In [5]:
pip install basketball-reference-scraper

Requirement already satisfied: basketball-reference-scraper in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (1.0.26)
Requirement already satisfied: python-dateutil==2.8.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (2.8.1)
Requirement already satisfied: six==1.13.0 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (1.13.0)
Requirement already satisfied: numpy==1.18.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (1.18.1)
Requirement already satisfied: pandas==0.25.3 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (0.25.3)
Requirement already satisfied: bs4==0.0.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (0.0.1)
Requirement already satisfied: requests==2.22.0 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (2.22.0)
Requirement already satisfied: pytz==2019.3 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (2019.3)
Requirement already satisfied: beautifulsoup4==4.8.2 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (4.8.2)
Requirement already satisfied: lxml==4.4.2 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (4.4.2)
Requirement already satisfied: soupsieve==1.9.5 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (1.9.5)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (1.25.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (2020.6.20)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/jeremyjang/opt/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (2.8)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from basketball_reference_scraper.teams import get_roster, get_team_stats, get_opp_stats, get_roster_stats, get_team_misc

In [8]:
s = get_team_stats('GSW', 2019, data_format='PER_GAME')
print(s)

G              82
MP          241.5
FG             44
FGA          89.8
FG%         0.491
3P           13.3
3PA          34.4
3P%         0.385
2P           30.8
2PA          55.3
2P%         0.557
FT           16.3
FTA          20.4
FT%         0.801
ORB           9.7
DRB          36.5
TRB          46.2
AST          29.4
STL           7.6
BLK           6.4
TOV          14.3
PF           21.4
PTS         117.7
TEAM          GSW
SEASON    2018-19
dtype: object

In [6]:
s = get_opp_stats('GSW', 2019, data_format='PER_GAME')
print(s)

OPP_G           82
OPP_MP       241.5
OPP_FG        40.4
OPP_FGA       91.1
OPP_FG%      0.444
OPP_3P        11.6
OPP_3PA       33.6
OPP_3P%      0.347
OPP_2P        28.8
OPP_2PA       57.5
OPP_2P%        0.5
OPP_FT        18.7
OPP_FTA       24.2
OPP_FT%      0.773
OPP_ORB       10.8
OPP_DRB       33.5
OPP_TRB       44.3
OPP_AST       24.3
OPP_STL        7.7
OPP_BLK        3.6
OPP_TOV       13.5
OPP_PF        19.5
OPP_PTS      111.2
TEAM           GSW
SEASON     2018-19
dtype: object

In [9]:
from basketball_reference_scraper.box_scores import get_box_scores

s = get_box_scores('2020-01-13', 'CHI', 'BOS', period='GAME', stat_type='BASIC')
print(s)

{'CHI':                 PLAYER     MP  FG FGA    FG% 3P 3PA    3P%  FT FTA  ... ORB  \
0          Zach LaVine  34:52   9  18   .500  3   6   .500   9   9  ...   1
1            Kris Dunn  30:01   3   7   .429  1   2   .500   2   3  ...   0
2     Tomáš Satoranský  25:55   3   8   .375  0   1   .000   6   8  ...   1
3      Lauri Markkanen  25:20   4   9   .444  0   3   .000   1   2  ...   1
4       Daniel Gafford  20:24   4   5   .800  0   0    NaN   2   2  ...   2
5       Thaddeus Young  24:23   8  14   .571  1   4   .250   0   0  ...   0
6           Coby White  23:23   3   8   .375  0   4   .000   0   0  ...   1
7          Luke Kornet  21:53   0   2   .000  0   2   .000   0   0  ...   0
8   Chandler Hutchison  14:24   1   5   .200  0   0    NaN   0   0  ...   1
9     Ryan Arcidiacono  13:25   0   2   .000  0   2   .000   0   0  ...   0
10    Denzel Valentine   2:00   2   2  1.000  1   1  1.000   0   0  ...   0
11  Shaquille Harrison   2:00   0   1   .000  0   0    NaN   1   2  ...   0
12   Cristiano Felício   2:00   0   0    NaN  0   0    NaN   0   0  ...   0
13         Team Totals    240  37  81   .457  6  25   .240  21  26  ...   7

   DRB TRB AST STL BLK TOV  PF  PTS  +/-
0    4   5   2   1   0   6   3   30   -7
1    5   5   1   0   0   2   2    9   -5
2    0   1   7   1   0   2   2   12   +3
3    5   6   0   2   0   0   3    9   -5
4    1   3   1   0   2   0   4   10   +8
5    2   2   1   0   0   1   1   17  -11
6    2   3   4   0   0   1   1    6  -18
7    5   5   0   0   1   1   2    0  -24
8    2   3   0   1   2   1   2    2   -6
9    3   3   0   0   0   0   2    0   -7
10   1   1   0   0   0   0   0    5   +4
11   1   1   0   0   0   0   0    1   +4
12   0   0   0   0   0   0   0    0   +4
13  31  38  16   5   5  14  22  101  NaN

[14 rows x 21 columns], 'BOS':              PLAYER     MP  FG FGA   FG% 3P 3PA    3P%  FT FTA  ... ORB DRB  \
0      Jaylen Brown  30:15   5  13  .385  0   1   .000   9   9  ...   2   1
1    Gordon Hayward  30:09   4  11  .364  0   1   .000   0   0  ...   0   6
2      Jayson Tatum  29:43   7  17  .412  2   7   .286   5   7  ...   0   6
3      Kemba Walker  27:36   5   9  .556  3   6   .500   1   2  ...   0   4
4       Enes Kanter  26:27   7   9  .778  0   0    NaN   1   1  ...   2   7
5      Marcus Smart  33:24   4   8  .500  2   5   .400   2   2  ...   0   5
6    Brad Wanamaker  24:11   3   5  .600  1   1  1.000   2   2  ...   1   2
7    Grant Williams  16:17   4   8  .500  1   2   .500   2   2  ...   4   1
8      Semi Ojeleye  12:57   0   0   NaN  0   0    NaN   0   0  ...   1   0
9   Vincent Poirier   5:01   0   3  .000  0   0    NaN   2   2  ...   0   0
10   Romeo Langford   2:00   0   0   NaN  0   0    NaN   2   2  ...   0   0
11    Javonte Green   2:00   0   0   NaN  0   0    NaN   0   0  ...   0   1
12      Team Totals    240  39  83  .470  9  23   .391  26  29  ...  10  33

   TRB AST STL BLK TOV  PF  PTS  +/-
0    3   3   2   0   0   3   19  +10
1    6   8   0   0   1   3    8  +14
2    6   2   1   2   1   1   21   -2
3    4   2   0   2   2   1   14   +2
4    9   0   1   1   5   3   15   +4
5    5   8   3   0   1   3   12  +25
6    3   2   0   0   0   1    9   +7
7    5   3   0   1   1   2   11  +11
8    1   0   0   0   0   0    0    0
9    0   0   0   0   1   2    2   -3
10   0   0   0   0   0   0    2   -4
11   1   0   0   0   0   0    0   -4
12  43  28   7   6  12  19  113  NaN

[13 rows x 21 columns]}

In [11]:
from basketball_reference_scraper.seasons import get_schedule, get_standings

s = get_schedule(2020, playoffs=False)
print(s)

           DATE                VISITOR  VISITOR_PTS                    HOME  \
0    2019-10-22   New Orleans Pelicans          122         Toronto Raptors
1    2019-10-22     Los Angeles Lakers          102    Los Angeles Clippers
2    2019-10-23         Denver Nuggets          108  Portland Trail Blazers
3    2019-10-23       Sacramento Kings           95            Phoenix Suns
4    2019-10-23  Oklahoma City Thunder           95               Utah Jazz
...         ...                    ...          ...                     ...
1055 2020-08-14         Denver Nuggets          109         Toronto Raptors
1056 2020-08-14             Miami Heat           92          Indiana Pacers
1057 2020-08-14  Oklahoma City Thunder          103    Los Angeles Clippers
1058 2020-08-14     Philadelphia 76ers          134         Houston Rockets
1059 2020-08-15      Memphis Grizzlies          122  Portland Trail Blazers

      HOME_PTS
0          130
1          112
2          100
3          124
4          100
...        ...
1055       117
1056       109
1057       107
1058        96
1059       126

[1060 rows x 5 columns]

In [14]:
from basketball_reference_scraper.shot_charts import get_shot_chart

s = get_shot_chart('2020-01-13', 'CHI', 'BOS')
print(s)

{'CHI':           x        y  QUARTER TIME_REMAINING              PLAYER MAKE_MISS  \
0   13.8 ft  26.7 ft        1        11:17.0     Lauri Markkanen      MISS
1   31.7 ft  17.6 ft        1        10:37.0    Tomáš Satoranský      MISS
2   32.0 ft  8.26 ft        1        10:06.0     Lauri Markkanen      MISS
3   24.0 ft  2.68 ft        1        10:05.0     Lauri Markkanen      MAKE
4   24.5 ft  4.97 ft        1         9:13.0      Daniel Gafford      MAKE
..      ...      ...      ...            ...                 ...       ...
76  25.3 ft  3.58 ft        4         3:35.0         Zach LaVine      MAKE
77  8.20 ft  27.8 ft        4         2:54.0         Zach LaVine      MAKE
78  17.7 ft  11.2 ft        4         1:47.0  Shaquille Harrison      MISS
79  17.2 ft  16.4 ft        4         0:54.0    Denzel Valentine      MAKE
80   6.1 ft  20.7 ft        4         0:18.0    Denzel Valentine      MAKE

    VALUE DISTANCE
0       3    26 ft
1       2    16 ft
2       2     9 ft
3       2     1 ft
4       2     2 ft
..    ...      ...
76      2     1 ft
77      3    29 ft
78      2    10 ft
79      2    15 ft
80      3    25 ft

[81 rows x 8 columns], 'BOS':           x        y  QUARTER TIME_REMAINING           PLAYER MAKE_MISS  \
0   25.9 ft  3.78 ft        1        11:35.0      Enes Kanter      MAKE
1    9.6 ft  9.55 ft        1        11:00.0     Jayson Tatum      MAKE
2   24.3 ft  4.77 ft        1         8:50.0      Enes Kanter      MAKE
3   22.5 ft  3.28 ft        1         8:19.0      Enes Kanter      MAKE
4   19.9 ft  8.16 ft        1         7:39.0     Jayson Tatum      MISS
..      ...      ...      ...            ...              ...       ...
78  25.3 ft  5.17 ft        4         3:03.0   Gordon Hayward      MAKE
79   6.7 ft  21.7 ft        4         2:39.0     Kemba Walker      MAKE
80  24.9 ft  29.1 ft        4         2:02.0     Kemba Walker      MAKE
81  34.1 ft  17.1 ft        4         1:33.0  Vincent Poirier      MISS
82  19.9 ft  5.17 ft        4         0:33.0  Vincent Poirier      MISS

    VALUE DISTANCE
0       2     2 ft
1       2    16 ft
2       2     2 ft
3       2     2 ft
4       2     6 ft
..    ...      ...
78      2     2 ft
79      3    25 ft
80      3    26 ft
81      2    17 ft
82      2     5 ft

[83 rows x 8 columns]}

In [15]:
from basketball_reference_scraper.injury_report import get_injury_report

s = get_injury_report()
print(s)

                PLAYER TEAM       DATE  \
0   Bogdan BogdanoviÄ‡  ATL 2021-01-12
1            Kris Dunn  ATL 2021-01-28
2      De'Andre Hunter  ATL 2021-01-30
3       Onyeka Okongwu  ATL 2021-02-01
4           Trae Young  ATL 2021-01-31
..                 ...  ...        ...
80       Patrick McCaw  TOR 2020-12-16
81       Norman Powell  TOR 2021-02-01
82       Elijah Hughes  UTA 2021-01-31
83       Thomas Bryant  WAS 2021-01-10
84           Raul Neto  WAS 2021-02-01

                                          DESCRIPTION          STATUS  \
0   General ManagerÃ‚Â Travis Schlenk said Bogdano...             Out
1   The Hawks announced that Dunn will miss at lea...             Out
2   The Hawks announced that Hunter will miss at l...             Out
3   Okongwu is questionable for Monday's (Feb. 1) ...      Day To Day
4   Young is probable for Monday's (Feb. 1) game a...      Day To Day
..                                                ...             ...
80  Raptors coach Nick Nurse said there's no timet...             Out
81  Powell is questionable for Tuesday's (Feb. 2) ...      Day To Day
82  Hughes did not play in Sunday's game (Jan. 31)...      Day To Day
83  Bryant tore the ACL in his left knee, accordin...  Out For Season
84  Wizards coach Scott Brooks said Neto is expect...             Out

         INJURY
0          Knee
1   Right ankle
2    Right knee
3      Achilles
4          Knee
..          ...
80         Knee
81         Quad
82        Ankle
83    Left knee
84        Groin

[85 rows x 6 columns]

In [16]:
from basketball_reference_scraper.players import get_game_logs, get_player_headshot

df = get_game_logs('Pau Gasol', '2010-01-12', '2010-01-20', playoffs=False)
print(df)

url = get_player_headshot('Kobe Bryant')
print(url)

You searched for "Pau Gasol"
7 results found.
0: Pau Gasol
1: Marc Gasol
2: Paul Watson
3: Paul Davis
4: Paul Grant
5: Paul Long
6: Paul Silas
Pick one: 0
Results for Pau Gasol:

         DATE     AGE TEAM HOME/AWAY OPPONENT   RESULT GS     MP FG FGA  ...  \
40 2010-01-15  29-193  LAL      HOME      LAC  W (+40)  1  30:29  4  10  ...
42 2010-01-18  29-196  LAL      HOME      ORL   W (+6)  1  39:32  8  14  ...

   DRB TRB AST STL BLK TOV PF PTS GAME_SCORE  +/-
40   2   6   3   0   3   1  0  20       21.2  +22
42   7  10   2   1   0   1  4  17       14.4   +7

[2 rows x 28 columns]
You searched for "Kobe Bryant"
4 results found.
0: Kobe Bryant
1: Joe Bryant
2: Em Bryant
3: Mark Bryant
Pick one: 0
Results for Kobe Bryant:

https://d2cwpp38twqe55.cloudfront.net/req/202006192/images/players/bryanko01.jpg

In [18]:
team_to_abbreviation = {
    "ATLANTA HAWKS" : "ATL",
    "ST. LOUIS HAWKS" : "SLH",
    "MILWAUKEE HAWKS" : "MIL",
    "TRI-CITIES BLACKHAWKS" : "TCB",
    "BOSTON CELTICS" : "BOS",
    "BROOKLYN NETS" : "BRK",
    "NEW JERSEY NETS" : "NJN",
    "CHICAGO BULLS" : "CHI",
    "CHARLOTTE HORNETS (1988-2004)": "CHH",
    "CHARLOTTE HORNETS (2014-Present)": "CHO",
    "CHARLOTTE BOBCATS" : "CHA",
    "CLEVELAND CAVALIERS": "CLE",
    "DALLAS MAVERICKS" : "DAL",
    "DENVER NUGGETS" : "DEN",
    "DETROIT PISTONS" : "DET",
    "FORT WAYNE PISTONS" : "FWP",
    "GOLDEN STATE WARRIORS" : "GSW",
    "SAN FRANCISCO WARRIORS" : "SFW",
    "PHILADELPHIA WARRIORS" : "PHI",
    "HOUSTON ROCKETS" : "HOU",
    "INDIANA PACERS" : "IND",
    "LOS ANGELES CLIPPERS" : "LAC",
    "SAN DIEGO CLIPPERS" : "SDC",
    "BUFFALO BRAVES" : "BUF",
    "LOS ANGELES LAKERS" : "LAL",
    "MINNEAPOLIS LAKERS" : "MIN",
    "MEMPHIS GRIZZLIES" : "MEM",
    "VANCOUVER GRIZZLIES" : 'VAN',
    "MIAMI HEAT" : "MIA",
    "MILWAUKEE BUCKS" : "MIL",
    "MINNESOTA TIMBERWOLVES" : "MIN",
    "NEW ORLEANS PELICANS" : "NOP",
    "NEW ORLEANS/OKLAHOMA CITY HORNETS" : "NOK",
    "NEW ORLEANS HORNETS" : "NOH",
    "NEW YORK KNICKS" : "NYK",
    "OKLAHOMA CITY THUNDER" : "OKC",
    "SEATTLE SUPERSONICS" : "SEA",
    "ORLANDO MAGIC" : "ORL",
    "PHILADELPHIA 76ERS" : "PHI",
    "SYRACUSE NATIONALS" : "SYR",
    "PHOENIX SUNS" : "PHO",
    "PORTLAND TRAIL BLAZERS" : "POR",
    "SACRAMENTO KINGS" : "SAC",
    "KANSAS CITY KINGS" : "KCK",
    "KANSAS CITY-OMAHA KINGS" : "KCK",
    "CINCINNATI ROYALS" : "CIN",
    "ROCHESTER ROYALS" : "ROR",
    "SAN ANTONIO SPURS" : "SAS",
    "TORONTO RAPTORS" : "TOR",
    "UTAH JAZZ" : "UTA",
    "NEW ORLEANS JAZZ" : "NOJ",
    "WASHINGTON WIZARDS" : "WAS",
    "WASHINGTON BULLETS" : "WAS",
    "CAPITAL BULLETS" : "CAP",
    "BALTIMORE BULLETS" : "BAL",
    "CHICAGO ZEPHYRS" : "CHI",
    "CHICAGO PACKERS" : "CHI",
    "ANDERSON PACKERS" : "AND",
    "CHICAGO STAGS" : "CHI",
    "INDIANAPOLIS OLYMPIANS" : "IND",
    "SHEBOYGAN RED SKINS" : "SRS",
    "ST. LOUIS BOMBERS" : "SLB",
    "WASHINGTON CAPITOLS" : "WAS",
    "WATERLOO HAWKS" : "WAT"
}

In [38]:
# get a team's past 10 games from a given date:

#let's look at Golden State's 73-9 record from the 2015-2016 season
season_2016_df = get_schedule(2016, playoffs=False)

season_2016_df

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS
0,2015-10-27,Cleveland Cavaliers,95,Chicago Bulls,97
1,2015-10-27,Detroit Pistons,106,Atlanta Hawks,94
2,2015-10-27,New Orleans Pelicans,95,Golden State Warriors,111
3,2015-10-28,Washington Wizards,88,Orlando Magic,87
4,2015-10-28,Philadelphia 76ers,95,Boston Celtics,112
...,...,...,...,...,...
1225,2016-04-13,Atlanta Hawks,98,Washington Wizards,109
1226,2016-04-13,Memphis Grizzlies,104,Golden State Warriors,125
1227,2016-04-13,Utah Jazz,96,Los Angeles Lakers,101
1228,2016-04-13,Los Angeles Clippers,105,Phoenix Suns,114
1229,2016-04-13,Denver Nuggets,99,Portland Trail Blazers,107

In [32]:
#their largest loss was against the Blazers, on 2016-02-19, so we'll grab all the data of warrior games before this date
season_2016_pre_big_loss = season_2016_df.loc[(season_2016_df["DATE"] < "2016-02-19")]
#a line that didnt work: (team_to_abbreviation[str(season_2016_df["VISITOR"]).upper()] == "GSW" or team_to_abbreviation[str(season_2016_df["HOME"]).upper()] == "GSW")

# warriors_2016_pre_big_loss =  season_2016_pre_big_loss.loc[(team_to_abbreviation[season_2016_df["VISITOR"]] == "Golden State Warriors" | team_to_abbreviation[season_2016_df["HOME"]] == "Golden State Warriors")]

In [48]:
import pandas as pd
# warriors_2016_pre_big_loss = pd.DataFrame()

# for rows in season_2016_pre_big_loss:
#     if ((rows["HOME"] == "Golden State Warriors") or (rows ["VISITOR"] == "Golden State Warriors")):
#         warriors_2016_pre_big_loss.append(rows)
        
warriors_2016_home = season_2016_pre_big_loss.loc[(season_2016_df["HOME"] == "Golden State Warriors")]
warriors_2016_visitor = season_2016_pre_big_loss.loc[(season_2016_df["VISITOR"] == "Golden State Warriors")]

season = [warriors_2016_home, warriors_2016_visitor]

warriors_season = pd.concat(season)

warriors_season=  warriors_season.sort_values(by="DATE", ascending = False)

# warriors_season
last_10_games = pd.DataFrame(warriors_season[0:11])
last_10_games

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS
797,2016-02-10,Golden State Warriors,112,Phoenix Suns,104
786,2016-02-09,Houston Rockets,110,Golden State Warriors,123
766,2016-02-06,Oklahoma City Thunder,108,Golden State Warriors,116
738,2016-02-03,Golden State Warriors,134,Washington Wizards,121
716,2016-01-31,Golden State Warriors,116,New York Knicks,95
705,2016-01-30,Golden State Warriors,108,Philadelphia 76ers,105
689,2016-01-27,Dallas Mavericks,107,Golden State Warriors,127
673,2016-01-25,San Antonio Spurs,90,Golden State Warriors,120
651,2016-01-22,Indiana Pacers,110,Golden State Warriors,122
633,2016-01-20,Golden State Warriors,125,Chicago Bulls,94
621,2016-01-18,Golden State Warriors,132,Cleveland Cavaliers,98

In [73]:
last_10_games_stats = []
game_date = last_10_games.iloc[0]["DATE"]
date_no_time = str(game_date).split()[0]
date_no_time

visitor_team = team_to_abbreviation[last_10_games.iloc[0]["VISITOR"].upper()]
visitor_team

home_team = team_to_abbreviation[last_10_games.iloc[0]["HOME"].upper()]
home_team

team_box_score = get_box_scores(date_no_time, visitor_team, home_team, period='GAME', stat_type='BASIC')
team_box_score = pd.DataFrame(team_box_score["GSW"])

team_box_score.tail(1)


# for index, row in last_10_games.iterrows():
#     print("hi")

,PLAYER,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
13,Team Totals,240,37,89,.416,14,40,.350,24,29,...,8,42,50,24,12,7,13,22,112,NaN