In [49]:
import pandas as pd
box_score = pd.read_csv('03_03box_score_combined.csv')

In [50]:
calculated_df = pd.read_csv('03_03_calculated_df_full.csv')

In [51]:
box_score['diff_%'] = box_score['home_winning_percentage'] - box_score['visitor_winning_percentage']
calculated_df['diff_%'] = calculated_df['home_winning_percentage'] - calculated_df['visitor_winning_percentage']

In [52]:
box_score.columns

Index(['DATE', 'HOME_ABBR', 'VISITOR_ABBR', 'PTS_home', 'PTS_away', 'MARGIN',
       'HOME_TEAM_WINS', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home',
       'AST_home', 'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away', 'home_winning_percentage',
       'visitor_winning_percentage', 'diff_%'],
      dtype='object')

In [53]:
box_score_2 = box_score[['DATE', 'HOME_ABBR', 'VISITOR_ABBR', 'PTS_home', 'PTS_away', 'MARGIN',
       'HOME_TEAM_WINS', 'home_winning_percentage', 'visitor_winning_percentage', 'diff_%']]

In [54]:
calculated_df_2 = calculated_df[['DATE', 'HOME_ABBR', 'VISITOR_ABBR', 'PTS_home', 'PTS_away', 'MARGIN', 'home_winning_percentage', 'visitor_winning_percentage', 'diff_%']]

In [55]:
calculated_df_2_explanation = 'box_score - grouped_values from the previous 10 games'

In [67]:
home_user_input = input('which home team do you want to take a look at?')

which home team do you want to take a look at?NOP

In [68]:
visitor_user_input = input('which visitor team do you want to take a look at?')

which visitor team do you want to take a look at?SAC

In [69]:
box_score_2.loc[box_score_2['HOME_ABBR'] == home_user_input].tail(10)

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,home_winning_percentage,visitor_winning_percentage,diff_%
701,2022-01-24,NOP,IND,117,113,4,1,0.391304,0.354167,0.037138
731,2022-01-28,NOP,DEN,105,116,-11,0,0.375000,0.562500,-0.187500
737,2022-01-29,NOP,BOS,97,107,-10,0,0.367347,0.509804,-0.142457
812,2022-02-08,NOP,HOU,110,97,13,1,0.407407,0.277778,0.129630
825,2022-02-10,NOP,MIA,97,112,-15,0,0.400000,0.642857,-0.242857
840,2022-02-12,NOP,SAS,114,124,-10,0,0.392857,0.385965,0.006892
856,2022-02-14,NOP,TOR,120,90,30,1,0.403509,0.553571,-0.150063
865,2022-02-15,NOP,MEM,109,121,-12,0,0.396552,0.694915,-0.298364
880,2022-02-17,NOP,DAL,118,125,-7,0,0.389831,0.593220,-0.203390
925,2022-03-02,NOP,SAC,125,95,30,1,0.419355,0.365079,0.054275

In [70]:
box_score_2.loc[box_score_2['VISITOR_ABBR'] == visitor_user_input].tail(10)

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,home_winning_percentage,visitor_winning_percentage,diff_%
708,2022-01-25,BOS,SAC,128,75,53,1,0.510204,0.367347,0.142857
716,2022-01-26,ATL,SAC,121,104,17,1,0.468085,0.360000,0.108085
738,2022-01-29,PHI,SAC,103,101,2,1,0.612245,0.352941,0.259304
755,2022-01-31,NYK,SAC,116,96,20,1,0.470588,0.346154,0.124434
778,2022-02-03,GSW,SAC,126,114,12,1,0.754717,0.351852,0.402865
841,2022-02-12,WAS,SAC,110,123,-13,0,0.454545,0.379310,0.075235
852,2022-02-14,BRK,SAC,109,85,24,1,0.526316,0.372881,0.153434
871,2022-02-16,CHI,SAC,125,118,7,1,0.644068,0.366667,0.277401
913,2022-02-28,OKC,SAC,110,131,-21,0,0.311475,0.370968,-0.059492
925,2022-03-02,NOP,SAC,125,95,30,1,0.419355,0.365079,0.054275

In [72]:
calculated_df_2.loc[calculated_df_2['HOME_ABBR'] == home_user_input].tail(10)

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,home_winning_percentage,visitor_winning_percentage,diff_%
503,2022-01-24,NOP,IND,5.8,3.4,2.4,0.391304,0.354167,0.037138
533,2022-01-28,NOP,DEN,-6.2,-1.6,-4.6,0.375000,0.562500,-0.187500
539,2022-01-29,NOP,BOS,-14.2,-5.9,-8.3,0.367347,0.509804,-0.142457
614,2022-02-08,NOP,HOU,-1.2,-12.8,11.6,0.407407,0.277778,0.129630
627,2022-02-10,NOP,MIA,-14.2,2.0,-16.2,0.400000,0.642857,-0.242857
642,2022-02-12,NOP,SAS,2.8,6.3,-3.5,0.392857,0.385965,0.006892
658,2022-02-14,NOP,TOR,8.8,-22.6,31.4,0.403509,0.553571,-0.150063
667,2022-02-15,NOP,MEM,-2.2,1.3,-3.5,0.396552,0.694915,-0.298364
682,2022-02-17,NOP,DAL,6.8,16.4,-9.6,0.389831,0.593220,-0.203390
727,2022-03-02,NOP,SAC,13.8,-9.2,23.0,0.419355,0.365079,0.054275

In [73]:
calculated_df_2.loc[calculated_df_2['VISITOR_ABBR'] == visitor_user_input].tail(10)

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,home_winning_percentage,visitor_winning_percentage,diff_%
510,2022-01-25,BOS,SAC,17.5,-29.2,46.7,0.510204,0.367347,0.142857
518,2022-01-26,ATL,SAC,0.6,-0.2,0.8,0.468085,0.360000,0.108085
540,2022-01-29,PHI,SAC,-4.2,-3.2,-1.0,0.612245,0.352941,0.259304
557,2022-01-31,NYK,SAC,10.0,-8.2,18.2,0.470588,0.346154,0.124434
580,2022-02-03,GSW,SAC,12.3,9.8,2.5,0.754717,0.351852,0.402865
643,2022-02-12,WAS,SAC,1.8,18.8,-17.0,0.454545,0.379310,0.075235
654,2022-02-14,BRK,SAC,2.0,-19.2,21.2,0.526316,0.372881,0.153434
673,2022-02-16,CHI,SAC,5.4,13.8,-8.4,0.644068,0.366667,0.277401
715,2022-02-28,OKC,SAC,6.9,26.8,-19.9,0.311475,0.370968,-0.059492
727,2022-03-02,NOP,SAC,13.8,-9.2,23.0,0.419355,0.365079,0.054275

In [74]:
home_df = calculated_df_2[calculated_df_2['HOME_ABBR'] == home_user_input]
home_df = home_df.round({"diff_%":1})
mean_grouped_home_df = home_df.groupby("diff_%").mean().reset_index()
mean_grouped_home_df

,diff_%,PTS_home,PTS_away,MARGIN,home_winning_percentage,visitor_winning_percentage
0,-0.4,-4.000000,-7.620000,3.620000,0.285780,0.690057
1,-0.3,-4.200000,3.025000,-7.225000,0.281757,0.582102
2,-0.2,-0.866667,-1.033333,0.166667,0.366505,0.573397
3,-0.1,1.050000,-7.875000,8.925000,0.364476,0.473058
4,0.0,4.300000,4.850000,-0.550000,0.392081,0.370066
5,0.1,3.466667,-12.500000,15.966667,0.370826,0.267619

In [75]:
visitor_df = calculated_df_2[calculated_df_2['VISITOR_ABBR'] == visitor_user_input]
visitor_df = visitor_df.round({"diff_%":1})
mean_grouped_visitor_df = visitor_df.groupby("diff_%").mean().reset_index()
mean_grouped_visitor_df

,diff_%,PTS_home,PTS_away,MARGIN,home_winning_percentage,visitor_winning_percentage
0,-0.2,-0.400000,24.8,-25.200000,0.230769,0.428571
1,-0.1,6.900000,26.8,-19.900000,0.311475,0.370968
2,-0.0,-6.550000,-11.7,5.150000,0.370879,0.390476
3,0.1,10.941667,4.8,6.141667,0.486875,0.383882
4,0.2,10.433333,0.8,9.633333,0.569996,0.385096
5,0.3,0.600000,5.3,-4.700000,0.628156,0.359804
6,0.4,5.800000,1.8,4.000000,0.780584,0.379051