In [111]:
#from basketball_reference_scraper.seasons import get_schedule, get_standings
#schedule_df = get_schedule(2021, playoffs=False`)

In [114]:
#schedule_df.to_csv('schedule_df.csv', index=False)

grabbing the boxscore and making an id lane

In [14]:
#import dependencies
import sqlalchemy
# Import dependencies
import pandas as pd
from sqlalchemy import create_engine

# N.B. external config.py file should be formatted like:
# login = 'postgres:password' where password is set to whatever your database password is. Default username is 
# postgres, but change this if you use a different username.
import psycopg2
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'
                .format(username='postgres',
                        password='postgres',
                        ipaddress='localhost',
                        port=5432,
                        dbname='flask_deploy'))
# Create the connection
engine = create_engine(postgres_str)
cnx = engine.connect()

In [16]:
boxscore_df = pd.read_csv('data/boxscore_2021.csv')

In [17]:
boxscore_df

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,margin,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,2020-12-22,BRK,GSW,125.0,99.0,26,0.457,0.813,0.429,24,57,0.374,0.652,0.303,26,47
1,2020-12-22,LAL,LAC,109.0,116.0,-7,0.469,0.774,0.310,22,45,0.473,0.737,0.350,22,40
2,2020-12-23,CLE,CHO,121.0,114.0,7,0.529,0.750,0.467,34,50,0.500,0.533,0.364,29,32
3,2020-12-23,IND,NYK,121.0,107.0,14,0.489,0.724,0.235,28,50,0.459,0.739,0.429,25,40
4,2020-12-23,ORL,MIA,113.0,107.0,6,0.477,0.633,0.357,23,41,0.506,0.842,0.350,25,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,2021-02-01,MIL,POR,134.0,106.0,28,0.552,0.583,0.500,38,53,0.375,1.000,0.357,19,45
294,2021-02-01,NOP,SAC,109.0,118.0,-9,0.396,0.833,0.300,22,46,0.477,0.769,0.326,31,52
295,2021-02-01,OKC,HOU,106.0,136.0,-30,0.438,0.789,0.382,21,45,0.480,0.909,0.538,30,50
296,2021-02-01,DAL,PHO,108.0,109.0,-1,0.430,0.960,0.313,16,42,0.467,0.833,0.371,19,45
297,2021-02-01,SAS,MEM,102.0,133.0,-31,0.416,0.682,0.351,28,42,0.559,0.778,0.500,37,53

In [18]:
a_ = list(range(1, 299))

In [19]:
a_ = pd.Series(a_)

In [20]:
boxscore_df['ID'] = a_

```sql

CREATE TABLE boxscore_2021 (
    "ID" INT PRIMARY KEY, 
    "DATE" DATE,
    "HOME_ABBR" VARCHAR,
	"MARGIN" INT,
    "VISITOR_ABBR" VARCHAR,
    "PTS_home" INT,
    "PTS_away" INT,
    "FG_PCT_home" DOUBLE PRECISION,
    "FT_PCT_home" DOUBLE PRECISION,
    "FG3_PCT_home" DOUBLE PRECISION,
    "AST_home" INT,
    "REB_home" INT,
    "FG_PCT_away" DOUBLE PRECISION,
    "FT_PCT_away" DOUBLE PRECISION,
    "FG3_PCT_away" DOUBLE PRECISION,
    "AST_away" INT,
    "REB_away" INT
);

```

In [21]:
#import dependencies
import sqlalchemy
# Import dependencies
import pandas as pd
from sqlalchemy import create_engine

# N.B. external config.py file should be formatted like:
# login = 'postgres:password' where password is set to whatever your database password is. Default username is 
# postgres, but change this if you use a different username.
import psycopg2
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session

In [22]:
postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'
                .format(username='postgres',
                        password='postgres',
                        ipaddress='localhost',
                        port=5432,
                        dbname='flask_deploy'))
# Create the connection
engine = create_engine(postgres_str)
cnx = engine.connect()

In [27]:
boxscore_df.head(1)

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,ID
0,2020-12-22,BRK,GSW,125.0,99.0,26,0.457,0.813,0.429,24,57,0.374,0.652,0.303,26,47,1

In [26]:
boxscore_df = boxscore_df.rename(columns={'margin':'MARGIN'})

In [28]:
boxscore_df.to_sql('boxscore_2021', engine, if_exists='append', index=False)

In [29]:
boxscore_df.to_csv('boxscore_2021_V2.csv', index=False)

In [6]:
len(boxscore_df)

298

In [1]:
import pandas as pd

In [30]:
#already ran, so read later
#run this to get schedle_df
schedule_df = pd.read_csv('data/schedule2021.csv')

In [31]:
schedule_df.head()

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,VISITOR_ABBR,HOME_ABBR
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,GSW,BRK
1,2020-12-22,LOS ANGELES CLIPPERS,116.0,LOS ANGELES LAKERS,109.0,LAC,LAL
2,2020-12-23,CHARLOTTE HORNETS,114.0,CLEVELAND CAVALIERS,121.0,CHO,CLE
3,2020-12-23,NEW YORK KNICKS,107.0,INDIANA PACERS,121.0,NYK,IND
4,2020-12-23,MIAMI HEAT,107.0,ORLANDO MAGIC,113.0,MIA,ORL

In [39]:
len(schedule_df)

540

In [40]:
schedule_df

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,VISITOR_ABBR,HOME_ABBR,ID
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,GSW,BRK,1
1,2020-12-22,LOS ANGELES CLIPPERS,116.0,LOS ANGELES LAKERS,109.0,LAC,LAL,2
2,2020-12-23,CHARLOTTE HORNETS,114.0,CLEVELAND CAVALIERS,121.0,CHO,CLE,3
3,2020-12-23,NEW YORK KNICKS,107.0,INDIANA PACERS,121.0,NYK,IND,4
4,2020-12-23,MIAMI HEAT,107.0,ORLANDO MAGIC,113.0,MIA,ORL,5
...,...,...,...,...,...,...,...,...
535,2021-03-04,MILWAUKEE BUCKS,0.0,MEMPHIS GRIZZLIES,0.0,MIL,MEM,536
536,2021-03-04,OKLAHOMA CITY THUNDER,0.0,SAN ANTONIO SPURS,0.0,OKC,SAS,537
537,2021-03-04,MIAMI HEAT,0.0,NEW ORLEANS PELICANS,0.0,MIA,NOP,538
538,2021-03-04,GOLDEN STATE WARRIORS,0.0,PHOENIX SUNS,0.0,GSW,PHO,539
539,2021-03-04,SACRAMENTO KINGS,0.0,PORTLAND TRAIL BLAZERS,0.0,SAC,POR,540

In [33]:
b_ = list(range(1,541))

In [34]:
b_ = pd.Series(b_)

In [35]:
schedule_df['ID'] = b_

In [38]:
schedule_df.to_csv('schedule_2021_V2.csv', index=False)

In [37]:
len(schedule_df)

540

In [9]:
schedule_df.loc[schedule_df['HOME_ABBR'] == 'LAL']

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,VISITOR_ABBR,HOME_ABBR
1,2020-12-22,LOS ANGELES CLIPPERS,116.0,LOS ANGELES LAKERS,109.0,LAC,LAL
17,2020-12-25,DALLAS MAVERICKS,115.0,LOS ANGELES LAKERS,138.0,DAL,LAL
38,2020-12-27,MINNESOTA TIMBERWOLVES,91.0,LOS ANGELES LAKERS,127.0,MIN,LAL
43,2020-12-28,PORTLAND TRAIL BLAZERS,115.0,LOS ANGELES LAKERS,107.0,POR,LAL
119,2021-01-07,SAN ANTONIO SPURS,118.0,LOS ANGELES LAKERS,109.0,SAS,LAL
129,2021-01-08,CHICAGO BULLS,115.0,LOS ANGELES LAKERS,117.0,CHI,LAL
176,2021-01-15,NEW ORLEANS PELICANS,95.0,LOS ANGELES LAKERS,112.0,NOP,LAL
197,2021-01-18,GOLDEN STATE WARRIORS,115.0,LOS ANGELES LAKERS,113.0,GSW,LAL
318,2021-02-04,DENVER NUGGETS,0.0,LOS ANGELES LAKERS,0.0,DEN,LAL
338,2021-02-06,DETROIT PISTONS,0.0,LOS ANGELES LAKERS,0.0,DET,LAL
351,2021-02-08,OKLAHOMA CITY THUNDER,0.0,LOS ANGELES LAKERS,0.0,OKC,LAL
366,2021-02-10,OKLAHOMA CITY THUNDER,0.0,LOS ANGELES LAKERS,0.0,OKC,LAL
381,2021-02-12,MEMPHIS GRIZZLIES,0.0,LOS ANGELES LAKERS,0.0,MEM,LAL
426,2021-02-18,BROOKLYN NETS,0.0,LOS ANGELES LAKERS,0.0,BRK,LAL
443,2021-02-20,MIAMI HEAT,0.0,LOS ANGELES LAKERS,0.0,MIA,LAL
459,2021-02-22,WASHINGTON WIZARDS,0.0,LOS ANGELES LAKERS,0.0,WAS,LAL
492,2021-02-26,PORTLAND TRAIL BLAZERS,0.0,LOS ANGELES LAKERS,0.0,POR,LAL
506,2021-02-28,GOLDEN STATE WARRIORS,0.0,LOS ANGELES LAKERS,0.0,GSW,LAL
522,2021-03-02,PHOENIX SUNS,0.0,LOS ANGELES LAKERS,0.0,PHO,LAL

Grabbing variables to run
```python
schedule_df.loc[0]['DATE'] 
```

Tutorial

```Python

teams = new_stats['MP'].str.split(':', expand=True).astype(int)

```

Tutorial
```python
for ind in schedule_df.index: 
    df2['margin'][ind] = df2['PTS_home'][ind] - df2['PTS_away'][ind]
```

In [165]:
team_to_abbreviation = {
    "ATLANTA HAWKS" : "ATL",
    "ST. LOUIS HAWKS" : "SLH",
    "MILWAUKEE HAWKS" : "MIL",
    "TRI-CITIES BLACKHAWKS" : "TCB",
    "BOSTON CELTICS" : "BOS",
    "BROOKLYN NETS" : "BRK",
    "NEW JERSEY NETS" : "NJN",
    "CHICAGO BULLS" : "CHI",
    "CHARLOTTE HORNETS": "CHO",
    "CHARLOTTE BOBCATS" : "CHA",
    "CLEVELAND CAVALIERS": "CLE",
    "DALLAS MAVERICKS" : "DAL",
    "DENVER NUGGETS" : "DEN",
    "DETROIT PISTONS" : "DET",
    "FORT WAYNE PISTONS" : "FWP",
    "GOLDEN STATE WARRIORS" : "GSW",
    "SAN FRANCISCO WARRIORS" : "SFW",
    "PHILADELPHIA WARRIORS" : "PHI",
    "HOUSTON ROCKETS" : "HOU",
    "INDIANA PACERS" : "IND",
    "LOS ANGELES CLIPPERS" : "LAC",
    "SAN DIEGO CLIPPERS" : "SDC",
    "BUFFALO BRAVES" : "BUF",
    "LOS ANGELES LAKERS" : "LAL",
    "MINNEAPOLIS LAKERS" : "MIN",
    "MEMPHIS GRIZZLIES" : "MEM",
    "VANCOUVER GRIZZLIES" : 'VAN',
    "MIAMI HEAT" : "MIA",
    "MILWAUKEE BUCKS" : "MIL",
    "MINNESOTA TIMBERWOLVES" : "MIN",
    "NEW ORLEANS PELICANS" : "NOP",
    "NEW ORLEANS/OKLAHOMA CITY HORNETS" : "NOK",
    "NEW ORLEANS HORNETS" : "NOH",
    "NEW YORK KNICKS" : "NYK",
    "OKLAHOMA CITY THUNDER" : "OKC",
    "SEATTLE SUPERSONICS" : "SEA",
    "ORLANDO MAGIC" : "ORL",
    "PHILADELPHIA 76ERS" : "PHI",
    "SYRACUSE NATIONALS" : "SYR",
    "PHOENIX SUNS" : "PHO",
    "PORTLAND TRAIL BLAZERS" : "POR",
    "SACRAMENTO KINGS" : "SAC",
    "KANSAS CITY KINGS" : "KCK",
    "KANSAS CITY-OMAHA KINGS" : "KCK",
    "CINCINNATI ROYALS" : "CIN",
    "ROCHESTER ROYALS" : "ROR",
    "SAN ANTONIO SPURS" : "SAS",
    "TORONTO RAPTORS" : "TOR",
    "UTAH JAZZ" : "UTA",
    "NEW ORLEANS JAZZ" : "NOJ",
    "WASHINGTON WIZARDS" : "WAS",
    "WASHINGTON BULLETS" : "WAS",
    "CAPITAL BULLETS" : "CAP",
    "BALTIMORE BULLETS" : "BAL",
    "CHICAGO ZEPHYRS" : "CHI",
    "CHICAGO PACKERS" : "CHI",
    "ANDERSON PACKERS" : "AND",
    "CHICAGO STAGS" : "CHI",
    "INDIANAPOLIS OLYMPIANS" : "IND",
    "SHEBOYGAN RED SKINS" : "SRS",
    "ST. LOUIS BOMBERS" : "SLB",
    "WASHINGTON CAPITOLS" : "WAS",
    "WATERLOO HAWKS" : "WAT"
}

In [174]:
#already ran so read this
#run this to add the abbreviations
for ind in schedule_df.index: 
    schedule_df['VISITOR'][ind] = schedule_df['VISITOR'][ind].upper()
    schedule_df['HOME'][ind] = schedule_df['HOME'][ind].upper()

/Users/stanleytan/anaconda3/envs/MachineLearning/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/stanleytan/anaconda3/envs/MachineLearning/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [169]:
#already ran so read this
#run this to include abbreviations
schedule_df['VISITOR_MASCOT'] = 0
schedule_df['HOME_MASCOT'] = 0

In [175]:
#already rean so read this
#run this to include abbreviations
for ind in schedule_df.index:
    visitor = schedule_df['VISITOR'][ind]
    home = schedule_df['HOME'][ind]
    schedule_df['VISITOR_MASCOT'][ind] = team_to_abbreviation[visitor]
    schedule_df['HOME_MASCOT'][ind] = team_to_abbreviation[home]

/Users/stanleytan/anaconda3/envs/MachineLearning/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/stanleytan/anaconda3/envs/MachineLearning/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [181]:
schedule_df.to_csv('schedule2021.csv', index=False)

In [1]:
import pandas as pd
from urllib.request import urlopen
from bs4 import BeautifulSoup
import numpy as np
pd.set_option('max_columns', None)

In [2]:
schedule_df = pd.read_csv('full_schedule_2021.csv')

In [3]:
schedule_df.tail(1)

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR,HOME_TEAM_WINS,ID
539,2021-03-04,SACRAMENTO KINGS,0.0,PORTLAND TRAIL BLAZERS,0.0,0,POR,SAC,0,540

In [5]:
schedule_df = schedule_df.fillna(0)

In [4]:
schedule_df.head()

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR,HOME_TEAM_WINS,ID
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,26,BRK,GSW,1,1
1,2020-12-22,LOS ANGELES CLIPPERS,116.0,LOS ANGELES LAKERS,109.0,-7,LAL,LAC,0,2
2,2020-12-23,CHARLOTTE HORNETS,114.0,CLEVELAND CAVALIERS,121.0,7,CLE,CHO,1,3
3,2020-12-23,NEW YORK KNICKS,107.0,INDIANA PACERS,121.0,14,IND,NYK,1,4
4,2020-12-23,MIAMI HEAT,107.0,ORLANDO MAGIC,113.0,6,ORL,MIA,1,5

In [8]:
for ind in schedule_df.index: 
    if schedule_df['VISITOR_PTS'][ind] > 0:
        schedule_df['MARGIN'][ind] = schedule_df['HOME_PTS'][ind] - schedule_df['VISITOR_PTS'][ind]
    else:
        break

/Users/stanleytan/anaconda3/envs/MachineLearning/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [9]:
schedule_df.head(1)

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,VISITOR_ABBR,HOME_ABBR,MARGIN
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,GSW,BRK,26

Tutorial -Replace
```python
df['name'].str.replace(r"\(.*\)","")
```

reference : <br>
https://www.basketball-reference.com/boxscores/202012260DET.html

grab things for the URL

.Format Tutorial
```python
>>> '{0}/{1}/{2}'.format('foo', 'bar', 'baz')

test_1 = 202012260
test_2 = "DET"

test_3 = "{0}{1}".format(test_1, test_2)
```

In [10]:
#grab DATE, HOME_ABBR, VISITOR_ABBR
box_score_columns = ['DATE', 'HOME_ABBR', 'VISITOR_ABBR', 'PTS_home', 'PTS_away', 'margin', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away', 'REB_away']
box_score_df = pd.DataFrame(columns=box_score_columns)

In [11]:
box_score_df

Empty DataFrame
Columns: [DATE, HOME_ABBR, VISITOR_ABBR, PTS_home, PTS_away, margin, FG_PCT_home, FT_PCT_home, FG3_PCT_home, AST_home, REB_home, FG_PCT_away, FT_PCT_away, FG3_PCT_away, AST_away, REB_away]
Index: []

In [12]:
from time import sleep

In [13]:
for ind in schedule_df.index:
    if schedule_df['VISITOR_PTS'][ind] > 0:
        date_1 = schedule_df.loc[ind]['DATE'].replace(r"-","") + "0"
        home_1 = schedule_df.loc[ind]['HOME_ABBR']
        visitor_1 = schedule_df.loc[ind]['VISITOR_ABBR']
        basketball_url = "https://www.basketball-reference.com/boxscores/"
        url = basketball_url + date_1 + home_1 + ".html"
        html = urlopen(url)
        soup = BeautifulSoup(html)
        table_home_abbr = "box-{0}-game-basic".format(home_1)
        table_visitor_abbr = "box-{0}-game-basic".format(visitor_1)
        table_home = soup.find('table', {"id":table_home_abbr})
        df_home = pd.read_html(str(table_home))
        df_home = df_home[0]
        new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
        np_array = np.arange(len(df_home.columns))
        list_ = np_array.tolist()
        df_home.columns = df_home.columns.droplevel(0)
#renaming columns
        for j in range(len(df_home.columns)):
            old = df_home.columns[j]
            new = new_columns[j]
            df_home = df_home.rename(columns = {old:new})
        table_visitor = soup.find('table', {"id":table_visitor_abbr})
        df_visitor = pd.read_html(str(table_visitor))
        df_visitor = df_visitor[0]
        new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
        np_array = np.arange(len(df_visitor.columns))
        list_ = np_array.tolist()
        df_visitor.columns = df_visitor.columns.droplevel(0)
#renaming columns
        for j in range(len(df_visitor.columns)):
            old = df_visitor.columns[j]
            new = new_columns[j]
            df_visitor = df_visitor.rename(columns = {old:new})
        empty_ = []
        empty_.append(schedule_df.loc[ind].iloc[0])
#DATE
        empty_.append(schedule_df.loc[ind].iloc[6])
#home abbbr
        empty_.append(schedule_df.loc[ind].iloc[5])
#visitor abbr
        empty_.append(schedule_df.loc[ind].iloc[4])
#home points
        empty_.append(schedule_df.loc[ind].iloc[2])
#away points
        empty_.append(schedule_df.loc[ind].iloc[7])
#margin
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS
        length_of_df = len(box_score_df)
        box_score_df.loc[length_of_df] = empty_
        sleep(0.5)

In [18]:
box_score_df.head(1)

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,margin,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,2020-12-22,BRK,26,125.0,99.0,GSW,.457,.813,.429,24,57,.374,.652,.303,26,47

```sql
CREATE TABLE box_score_2021 (
    "ID" INT PRIMARY KEY, 
    "DATE" DATE,a
    "HOME_ABBR" VARCHAR,
    "MARGIN" INT,
    "VISITOR_ABBR" VARCHAR,
    "PTS_home" INT,
    "PTS_away" INT,
    "FG_PCT_home" DOUBLE PRECISION,
    "FT_PCT_home" DOUBLE PRECISION,
    "FG3_PCT_home" DOUBLE PRECISION,
    "AST_home" INT,
    "REB_home" INT,
    "FG_PCT_away" DOUBLE PRECISION,
    "FT_PCT_away" DOUBLE PRECISION,
    "FG3_PCT_away" DOUBLE PRECISION,
    "AST_away" INT,
    "REB_away" INT
);
```

In [20]:
#import dependencies
import sqlalchemy
# Import dependencies
import pandas as pd
from sqlalchemy import create_engine

# N.B. external config.py file should be formatted like:
# login = 'postgres:password' where password is set to whatever your database password is. Default username is 
# postgres, but change this if you use a different username.
import psycopg2
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'
                .format(username='postgres',
                        password='postgres',
                        ipaddress='localhost',
                        port=5432,
                        dbname='flask_deploy'))
# Create the connection
engine = create_engine(postgres_str)
cnx = engine.connect()

In [16]:
box_score_df.tail(10)

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,margin,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
349,2021-02-08,PHO,6,119.0,113.0,CLE,.522,.737,.458,29,41,.512,.680,.333,23,39
350,2021-02-08,DEN,-13,112.0,125.0,MIL,.436,.938,.417,22,38,.506,.864,.400,24,50
351,2021-02-08,LAL,7,119.0,112.0,OKC,.463,.759,.237,28,59,.391,.737,.316,23,55
352,2021-02-09,DET,11,122.0,111.0,BRK,.560,.714,.448,28,37,.500,.875,.355,30,34
353,2021-02-09,MIA,2,98.0,96.0,NYK,.371,.821,.424,21,38,.425,.750,.357,22,46
354,2021-02-09,NOP,29,130.0,101.0,HOU,.511,.857,.387,31,55,.418,.571,.302,24,37
355,2021-02-09,SAS,-23,91.0,114.0,GSW,.372,.905,.333,20,45,.462,.684,.425,26,50
356,2021-02-09,POR,9,106.0,97.0,ORL,.389,.947,.391,18,54,.420,.545,.314,22,53
357,2021-02-09,SAC,-8,111.0,119.0,PHI,.434,.579,.333,24,39,.482,.800,.450,24,59
358,2021-02-09,UTA,14,122.0,108.0,BOS,.476,.889,.375,28,41,.442,.826,.448,18,35

In [17]:
box_score_df.to_csv('boxscore_2021_V2.csv', index=False)

In [34]:
for ind in schedule_df.head(5).index: 
    date_1 = schedule_df.loc[ind]['DATE'].replace(r"-","") + "0"
    home_1 = schedule_df.loc[ind]['HOME_ABBR']
    visitor_1 = schedule_df.loc[ind]['VISITOR_ABBR']
    basketball_url = "https://www.basketball-reference.com/boxscores/"
    url = basketball_url + date_1 + home_1 + ".html"
    html = urlopen(url)
    soup = BeautifulSoup(html)
    table_home_abbr = "box-{0}-game-basic".format(home_1)
    table_visitor_abbr = "box-{0}-game-basic".format(visitor_1)
    table_home = soup.find('table', {"id":table_home_abbr})
    df_home = pd.read_html(str(table_home))
    df_home = df_home[0]
    new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
    np_array = np.arange(len(df_home.columns))
    list_ = np_array.tolist()
    df_home.columns = df_home.columns.droplevel(0)
#renaming columns
    for j in range(len(df_home.columns)):
        old = df_home.columns[j]
        new = new_columns[j]
        df_home = df_home.rename(columns = {old:new})
    table_visitor = soup.find('table', {"id":table_visitor_abbr})
    df_visitor = pd.read_html(str(table_visitor))
    df_visitor = df_visitor[0]
    new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
    np_array = np.arange(len(df_visitor.columns))
    list_ = np_array.tolist()
    df_visitor.columns = df_visitor.columns.droplevel(0)
#renaming columns
    for j in range(len(df_visitor.columns)):
        old = df_visitor.columns[j]
        new = new_columns[j]
        df_visitor = df_visitor.rename(columns = {old:new})
    empty_ = []
    empty_.append(schedule_df.loc[ind].iloc[0])
#DATE
    empty_.append(schedule_df.loc[ind].iloc[6])
#home abbbr
    empty_.append(schedule_df.loc[ind].iloc[5])
#visitor abbr
    empty_.append(schedule_df.loc[ind].iloc[4])
#home points
    empty_.append(schedule_df.loc[ind].iloc[2])
#away points
    empty_.append(schedule_df.loc[ind].iloc[7])
#margin
    empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
    empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
    empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
    empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
    empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS
    empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
    empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
    empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
    empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
    empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS
    length_of_df = len(box_score_df)
    box_score_df.loc[length_of_df] = empty_
    sleep(0.5)

In [35]:
box_score_df

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,margin,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,2020-12-22,BRK,GSW,125.0,99.0,26,.457,.813,.429,24,57,.374,.652,.303,26,47
1,2020-12-22,BRK,GSW,125.0,99.0,26,.457,.813,.429,24,57,.374,.652,.303,26,47
2,2020-12-22,BRK,GSW,125.0,99.0,26,.469,.774,.310,22,45,.473,.737,.350,22,40
3,2020-12-22,BRK,GSW,125.0,99.0,26,.529,.750,.467,34,50,.500,.533,.364,29,32
4,2020-12-22,BRK,GSW,125.0,99.0,26,.489,.724,.235,28,50,.459,.739,.429,25,40
5,2020-12-22,BRK,GSW,125.0,99.0,26,.477,.633,.357,23,41,.506,.842,.350,25,43
6,2020-12-22,BRK,GSW,125.0,99.0,26,.457,.813,.429,24,57,.374,.652,.303,26,47
7,2020-12-22,LAL,LAC,109.0,116.0,-7,.469,.774,.310,22,45,.473,.737,.350,22,40
8,2020-12-23,CLE,CHO,121.0,114.0,7,.529,.750,.467,34,50,.500,.533,.364,29,32
9,2020-12-23,IND,NYK,121.0,107.0,14,.489,.724,.235,28,50,.459,.739,.429,25,40
10,2020-12-23,ORL,MIA,113.0,107.0,6,.477,.633,.357,23,41,.506,.842,.350,25,43

In [10]:
date_1 = schedule_df.loc[0]['DATE'].replace(r"-","") + "0"
home_1 = schedule_df.loc[0]['HOME_ABBR']
visitor_1 = schedule_df.loc[0]['VISITOR_ABBR']
basketball_url = "https://www.basketball-reference.com/boxscores/"
url = basketball_url + date_1 + home_1 + ".html"
html = urlopen(url)
soup = BeautifulSoup(html)

In [11]:
table_home_abbr = "box-{0}-game-basic".format(home_1)
table_visitor_abbr = "box-{0}-game-basic".format(visitor_1)

In [12]:
table_home = soup.find('table', {"id":table_home_abbr})
df_home = pd.read_html(str(table_home))
df_home = df_home[0]
new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
np_array = np.arange(len(df_home.columns))
list_ = np_array.tolist()
df_home.columns = df_home.columns.droplevel(0)
#renaming columns
for j in range(len(df_home.columns)):
    old = df_home.columns[j]
    new = new_columns[j]
    df_home = df_home.rename(columns = {old:new})

In [13]:
table_visitor = soup.find('table', {"id":table_visitor_abbr})
df_visitor = pd.read_html(str(table_visitor))
df_visitor = df_visitor[0]
new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
np_array = np.arange(len(df_visitor.columns))
list_ = np_array.tolist()
df_visitor.columns = df_visitor.columns.droplevel(0)
#renaming columns
for j in range(len(df_visitor.columns)):
    old = df_visitor.columns[j]
    new = new_columns[j]
    df_visitor = df_visitor.rename(columns = {old:new})

In [14]:
schedule_df.columns

Index(['DATE', 'VISITOR', 'VISITOR_PTS', 'HOME', 'HOME_PTS', 'VISITOR_ABBR',
       'HOME_ABBR', 'MARGIN'],
      dtype='object')

In [15]:
#grab DATE, HOME_ABBR, VISITOR_ABBR
box_score_columns = ['DATE', 'HOME_ABBR', 'VISITOR_ABBR', 'PTS_home', 'PTS_away', 'margin', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away', 'REB_away']

In [16]:
box_score_df = pd.DataFrame(columns=box_score_columns)

In [18]:
schedule_df.loc[0]

DATE                       2020-12-22
VISITOR         GOLDEN STATE WARRIORS
VISITOR_PTS                        99
HOME                    BROOKLYN NETS
HOME_PTS                          125
VISITOR_ABBR                      GSW
HOME_ABBR                         BRK
MARGIN                             26
Name: 0, dtype: object

Copy and paste
```python
schedule_df.loc[0].iloc[0]
#DATE
schedule_df.loc[0].iloc[5]
#visitor
schedule_df.loc[0].iloc[6]
#home
```

In [19]:
df_visitor.head(1)

,STARTERS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
0,Andrew Wiggins,31:14,4,16,.250,2,6,.333,3,4,.750,0,2,2,1,0,1,4,4,13,-28

In [20]:
df_home.head(1)

,STARTERS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
0,Kyrie Irving,25:18,10,16,.625,4,7,.571,2,2,1.000,1,3,4,4,0,0,1,3,26,+32

Returned df_visitor, df_home

In [21]:
box_score_columns

['DATE',
 'HOME_ABBR',
 'VISITOR_ABBR',
 'PTS_home',
 'PTS_away',
 'margin',
 'FG_PCT_home',
 'FT_PCT_home',
 'FG3_PCT_home',
 'AST_home',
 'REB_home',
 'FG_PCT_away',
 'FT_PCT_away',
 'FG3_PCT_away',
 'AST_away',
 'REB_away']

In [66]:
#take a peek
df_home.loc[df_home['STARTERS'] == 'Team Totals']

,STARTERS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
16,Team Totals,240,42,92,.457,15,35,.429,26,32,.813,13,44,57,24,11,7,20,22,125,NaN

In [89]:
df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,4]
#FG_PCT
df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,10]
#FT_PCT
df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,7]
#FT_PCT
df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,14]
#FT_PCT
df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,13]
#REBOUNDS

'.457'

In [ ]:
df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,4]
#FG_PCT
df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,10]
#FT_PCT
df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,7]
#FT_PCT
df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,14]
#FT_PCT
df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,13]
#REBOUNDS

In [93]:
df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,13]
#FT_PCT
#take a peek

'57'

In [85]:
schedule_df.loc[0]

DATE                       2020-12-22
VISITOR         GOLDEN STATE WARRIORS
VISITOR_PTS                        99
HOME                    BROOKLYN NETS
HOME_PTS                          125
VISITOR_ABBR                      GSW
HOME_ABBR                         BRK
MARGIN                             26
Name: 0, dtype: object

In [87]:
schedule_df.loc[0][2]

99.0

In [94]:
empty_ = []
empty_.append(schedule_df.loc[0].iloc[0])
#DATE
empty_.append(schedule_df.loc[0].iloc[6])
#home abbbr
empty_.append(schedule_df.loc[0].iloc[5])
#visitor abbr
empty_.append(schedule_df.loc[0].iloc[4])
#home points
empty_.append(schedule_df.loc[0].iloc[2])
#away points
empty_.append(schedule_df.loc[0].iloc[7])
#margin
empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS
empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS

In [96]:
length_of_df = len(box_score_df)
box_score_df.loc[length_of_df] = empty_

In [97]:
box_score_df

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,margin,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,2020-12-22,BRK,GSW,125.0,99.0,26,.457,.813,.429,24,57,.374,.652,.303,26,47

Tutorial - Piecing the data together
```python

home_away_df= pd.DataFrame(columns=away_df.columns)
empty_ = []
empty_.append(home_df.iloc[0,0])
empty_.append(away_df.iloc[0,1])
#like so 
#create an empty boxscore_df
length_of_df = len(home_away_df)
home_away_df.loc[length_of_df] = empty_
```

In [101]:
url = "https://www.basketball-reference.com/boxscores/202012260DET.html"
html = urlopen(url)
soup = BeautifulSoup(html)

Tutorial
```python
>>> soup.find("div", {"id": "articlebody"})
```

In [104]:
url = "https://www.basketball-reference.com/boxscores/202012260CHO.html"
html = urlopen(url)
soup = BeautifulSoup(html)

### when you search out the tables you can find which ones you need
```python
table_test = soup.find('table', {"id": "box-OKC-game-basic"})
```

In [102]:
table2 = soup.find('table', {"id": "box-DET-game-basic"})

In [92]:
df2 = pd.read_html(str(table2))

In [93]:
df2 = df2[0]

In [94]:
df2.columns

MultiIndex([(   'Unnamed: 0_level_0', 'Starters'),
            ('Basic Box Score Stats',       'MP'),
            ('Basic Box Score Stats',       'FG'),
            ('Basic Box Score Stats',      'FGA'),
            ('Basic Box Score Stats',      'FG%'),
            ('Basic Box Score Stats',       '3P'),
            ('Basic Box Score Stats',      '3PA'),
            ('Basic Box Score Stats',      '3P%'),
            ('Basic Box Score Stats',       'FT'),
            ('Basic Box Score Stats',      'FTA'),
            ('Basic Box Score Stats',      'FT%'),
            ('Basic Box Score Stats',      'ORB'),
            ('Basic Box Score Stats',      'DRB'),
            ('Basic Box Score Stats',      'TRB'),
            ('Basic Box Score Stats',      'AST'),
            ('Basic Box Score Stats',      'STL'),
            ('Basic Box Score Stats',      'BLK'),
            ('Basic Box Score Stats',      'TOV'),
            ('Basic Box Score Stats',       'PF'),
            ('Basic Box Score Stats',      'PTS'),
            ('Basic Box Score Stats',      '+/-')],
           )

In [95]:
new_columns = new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']

In [96]:
import numpy as np
np_array = np.arange(len(df2.columns))
list_ = np_array.tolist()

In [97]:
df2.columns = df2.columns.droplevel(0)

In [98]:
#renaming columns
for j in range(len(df2.columns)):
    old = df2.columns[j]
    new = new_columns[j]
    df2 = df2.rename(columns = {old:new})

In [99]:
df2

,STARTERS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
0,Blake Griffin,44:20,9,21,.429,8,16,.500,0,0,...,0,6,6,4,3,0,3,1,26,-16
1,Jerami Grant,42:31,9,14,.643,4,8,.500,6,8,...,1,9,10,2,0,3,1,4,28,+2
2,Delon Wright,42:12,5,9,.556,2,3,.667,7,9,...,3,3,6,4,0,1,1,0,19,-23
3,Mason Plumlee,32:47,3,6,.500,0,1,.000,0,0,...,2,7,9,5,3,0,3,6,6,-2
4,Killian Hayes,19:30,1,7,.143,0,3,.000,1,2,...,0,3,3,2,0,0,2,2,3,-5
5,Reserves,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
6,Derrick Rose,33:07,4,15,.267,1,2,.500,4,6,...,1,3,4,4,0,0,6,1,13,-3
7,Sviatoslav Mykhailiuk,23:34,4,9,.444,1,6,.167,3,3,...,0,3,3,2,2,0,3,2,12,+3
8,Josh Jackson,18:42,2,6,.333,0,3,.000,2,2,...,0,8,8,1,1,1,3,0,6,+9
9,Jahlil Okafor,18:27,3,4,.750,0,0,NaN,0,0,...,1,3,4,0,0,0,0,3,6,+9
10,Sekou Doumbouya,8:49,0,5,.000,0,1,.000,0,0,...,1,1,2,0,0,0,0,0,0,-18
11,Saddiq Bey,6:01,0,2,.000,0,2,.000,0,2,...,1,1,2,0,0,0,0,1,0,-1
12,Rodney McGruder,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
13,Wayne Ellington,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
14,Deividas Sirvydis,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
15,Isaiah Stewart,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
16,Team Totals,290,40,98,.408,16,45,.356,23,32,...,10,47,57,24,9,5,22,20,119,NaN

In [60]:
table = soup.find('table')

In [61]:
df = pd.read_html(str(table))

In [62]:
df = df[0]

In [65]:
df.columns

MultiIndex([(   'Unnamed: 0_level_0', 'Starters'),
            ('Basic Box Score Stats',       'MP'),
            ('Basic Box Score Stats',       'FG'),
            ('Basic Box Score Stats',      'FGA'),
            ('Basic Box Score Stats',      'FG%'),
            ('Basic Box Score Stats',       '3P'),
            ('Basic Box Score Stats',      '3PA'),
            ('Basic Box Score Stats',      '3P%'),
            ('Basic Box Score Stats',       'FT'),
            ('Basic Box Score Stats',      'FTA'),
            ('Basic Box Score Stats',      'FT%'),
            ('Basic Box Score Stats',      'ORB'),
            ('Basic Box Score Stats',      'DRB'),
            ('Basic Box Score Stats',      'TRB'),
            ('Basic Box Score Stats',      'AST'),
            ('Basic Box Score Stats',      'STL'),
            ('Basic Box Score Stats',      'BLK'),
            ('Basic Box Score Stats',      'TOV'),
            ('Basic Box Score Stats',       'PF'),
            ('Basic Box Score Stats',      'PTS'),
            ('Basic Box Score Stats',      '+/-')],
           )

In [66]:
df.columns = df.columns.droplevel(0)

In [67]:
df

,Starters,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
0,Collin Sexton,45:14,15,23,.652,2,3,.667,0,1,...,0,2,2,3,3,0,4,5,32,+9
1,Darius Garland,43:59,9,14,.643,3,3,1.000,0,0,...,2,3,5,12,2,1,2,3,21,+19
2,Andre Drummond,43:40,7,21,.333,0,2,.000,9,14,...,2,14,16,5,4,3,4,2,23,+10
3,Isaac Okoro,41:39,0,4,.000,0,3,.000,0,0,...,0,3,3,0,1,0,2,4,0,+16
4,Kevin Love,37:33,4,12,.333,3,8,.375,4,5,...,1,8,9,3,0,0,3,1,15,+14
5,Reserves,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
6,Cedi Osman,25:56,7,12,.583,4,7,.571,4,6,...,0,4,4,0,1,0,0,1,22,-12
7,Larry Nance,24:30,0,3,.000,0,2,.000,0,0,...,2,5,7,2,2,0,1,1,0,-2
8,JaVale McGee,14:20,4,7,.571,1,1,1.000,2,4,...,0,2,2,0,0,0,2,6,11,-1
9,Dante Exum,13:09,2,3,.667,0,1,.000,0,0,...,0,3,3,4,0,0,0,1,4,-8
10,Thon Maker,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
11,Dean Wade,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
12,Damyean Dotson,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
13,Marques Bolden,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
14,Lamar Stevens,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
15,Team Totals,290,48,99,.485,13,30,.433,19,30,...,7,44,51,29,13,4,18,24,128,NaN

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 21 columns):
(Unnamed: 0_level_0, Starters)    16 non-null object
(Basic Box Score Stats, MP)       16 non-null object
(Basic Box Score Stats, FG)       16 non-null object
(Basic Box Score Stats, FGA)      16 non-null object
(Basic Box Score Stats, FG%)      16 non-null object
(Basic Box Score Stats, 3P)       16 non-null object
(Basic Box Score Stats, 3PA)      16 non-null object
(Basic Box Score Stats, 3P%)      16 non-null object
(Basic Box Score Stats, FT)       16 non-null object
(Basic Box Score Stats, FTA)      16 non-null object
(Basic Box Score Stats, FT%)      12 non-null object
(Basic Box Score Stats, ORB)      16 non-null object
(Basic Box Score Stats, DRB)      16 non-null object
(Basic Box Score Stats, TRB)      16 non-null object
(Basic Box Score Stats, AST)      16 non-null object
(Basic Box Score Stats, STL)      16 non-null object
(Basic Box Score Stats, BLK)      16 non-null object
(Basic Box Score Stats, TOV)      16 non-null object
(Basic Box Score Stats, PF)       16 non-null object
(Basic Box Score Stats, PTS)      16 non-null object
(Basic Box Score Stats, +/-)      15 non-null object
dtypes: object(21)
memory usage: 2.8+ KB

In [74]:
new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']

In [75]:
#renaming columns
for j in range(len(df.columns)):
    old = df.columns[j]
    new = new_columns[j]
    df = df.rename(columns = {old:new})

In [76]:
df

,STARTERS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
0,Collin Sexton,45:14,15,23,.652,2,3,.667,0,1,...,0,2,2,3,3,0,4,5,32,+9
1,Darius Garland,43:59,9,14,.643,3,3,1.000,0,0,...,2,3,5,12,2,1,2,3,21,+19
2,Andre Drummond,43:40,7,21,.333,0,2,.000,9,14,...,2,14,16,5,4,3,4,2,23,+10
3,Isaac Okoro,41:39,0,4,.000,0,3,.000,0,0,...,0,3,3,0,1,0,2,4,0,+16
4,Kevin Love,37:33,4,12,.333,3,8,.375,4,5,...,1,8,9,3,0,0,3,1,15,+14
5,Reserves,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
6,Cedi Osman,25:56,7,12,.583,4,7,.571,4,6,...,0,4,4,0,1,0,0,1,22,-12
7,Larry Nance,24:30,0,3,.000,0,2,.000,0,0,...,2,5,7,2,2,0,1,1,0,-2
8,JaVale McGee,14:20,4,7,.571,1,1,1.000,2,4,...,0,2,2,0,0,0,2,6,11,-1
9,Dante Exum,13:09,2,3,.667,0,1,.000,0,0,...,0,3,3,4,0,0,0,1,4,-8
10,Thon Maker,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
11,Dean Wade,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
12,Damyean Dotson,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
13,Marques Bolden,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
14,Lamar Stevens,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play
15,Team Totals,290,48,99,.485,13,30,.433,19,30,...,7,44,51,29,13,4,18,24,128,NaN

In [109]:
df.columns

Index(['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       '+/-'],
      dtype='object')

In [77]:
df.loc[df['STARTERS'] == 'Team Totals']

,STARTERS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-
15,Team Totals,290,48,99,.485,13,30,.433,19,30,...,7,44,51,29,13,4,18,24,128,NaN

What I am looking for

```python 

[['PTS_home', 'PTS_away', 'margin', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away', 'REB_away']]

```

Trial Code

In [84]:
table2 = soup.find('table')

In [52]:
import numpy as np
np_array = np.arange(len(df.columns))
list_ = np_array.tolist()

Tutorial 
```python
column_indices = [1,4,5,6]
new_names = ['a','b','c','d']
old_names = df.columns[column_indices]
df.rename(columns=dict(zip(old_names, new_names)), inplace=True)
```

In [55]:
old_names = df.columns[list_]
df = df.rename(columns=dict(zip(old_names, new_names)), inplace=True)

In [58]:
df

In [37]:
str(table)[1]

't'

In [5]:
# NBA season we will be analyzing
year = 2020
# URL page we will scraping (see image above)
url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html".format(year)
# this is the HTML from the given URL
html = urlopen(url)
soup = BeautifulSoup(html)

In [6]:
# use findALL() to get the column headers
soup.findAll('tr', limit=2)
# use getText()to extract the text we need into a list
headers = [th.getText() for th in soup.findAll('tr', limit=2)[0].findAll('th')]
# exclude the first column as we will not need the ranking order from Basketball Reference for the analysis
headers = headers[1:]
headers

['Player',
 'Pos',
 'Age',
 'Tm',
 'G',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'eFG%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS']

In [15]:
type(rows)

list

In [11]:
# avoid the first header row
rows = soup.findAll('tr')[1:]

Tutorial
```python
# avoid the first header row
rows = soup.findAll('tr')[1:]
player_stats = [[td.getText() for td in rows[i].findAll('td')]
            for i in range(len(rows))]
```

In [18]:
row1 = rows[0:1]

In [19]:
row1

[<tr class="full_table"><th class="right" csk="1" data-stat="ranker" scope="row">1</th><td class="left" csk="Adams,Steven" data-append-csv="adamsst01" data-stat="player"><a href="/players/a/adamsst01.html">Steven Adams</a></td><td class="center" data-stat="pos">C</td><td class="right" data-stat="age">26</td><td class="left" data-stat="team_id"><a href="/teams/OKC/2020.html">OKC</a></td><td class="right" data-stat="g">63</td><td class="right" data-stat="gs">63</td><td class="right" data-stat="mp_per_g">26.7</td><td class="right" data-stat="fg_per_g">4.5</td><td class="right" data-stat="fga_per_g">7.6</td><td class="right" data-stat="fg_pct">.592</td><td class="right iz" data-stat="fg3_per_g">0.0</td><td class="right iz" data-stat="fg3a_per_g">0.0</td><td class="right non_qual" data-stat="fg3_pct">.333</td><td class="right" data-stat="fg2_per_g">4.5</td><td class="right" data-stat="fg2a_per_g">7.5</td><td class="right" data-stat="fg2_pct">.594</td><td class="right" data-stat="efg_pct">.593</td><td class="right" data-stat="ft_per_g">1.9</td><td class="right" data-stat="fta_per_g">3.2</td><td class="right" data-stat="ft_pct">.582</td><td class="right" data-stat="orb_per_g">3.3</td><td class="right" data-stat="drb_per_g">6.0</td><td class="right" data-stat="trb_per_g">9.3</td><td class="right" data-stat="ast_per_g">2.3</td><td class="right" data-stat="stl_per_g">0.8</td><td class="right" data-stat="blk_per_g">1.1</td><td class="right" data-stat="tov_per_g">1.5</td><td class="right" data-stat="pf_per_g">1.9</td><td class="right" data-stat="pts_per_g">10.9</td></tr>]

In [7]:
# avoid the first header row
rows = soup.findAll('tr')[1:]
player_stats = [[td.getText() for td in rows[i].findAll('td')]
            for i in range(len(rows))]

In [ ]:
for i in range(len(rows)):

In [21]:
stats = pd.DataFrame(player_stats, columns = headers)
stats.head(10)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Steven Adams,C,26,OKC,63,63,26.7,4.5,7.6,.592,...,.582,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
1,Bam Adebayo,PF,22,MIA,72,72,33.6,6.1,11.0,.557,...,.691,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9
2,LaMarcus Aldridge,C,34,SAS,53,53,33.1,7.4,15.0,.493,...,.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
3,Kyle Alexander,C,23,MIA,2,0,6.5,0.5,1.0,.500,...,,1.0,0.5,1.5,0.0,0.0,0.0,0.5,0.5,1.0
4,Nickeil Alexander-Walker,SG,21,NOP,47,1,12.6,2.1,5.7,.368,...,.676,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7
5,Grayson Allen,SG,24,MEM,38,0,18.9,3.1,6.6,.466,...,.867,0.2,2.0,2.2,1.4,0.3,0.1,0.9,1.4,8.7
6,Jarrett Allen,C,21,BRK,70,64,26.5,4.3,6.6,.649,...,.633,3.1,6.5,9.6,1.6,0.6,1.3,1.1,2.3,11.1
7,Kadeem Allen,PG,27,NYK,10,0,11.7,1.9,4.4,.432,...,.636,0.2,0.7,0.9,2.1,0.5,0.2,0.8,0.7,5.0
8,Al-Farouq Aminu,PF,29,ORL,18,2,21.1,1.4,4.8,.291,...,.655,1.3,3.5,4.8,1.2,1.0,0.4,0.9,1.5,4.3
9,Justin Anderson,SG,26,BRK,10,1,10.7,1.0,3.8,.263,...,.500,0.1,2.0,2.1,0.8,0.0,0.6,0.4,1.3,2.8

In [23]:
pd.set_option('display.max_rows', None)

In [27]:
stats = stats.dropna(how='any')

In [28]:
stats.head(50)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Steven Adams,C,26,OKC,63,63,26.7,4.5,7.6,.592,...,.582,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
1,Bam Adebayo,PF,22,MIA,72,72,33.6,6.1,11.0,.557,...,.691,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9
2,LaMarcus Aldridge,C,34,SAS,53,53,33.1,7.4,15.0,.493,...,.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
3,Kyle Alexander,C,23,MIA,2,0,6.5,0.5,1.0,.500,...,,1.0,0.5,1.5,0.0,0.0,0.0,0.5,0.5,1.0
4,Nickeil Alexander-Walker,SG,21,NOP,47,1,12.6,2.1,5.7,.368,...,.676,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7
5,Grayson Allen,SG,24,MEM,38,0,18.9,3.1,6.6,.466,...,.867,0.2,2.0,2.2,1.4,0.3,0.1,0.9,1.4,8.7
6,Jarrett Allen,C,21,BRK,70,64,26.5,4.3,6.6,.649,...,.633,3.1,6.5,9.6,1.6,0.6,1.3,1.1,2.3,11.1
7,Kadeem Allen,PG,27,NYK,10,0,11.7,1.9,4.4,.432,...,.636,0.2,0.7,0.9,2.1,0.5,0.2,0.8,0.7,5.0
8,Al-Farouq Aminu,PF,29,ORL,18,2,21.1,1.4,4.8,.291,...,.655,1.3,3.5,4.8,1.2,1.0,0.4,0.9,1.5,4.3
9,Justin Anderson,SG,26,BRK,10,1,10.7,1.0,3.8,.263,...,.500,0.1,2.0,2.1,0.8,0.0,0.6,0.4,1.3,2.8
10,Kyle Anderson,SF,26,MEM,67,28,19.9,2.3,4.9,.474,...,.667,0.9,3.4,4.3,2.4,0.8,0.6,1.0,1.7,5.8
11,Ryan Anderson,C,31,HOU,2,0,7.0,1.0,3.5,.286,...,,0.0,3.5,3.5,1.0,0.5,0.0,0.5,0.5,2.5
12,Giannis Antetokounmpo,PF,25,MIL,63,63,30.4,10.9,19.7,.553,...,.633,2.2,11.4,13.6,5.6,1.0,1.0,3.7,3.1,29.5
13,Kostas Antetokounmpo,PF,22,LAL,5,0,4.0,0.6,0.6,1.000,...,.500,0.4,0.2,0.6,0.4,0.0,0.0,0.2,0.4,1.4
14,Thanasis Antetokounmpo,SF,27,MIL,20,2,6.5,1.2,2.4,.500,...,.412,0.6,0.6,1.2,0.8,0.4,0.1,0.6,0.9,2.8
15,Carmelo Anthony,PF,35,POR,58,58,32.8,5.8,13.5,.430,...,.845,1.2,5.1,6.3,1.5,0.8,0.5,1.7,2.9,15.4
16,OG Anunoby,SF,22,TOR,69,68,29.9,4.1,8.2,.505,...,.706,1.2,4.1,5.3,1.6,1.4,0.7,1.1,2.4,10.6
17,Ryan Arcidiacono,PG,25,CHI,58,4,16.0,1.6,3.8,.409,...,.711,0.3,1.6,1.9,1.7,0.5,0.1,0.6,1.7,4.5
18,Trevor Ariza,SF,34,TOT,53,21,28.2,2.7,6.1,.438,...,.838,0.6,4.0,4.6,1.7,1.3,0.3,1.1,2.1,8.0
19,Trevor Ariza,SF,34,SAC,32,0,24.7,2.0,5.2,.388,...,.778,0.7,3.9,4.6,1.6,1.1,0.2,0.9,2.0,6.0
20,Trevor Ariza,SF,34,POR,21,21,33.4,3.7,7.6,.491,...,.872,0.6,4.1,4.8,2.0,1.6,0.4,1.3,2.3,11.0
21,D.J. Augustin,PG,32,ORL,57,13,24.9,3.2,8.1,.399,...,.890,0.4,1.8,2.1,4.6,0.6,0.0,1.5,1.3,10.5
23,Deandre Ayton,C,21,PHO,38,32,32.5,8.2,14.9,.546,...,.753,3.9,7.6,11.5,1.9,0.7,1.5,2.1,3.1,18.2
24,Dwayne Bacon,SG,24,CHO,39,11,17.6,2.2,6.3,.348,...,.660,0.4,2.2,2.6,1.3,0.6,0.1,0.9,1.3,5.7
25,Marvin Bagley III,C,20,SAC,13,6,25.7,6.0,12.8,.467,...,.806,2.2,5.2,7.5,0.8,0.5,0.9,1.4,3.3,14.2
26,Lonzo Ball,PG,22,NOP,63,54,32.1,4.4,10.9,.403,...,.566,1.1,5.0,6.1,7.0,1.4,0.6,3.1,2.0,11.8
27,Mo Bamba,C,21,ORL,62,0,14.2,2.1,4.6,.462,...,.674,1.6,3.3,4.9,0.7,0.4,1.4,0.7,1.9,5.4
28,J.J. Barea,PG,35,DAL,29,6,15.5,2.9,7.1,.411,...,.909,0.3,1.5,1.8,3.9,0.2,0.1,1.3,0.9,7.7
29,Harrison Barnes,PF,27,SAC,72,72,34.5,5.1,11.0,.460,...,.801,1.1,3.9,4.9,2.2,0.6,0.2,1.2,1.3,14.5
30,RJ Barrett,SG,19,NYK,56,55,30.4,5.2,13.0,.402,...,.614,0.9,4.1,5.0,2.6,1.0,0.3,2.2,2.2,14.3
31,Will Barton,SF,29,DEN,58,58,33.0,5.7,12.7,.450,...,.767,1.3,5.0,6.3,3.7,1.1,0.5,1.5,2.1,15.1
32,Keita Bates-Diop,PF-SF,24,TOT,44,0,16.9,2.3,5.3,.427,...,.720,0.6,2.3,2.9,0.7,0.4,0.5,0.4,1.0,6.5
33,Keita Bates-Diop,PF,24,MIN,37,0,17.5,2.4,5.6,.422,...,.708,0.6,2.4,3.0,0.8,0.5,0.5,0.4,1.0,6.8
34,Keita Bates-Diop,SF,24,DEN,7,0,14.0,1.9,4.0,.464,...,.800,0.6,1.9,2.4,0.0,0.3,0.6,0.4,1.0,5.3
35,Nicolas Batum,SF,31,CHO,22,3,23.0,1.3,3.7,.346,...,.900,1.1,3.4,4.5,3.0,0.8,0.4,1.0,1.9,3.6
36,Aron Baynes,C,33,PHO,42,28,22.2,4.4,9.1,.480,...,.747,1.7,4.0,5.6,1.6,0.2,0.5,1.2,3.4,11.5
37,Kent Bazemore,SF,30,TOT,68,21,24.8,2.9,7.9,.375,...,.769,0.4,3.9,4.3,1.4,1.1,0.6,1.3,2.9,8.8
38,Kent Bazemore,SF,30,POR,43,21,25.8,2.6,7.6,.347,...,.806,0.3,3.7,4.0,1.4,1.0,0.7,1.4,2.8,7.9
39,Kent Bazemore,SF,30,SAC,25,0,23.1,3.5,8.3,.418,...,.733,0.6,4.3,4.9,1.3,1.2,0.4,1.2,3.0,10.3
40,Darius Bazley,PF,19,OKC,61,9,18.5,2.0,5.2,.394,...,.694,0.5,3.5,4.0,0.7,0.4,0.7,0.7,0.9,5.6
41,Bradley Beal,SG,26,WAS,57,57,36.0,10.4,22.9,.455,...,.842,0.9,3.3,4.2,6.1,1.2,0.4,3.4,2.2,30.5
42,Malik Beasley,SG,23,TOT,55,14,22.0,4.1,9.7,.425,...,.818,0.3,2.4,2.7,1.4,0.7,0.1,1.0,1.4,11.2
43,Malik Beasley,SG,23,DEN,41,0,18.2,2.9,7.3,.389,...,.868,0.2,1.7,1.9,1.2,0.8,0.1,0.9,1.2,7.9
44,Malik Beasley,SG,23,MIN,14,14,33.1,7.9,16.6,.472,...,.750,0.6,4.4,5.1,1.9,0.6,0.1,1.5,1.9,20.7
45,Marco Belinelli,SG,33,SAS,57,0,15.5,2.2,5.5,.392,...,.828,0.1,1.6,1.7,1.2,0.2,0.0,0.3,0.8,6.3
46,Jordan Bell,C,25,TOT,29,0,8.8,1.2,2.3,.522,...,.613,1.0,1.8,2.8,0.6,0.1,0.3,0.7,0.7,3.2
47,Jordan Bell,C,25,MIN,27,0,8.7,1.2,2.2,.533,...,.586,1.0,1.9,2.9,0.5,0.1,0.4,0.7,0.6,3.1
48,Jordan Bell,C,25,MEM,2,0,10.5,1.5,3.5,.429,...,1.000,1.0,0.5,1.5,1.0,0.5,0.0,1.5,1.0,5.0
49,DeAndre' Bembry,SG,25,ATL,43,4,21.3,2.4,5.3,.456,...,.542,0.8,2.7,3.5,1.9,1.3,0.4,1.4,2.0,5.8
50,Dragan Bender,PF-C,22,TOT,16,3,17.9,2.6,5.8,.446,...,.714,1.0,3.6,4.6,1.8,0.3,0.6,1.3,2.6,6.7

In [9]:
len(stats)

677

In [10]:
stats.to_csv('players_example1.csv', index=False)