In [22]:
pd.set_option("display.max_rows", 10)

In [165]:
import pandas as pd
df_2 = pd.read_csv('abbr_games.csv')

In [166]:
mask = df_2['GAME_DATE_EST'] < '2020-08-16'
df_2 = df_2.loc[mask]

In [167]:
mask_2 = df_2['GAME_DATE_EST'] > '2019-10-03'
df_2 = df_2.loc[mask_2]

In [168]:
df_2 = df_2.reset_index(drop=True)

In [169]:
df_2

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,VISITOR_ABBR,HOME_ABBR,MARGIN
0,2020-08-15,51900111,Final,1610612757,1610612763,2019,1610612757,126.0,0.452,0.854,...,122.0,0.489,0.818,0.560,30.0,49.0,1,MEM,POR,4.0
1,2020-08-14,21901318,Final,1610612761,1610612743,2019,1610612761,117.0,0.500,0.643,...,109.0,0.414,0.913,0.421,27.0,41.0,1,DEN,TOR,8.0
2,2020-08-14,21901316,Final,1610612754,1610612748,2019,1610612754,109.0,0.483,0.727,...,92.0,0.356,0.741,0.263,14.0,48.0,1,MIA,IND,17.0
3,2020-08-14,21901317,Final,1610612746,1610612760,2019,1610612746,107.0,0.400,0.692,...,103.0,0.358,0.591,0.318,18.0,48.0,1,OKC,LAC,4.0
4,2020-08-14,21901315,Final,1610612745,1610612755,2019,1610612745,96.0,0.438,0.875,...,134.0,0.563,0.818,0.474,31.0,51.0,0,PHI,HOU,-38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153,2019-10-05,11900005,Final,1610612754,1610612758,2019,1610612754,130.0,0.521,0.944,...,106.0,0.378,0.780,0.353,24.0,35.0,1,SAC,IND,24.0
1154,2019-10-05,11900006,Final,1610612744,1610612747,2019,1610612744,101.0,0.393,0.769,...,123.0,0.475,0.633,0.303,32.0,58.0,0,LAL,GSW,-22.0
1155,2019-10-05,11900007,Final,1610612759,1610612753,2019,1610612759,89.0,0.388,0.750,...,125.0,0.526,0.714,0.361,29.0,47.0,0,ORL,SAS,-36.0
1156,2019-10-04,11900002,Final,1610612746,1610612745,2019,1610612746,96.0,0.384,0.600,...,109.0,0.375,0.800,0.229,21.0,52.0,0,HOU,LAC,-13.0
1157,2019-10-04,11900003,Final,1610612758,1610612754,2019,1610612758,131.0,0.494,0.778,...,132.0,0.516,0.788,0.370,26.0,47.0,0,IND,SAC,-1.0

In [170]:
df_2.rename(columns={"GAME_DATE_EST": "DATE"}, inplace=True)

In [171]:
df_2 = df_2[['DATE','PTS_home', 'FG_PCT_home',
       'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home',
       'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away',
       'REB_away', 'HOME_TEAM_WINS', 'VISITOR_ABBR', 'HOME_ABBR', 'MARGIN']]

In [172]:
df_2['DATE'] = pd.to_datetime(df_2['DATE'])

<ipython-input-172-d836e6beff0f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['DATE'] = pd.to_datetime(df_2['DATE'])

In [173]:
df_2 = df_2.sort_values(by=['DATE'])

In [174]:
#creating ID
end_a = len(df_2) + 1
a_ = list(range(1, end_a))
df_2['ID'] = a_

In [175]:
df_2.columns

Index(['DATE', 'PTS_home', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home',
       'AST_home', 'REB_home', 'PTS_away', 'FG_PCT_away', 'FT_PCT_away',
       'FG3_PCT_away', 'AST_away', 'REB_away', 'HOME_TEAM_WINS',
       'VISITOR_ABBR', 'HOME_ABBR', 'MARGIN', 'ID'],
      dtype='object')

In [176]:
df_2 = df_2[['ID','DATE', 'PTS_home', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home',
       'AST_home', 'REB_home', 'PTS_away', 'FG_PCT_away', 'FT_PCT_away',
       'FG3_PCT_away', 'AST_away', 'REB_away', 'HOME_TEAM_WINS',
       'VISITOR_ABBR', 'HOME_ABBR', 'MARGIN']]

In [177]:
df_2['DATE'] = pd.to_datetime(df_2['DATE'])  

#necessary to have this here.

In [178]:
df_2 = df_2.reset_index(drop=True)

len(df_into_season) + len(df_second)

TUTORIAL

```python
#already rean so read this
#run this to include abbreviations
for ind in sample_df.index:
    visitor = sample_df['VISITOR_TEAM_ID'][ind]
    home = sample_df['HOME_TEAM_ID'][ind]
    sample_df['VISITOR_ABBR'][ind] = team_to_abbreviation[visitor]
    sample_df['HOME_ABBR'][ind] = team_to_abbreviation[home]
```

In [35]:
Tutorial, how to make a normalized list for plotting:

```python

margin_list = calculated_df2['margin'].tolist()
max(margin_list)
11.594047619047627
norm = [float(i)/max(margin_list) for i in margin_list]
calculated_df2['normMargin'] = norm
```

In [47]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2516 entries, 0 to 2515
Data columns (total 18 columns):
ID                2516 non-null int64
DATE              2516 non-null datetime64[ns]
PTS_home          2516 non-null float64
FG_PCT_home       2516 non-null float64
FT_PCT_home       2516 non-null float64
FG3_PCT_home      2516 non-null float64
AST_home          2516 non-null float64
REB_home          2516 non-null float64
PTS_away          2516 non-null float64
FG_PCT_away       2516 non-null float64
FT_PCT_away       2516 non-null float64
FG3_PCT_away      2516 non-null float64
AST_away          2516 non-null float64
REB_away          2516 non-null float64
HOME_TEAM_WINS    2516 non-null int64
VISITOR_ABBR      2516 non-null object
HOME_ABBR         2516 non-null object
MARGIN            2516 non-null float64
dtypes: datetime64[ns](1), float64(13), int64(2), object(2)
memory usage: 353.9+ KB

In [179]:
df_into_season = df_2.copy()
df_into_season['DATE'] = pd.to_datetime(df_into_season['DATE'])

In [180]:
df_into_season

,ID,DATE,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,VISITOR_ABBR,HOME_ABBR,MARGIN
0,1,2019-10-04,131.0,0.494,0.778,0.417,30.0,30.0,132.0,0.516,0.788,0.370,26.0,47.0,0,IND,SAC,-1.0
1,2,2019-10-04,96.0,0.384,0.600,0.273,26.0,49.0,109.0,0.375,0.800,0.229,21.0,52.0,0,HOU,LAC,-13.0
2,3,2019-10-05,101.0,0.393,0.769,0.262,20.0,47.0,123.0,0.475,0.633,0.303,32.0,58.0,0,LAL,GSW,-22.0
3,4,2019-10-05,130.0,0.521,0.944,0.517,35.0,51.0,106.0,0.378,0.780,0.353,24.0,35.0,1,SAC,IND,24.0
4,5,2019-10-05,89.0,0.388,0.750,0.444,22.0,40.0,125.0,0.526,0.714,0.361,29.0,47.0,0,ORL,SAS,-36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153,1154,2020-08-14,96.0,0.438,0.875,0.250,25.0,27.0,134.0,0.563,0.818,0.474,31.0,51.0,0,PHI,HOU,-38.0
1154,1155,2020-08-14,107.0,0.400,0.692,0.324,23.0,61.0,103.0,0.358,0.591,0.318,18.0,48.0,1,OKC,LAC,4.0
1155,1156,2020-08-14,109.0,0.483,0.727,0.395,32.0,51.0,92.0,0.356,0.741,0.263,14.0,48.0,1,MIA,IND,17.0
1156,1157,2020-08-14,117.0,0.500,0.643,0.514,27.0,51.0,109.0,0.414,0.913,0.421,27.0,41.0,1,DEN,TOR,8.0
1157,1158,2020-08-15,126.0,0.452,0.854,0.375,20.0,39.0,122.0,0.489,0.818,0.560,30.0,49.0,1,MEM,POR,4.0

In [41]:
df_into_season.columns

Index(['ID', 'DATE', 'PTS_home', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home',
       'AST_home', 'REB_home', 'PTS_away', 'FG_PCT_away', 'FT_PCT_away',
       'FG3_PCT_away', 'AST_away', 'REB_away', 'HOME_TEAM_WINS',
       'VISITOR_ABBR', 'HOME_ABBR', 'MARGIN'],
      dtype='object')

In [181]:
empty_home_winning_percentage = []
empty_away_winning_percentage = []
home_team_wins = 0
home_team_loss = 0
away_team_wins = 0
away_team_loss = 0
for ind in df_into_season.head(100).index:
    print(ind)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

In [203]:
empty_home_winning_percentage = []
empty_away_winning_percentage = []
home_team_wins = 0
home_team_loss = 0
away_team_wins = 0
away_team_loss = 0
for ind in df_into_season.index:
    if ind > 77:
        home_team_wins = 0
        home_team_loss = 0
        away_team_wins = 0
        away_team_loss = 0
        date = df_into_season['DATE'][ind]
        home_team_abbr = df_into_season['HOME_ABBR'][ind]
        visitor_team_abbr = df_into_season['VISITOR_ABBR'][ind]
        home_team_wins = df_into_season['HOME_TEAM_WINS'][ind]
        mask = (df_into_season['DATE'] < date)
        new_ = df_into_season.loc[mask]
        home_df2 = new_.loc[new_['HOME_ABBR'] == home_team_abbr]
        home_as_visitor_df2 = new_.loc[new_['VISITOR_ABBR'] == home_team_abbr]
        visitor_df2= new_.loc[new_['VISITOR_ABBR'] == visitor_team_abbr]
        visitor_as_home_df2 = new_.loc[new_['HOME_ABBR'] == visitor_team_abbr]
        for ind in home_df2.index:
            home_team_wins_home_df2 = home_df2['HOME_TEAM_WINS'][ind]
            if home_team_wins_home_df2 == 1:
                home_team_wins = home_team_wins + 1
            else:
                home_team_loss = home_team_loss + 1
        for ind in home_as_visitor_df2.index:
            home_team_wins_visitor_df2 = home_as_visitor_df2['HOME_TEAM_WINS'][ind]
            if home_team_wins_visitor_df2 == 0:
                home_team_wins = home_team_wins + 1
            else:
                home_team_loss = home_team_loss + 1
    
        for ind in visitor_df2.index:
            home_team_wins_visitor_df2 = visitor_df2['HOME_TEAM_WINS'][ind]
#     print(visitor_df2['HOME_TEAM_WINS'][ind])
            if home_team_wins_visitor_df2 == 0:
                away_team_wins = away_team_wins + 1
            else:
                away_team_loss = away_team_loss + 1
        for ind in visitor_as_home_df2.index:
            home_team_wins_visitor_as_home_df2 = visitor_as_home_df2['HOME_TEAM_WINS'][ind]
            if home_team_wins_visitor_as_home_df2 == 1:
                away_team_wins = away_team_wins + 1
            else:
                away_team_loss = away_team_loss + 1            
        total_home_team_games = home_team_wins + home_team_loss
        total_away_team_games = away_team_wins + away_team_loss
        home_winning_percentage = home_team_wins / total_home_team_games
        away_winning_percentage = away_team_wins / total_away_team_games
        empty_home_winning_percentage.append(home_winning_percentage)
        empty_away_winning_percentage.append(away_winning_percentage)

In [199]:
len(df_into_season)

1158

In [206]:
len(empty_home_winning_percentage)

1158

In [205]:
import numpy as np
length_beg_arr = len(df_into_season) - len(empty_away_winning_percentage)
arr = np.arange(78)
arr[:] = 0.0 
arr = arr.tolist()
empty_away_winning_percentage = arr + empty_away_winning_percentage
empty_home_winning_percentage = arr + empty_home_winning_percentage

In [207]:
df_into_season['home_winning_percentage'] = empty_home_winning_percentage
df_into_season['visitor_winning_percentage'] = empty_away_winning_percentage

In [208]:
df_into_season

,ID,DATE,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,VISITOR_ABBR,HOME_ABBR,MARGIN,home_winning_percentage,visitor_winning_percentage
0,1,2019-10-04,131.0,0.494,0.778,0.417,30.0,30.0,132.0,0.516,0.788,0.370,26.0,47.0,0,IND,SAC,-1.0,0.000000,0.000000
1,2,2019-10-04,96.0,0.384,0.600,0.273,26.0,49.0,109.0,0.375,0.800,0.229,21.0,52.0,0,HOU,LAC,-13.0,0.000000,0.000000
2,3,2019-10-05,101.0,0.393,0.769,0.262,20.0,47.0,123.0,0.475,0.633,0.303,32.0,58.0,0,LAL,GSW,-22.0,0.000000,0.000000
3,4,2019-10-05,130.0,0.521,0.944,0.517,35.0,51.0,106.0,0.378,0.780,0.353,24.0,35.0,1,SAC,IND,24.0,0.000000,0.000000
4,5,2019-10-05,89.0,0.388,0.750,0.444,22.0,40.0,125.0,0.526,0.714,0.361,29.0,47.0,0,ORL,SAS,-36.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153,1154,2020-08-14,96.0,0.438,0.875,0.250,25.0,27.0,134.0,0.563,0.818,0.474,31.0,51.0,0,PHI,HOU,-38.0,0.620253,0.582278
1154,1155,2020-08-14,107.0,0.400,0.692,0.324,23.0,61.0,103.0,0.358,0.591,0.318,18.0,48.0,1,OKC,LAC,4.0,0.653846,0.623377
1155,1156,2020-08-14,109.0,0.483,0.727,0.395,32.0,51.0,92.0,0.356,0.741,0.263,14.0,48.0,1,MIA,IND,17.0,0.625000,0.612500
1156,1157,2020-08-14,117.0,0.500,0.643,0.514,27.0,51.0,109.0,0.414,0.913,0.421,27.0,41.0,1,DEN,TOR,8.0,0.721519,0.645570
1157,1158,2020-08-15,126.0,0.452,0.854,0.375,20.0,39.0,122.0,0.489,0.818,0.560,30.0,49.0,1,MEM,POR,4.0,0.451220,0.455696

In [209]:
# create dataframe with respective columns
# turn this into a dictionary to add to the rows that have 0.0 for winning_percentage
team_abbr = df_into_season['HOME_ABBR'].unique()
team_abbr = team_abbr.tolist()
team_abbr_df = pd.DataFrame(team_abbr)
team_abbr_df.rename(columns={0:'team_abbr'}, inplace=True)
team_abbr_df['winning_percentage'] = 0.0

In [210]:
team_abbr_df.columns

Index(['team_abbr', 'winning_percentage'], dtype='object')

In [211]:
team_winning_dict = dict(zip(team_abbr_df['team_abbr'], team_abbr_df['winning_percentage']))

In [166]:
df_into_season.head()

,ID,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,home_winning_percentage,visitor_winning_percentage
0,1,2021-01-02,IND,NYK,117.312500,98.625000,18.687500,0,0.467562,0.794125,0.334937,28.375000,43.562500,0.429125,0.733750,0.335375,23.000000,46.875000,0.0,0.0
1,2,2021-01-02,ORL,OKC,107.541667,106.416667,1.125000,0,0.430917,0.735750,0.313708,20.833333,45.458333,0.452417,0.727000,0.295167,24.166667,50.833333,0.0,0.0
2,3,2021-01-02,PHI,CHO,106.458333,112.500000,-6.041667,1,0.424500,0.810375,0.298500,21.708333,49.541667,0.483917,0.660292,0.385125,29.208333,42.500000,0.0,0.0
3,4,2021-01-02,ATL,CLE,127.312500,112.208333,15.104167,0,0.475938,0.864250,0.454625,28.625000,46.375000,0.469333,0.627708,0.462125,26.375000,46.750000,0.0,0.0
4,5,2021-01-02,NOP,TOR,99.125000,102.500000,-3.375000,1,0.396562,0.721500,0.232500,16.812500,53.562500,0.409875,0.779250,0.345875,25.750000,45.875000,0.0,0.0

In [212]:
for ind in df_into_season.index:
    abbr = df_into_season['HOME_ABBR'][ind]
    winning_percentage = df_into_season['home_winning_percentage'][ind]
    team_winning_dict[abbr] = winning_percentage

In [213]:
team_winning_dict['DEN'].item()

0.6538461538461539

In [214]:
team_winning_dict

{'SAC': 0.4230769230769231,
 'LAC': 0.6538461538461539,
 'GSW': 0.2463768115942029,
 'IND': 0.625,
 'SAS': 0.44871794871794873,
 'BOS': 0.6794871794871795,
 'CHI': 0.34285714285714286,
 'ATL': 0.29577464788732394,
 'WAS': 0.33766233766233766,
 'DET': 0.3382352941176471,
 'POR': 0.45121951219512196,
 'PHX': 0.475,
 'OKC': 0.6233766233766234,
 'MIA': 0.620253164556962,
 'TOR': 0.7215189873417721,
 'MIL': 0.7948717948717948,
 'CHA': 0.3382352941176471,
 'LAL': 0.7215189873417721,
 'HOU': 0.620253164556962,
 'ORL': 0.45121951219512196,
 'NOP': 0.4935064935064935,
 'NYK': 0.3088235294117647,
 'DAL': 0.5802469135802469,
 'BKN': 0.4935064935064935,
 'UTA': 0.5822784810126582,
 'MEM': 0.45569620253164556,
 'PHI': 0.5897435897435898,
 'CLE': 0.2835820895522388,
 'DEN': 0.6538461538461539,
 'MIN': 0.30303030303030304}

In [215]:
for ind in df_into_season.head().index:
    home_abbr = df_into_season['HOME_ABBR'][ind]
    away_abbr = df_into_season['VISITOR_ABBR'][ind]
    if df_into_season['home_winning_percentage'][ind] == 0:
        df_into_season['home_winning_percentage'][ind] = team_winning_dict[home_abbr].item()
        df_into_season['visitor_winning_percentage'][ind] = team_winning_dict[away_abbr].item()

<ipython-input-215-08629d62006c>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_into_season['home_winning_percentage'][ind] = team_winning_dict[home_abbr].item()
<ipython-input-215-08629d62006c>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_into_season['visitor_winning_percentage'][ind] = team_winning_dict[away_abbr].item()

In [216]:
df_into_season

,ID,DATE,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,VISITOR_ABBR,HOME_ABBR,MARGIN,home_winning_percentage,visitor_winning_percentage
0,1,2019-10-04,131.0,0.494,0.778,0.417,30.0,30.0,132.0,0.516,0.788,0.370,26.0,47.0,0,IND,SAC,-1.0,0.423077,0.625000
1,2,2019-10-04,96.0,0.384,0.600,0.273,26.0,49.0,109.0,0.375,0.800,0.229,21.0,52.0,0,HOU,LAC,-13.0,0.653846,0.620253
2,3,2019-10-05,101.0,0.393,0.769,0.262,20.0,47.0,123.0,0.475,0.633,0.303,32.0,58.0,0,LAL,GSW,-22.0,0.246377,0.721519
3,4,2019-10-05,130.0,0.521,0.944,0.517,35.0,51.0,106.0,0.378,0.780,0.353,24.0,35.0,1,SAC,IND,24.0,0.625000,0.423077
4,5,2019-10-05,89.0,0.388,0.750,0.444,22.0,40.0,125.0,0.526,0.714,0.361,29.0,47.0,0,ORL,SAS,-36.0,0.448718,0.451220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153,1154,2020-08-14,96.0,0.438,0.875,0.250,25.0,27.0,134.0,0.563,0.818,0.474,31.0,51.0,0,PHI,HOU,-38.0,0.620253,0.582278
1154,1155,2020-08-14,107.0,0.400,0.692,0.324,23.0,61.0,103.0,0.358,0.591,0.318,18.0,48.0,1,OKC,LAC,4.0,0.653846,0.623377
1155,1156,2020-08-14,109.0,0.483,0.727,0.395,32.0,51.0,92.0,0.356,0.741,0.263,14.0,48.0,1,MIA,IND,17.0,0.625000,0.612500
1156,1157,2020-08-14,117.0,0.500,0.643,0.514,27.0,51.0,109.0,0.414,0.913,0.421,27.0,41.0,1,DEN,TOR,8.0,0.721519,0.645570
1157,1158,2020-08-15,126.0,0.452,0.854,0.375,20.0,39.0,122.0,0.489,0.818,0.560,30.0,49.0,1,MEM,POR,4.0,0.451220,0.455696

In [218]:
#import dependencies
import sqlalchemy
# Import dependencies
import pandas as pd
from sqlalchemy import create_engine

# N.B. external config.py file should be formatted like:
# login = 'postgres:password' where password is set to whatever your database password is. Default username is 
# postgres, but change this if you use a different username.
import psycopg2
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
# postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'
#                 .format(username='postgres',
#                         password='postgres',
#                         ipaddress='localhost',
#                         port=5432,
#                         dbname='flask_deploy'))

postgres_str = 'postgres://umydthrhevlwbv:a166611fc4fda747769900bb51cfb8cbd633cebe3ec13fdfc2180772a9d3bc8d@ec2-18-204-101-137.compute-1.amazonaws.com:5432/d9ugm948kmolua'



# Create the connection
engine = create_engine(postgres_str)
cnx = engine.connect()

In [219]:
df_into_season.to_sql('training_model', engine, if_exists='replace', index=False)

In [221]:
with engine.connect() as con:
    con.execute('ALTER TABLE training_model ADD PRIMARY KEY ("ID");')