In [4]:
import pandas as pd
from urllib.request import urlopen
from bs4 import BeautifulSoup
import numpy as np
from time import sleep

In [9]:
df_ = pd.read_csv('partial_schedule_2021.csv')

In [5]:
df_2 = pd.read_csv('full_schedule_2021_V2.csv')

In [6]:
df_2

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR,HOME_TEAM_WINS,ID
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,26,BRK,GSW,1,1
1,2020-12-22,LOS ANGELES CLIPPERS,116.0,LOS ANGELES LAKERS,109.0,-7,LAL,LAC,0,2
2,2020-12-23,CHARLOTTE HORNETS,114.0,CLEVELAND CAVALIERS,121.0,7,CLE,CHO,1,3
3,2020-12-23,NEW YORK KNICKS,107.0,INDIANA PACERS,121.0,14,IND,NYK,1,4
4,2020-12-23,MIAMI HEAT,107.0,ORLANDO MAGIC,113.0,6,ORL,MIA,1,5
...,...,...,...,...,...,...,...,...,...,...
535,2021-03-04,MILWAUKEE BUCKS,0.0,MEMPHIS GRIZZLIES,0.0,0,MEM,MIL,0,536
536,2021-03-04,OKLAHOMA CITY THUNDER,0.0,SAN ANTONIO SPURS,0.0,0,SAS,OKC,0,537
537,2021-03-04,MIAMI HEAT,0.0,NEW ORLEANS PELICANS,0.0,0,NOP,MIA,0,538
538,2021-03-04,GOLDEN STATE WARRIORS,0.0,PHOENIX SUNS,0.0,0,PHO,GSW,0,539
539,2021-03-04,SACRAMENTO KINGS,0.0,PORTLAND TRAIL BLAZERS,0.0,0,POR,SAC,0,540

In [2]:
df_compare = pd.read_csv('data/schedule2021.csv')

In [8]:
schedule_df = df_2.copy()

In [9]:
box_score_columns = ['ID', 'DATE', 'HOME_ABBR', 'VISITOR_ABBR', 'PTS_home', 'PTS_away', 'MARGIN', 'HOME_TEAM_WINS', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away', 'REB_away']
box_score_df = pd.DataFrame(columns=box_score_columns)

In [44]:
schedule_df.head(1)

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR,HOME_TEAM_WINS,ID
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,26,BRK,GSW,1,1

In [34]:
#date_1 = schedule_df.loc[ind]['DATE'].replace(r"-","") + "0"
print(schedule_df.iloc[0,0].replace(r"-","")+ "0")

202012220

In [46]:
schedule_df = schedule_df.loc[schedule_df['VISITOR_PTS'] > 0]

In [54]:
schedule_df.tail(18)

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR,HOME_TEAM_WINS,ID
341,2021-02-07,MIAMI HEAT,109.0,NEW YORK KNICKS,103.0,-6,NYK,MIA,0,342
342,2021-02-07,BOSTON CELTICS,91.0,PHOENIX SUNS,100.0,9,PHO,BOS,1,343
343,2021-02-07,SACRAMENTO KINGS,113.0,LOS ANGELES CLIPPERS,110.0,-3,LAC,SAC,0,344
344,2021-02-08,HOUSTON ROCKETS,94.0,CHARLOTTE HORNETS,119.0,25,CHO,HOU,1,345
345,2021-02-08,WASHINGTON WIZARDS,105.0,CHICAGO BULLS,101.0,-4,CHI,WAS,0,346
346,2021-02-08,TORONTO RAPTORS,128.0,MEMPHIS GRIZZLIES,113.0,-15,MEM,TOR,0,347
347,2021-02-08,MINNESOTA TIMBERWOLVES,122.0,DALLAS MAVERICKS,127.0,5,DAL,MIN,1,348
348,2021-02-08,GOLDEN STATE WARRIORS,100.0,SAN ANTONIO SPURS,105.0,5,SAS,GSW,1,349
349,2021-02-08,CLEVELAND CAVALIERS,113.0,PHOENIX SUNS,119.0,6,PHO,CLE,1,350
350,2021-02-08,MILWAUKEE BUCKS,125.0,DENVER NUGGETS,112.0,-13,DEN,MIL,0,351
351,2021-02-08,OKLAHOMA CITY THUNDER,112.0,LOS ANGELES LAKERS,119.0,7,LAL,OKC,1,352
352,2021-02-09,BROOKLYN NETS,111.0,DETROIT PISTONS,122.0,11,DET,BRK,1,353
353,2021-02-09,NEW YORK KNICKS,96.0,MIAMI HEAT,98.0,2,MIA,NYK,1,354
354,2021-02-09,HOUSTON ROCKETS,101.0,NEW ORLEANS PELICANS,130.0,29,NOP,HOU,1,355
355,2021-02-09,GOLDEN STATE WARRIORS,114.0,SAN ANTONIO SPURS,91.0,-23,SAS,GSW,0,356
356,2021-02-09,ORLANDO MAGIC,97.0,PORTLAND TRAIL BLAZERS,106.0,9,POR,ORL,1,357
357,2021-02-09,PHILADELPHIA 76ERS,119.0,SACRAMENTO KINGS,111.0,-8,SAC,PHI,0,358
358,2021-02-09,BOSTON CELTICS,108.0,UTAH JAZZ,122.0,14,UTA,BOS,1,359

In [39]:
schedule_df.tail(10)

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR,HOME_TEAM_WINS,ID
530,2021-03-03,GOLDEN STATE WARRIORS,0.0,PORTLAND TRAIL BLAZERS,0.0,0,POR,GSW,0,531
531,2021-03-03,LOS ANGELES LAKERS,0.0,SACRAMENTO KINGS,0.0,0,SAC,LAL,0,532
532,2021-03-04,TORONTO RAPTORS,0.0,BOSTON CELTICS,0.0,0,BOS,TOR,0,533
533,2021-03-04,DENVER NUGGETS,0.0,INDIANA PACERS,0.0,0,IND,DEN,0,534
534,2021-03-04,LOS ANGELES CLIPPERS,0.0,WASHINGTON WIZARDS,0.0,0,WAS,LAC,0,535
535,2021-03-04,MILWAUKEE BUCKS,0.0,MEMPHIS GRIZZLIES,0.0,0,MEM,MIL,0,536
536,2021-03-04,OKLAHOMA CITY THUNDER,0.0,SAN ANTONIO SPURS,0.0,0,SAS,OKC,0,537
537,2021-03-04,MIAMI HEAT,0.0,NEW ORLEANS PELICANS,0.0,0,NOP,MIA,0,538
538,2021-03-04,GOLDEN STATE WARRIORS,0.0,PHOENIX SUNS,0.0,0,PHO,GSW,0,539
539,2021-03-04,SACRAMENTO KINGS,0.0,PORTLAND TRAIL BLAZERS,0.0,0,POR,SAC,0,540

In [81]:
schedule_df.tail(7)

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR,HOME_TEAM_WINS,ID
352,2021-02-09,BROOKLYN NETS,111.0,DETROIT PISTONS,122.0,11,DET,BRK,1,353
353,2021-02-09,NEW YORK KNICKS,96.0,MIAMI HEAT,98.0,2,MIA,NYK,1,354
354,2021-02-09,HOUSTON ROCKETS,101.0,NEW ORLEANS PELICANS,130.0,29,NOP,HOU,1,355
355,2021-02-09,GOLDEN STATE WARRIORS,114.0,SAN ANTONIO SPURS,91.0,-23,SAS,GSW,0,356
356,2021-02-09,ORLANDO MAGIC,97.0,PORTLAND TRAIL BLAZERS,106.0,9,POR,ORL,1,357
357,2021-02-09,PHILADELPHIA 76ERS,119.0,SACRAMENTO KINGS,111.0,-8,SAC,PHI,0,358
358,2021-02-09,BOSTON CELTICS,108.0,UTAH JAZZ,122.0,14,UTA,BOS,1,359

In [82]:
for ind in schedule_df.tail(7).index:
    if schedule_df['VISITOR_PTS'][ind] > 0:
        date_1 = schedule_df.loc[ind]['DATE'].replace(r"-","") + "0"
        home_1 = schedule_df.loc[ind]['HOME_ABBR']
        visitor_1 = schedule_df.loc[ind]['VISITOR_ABBR']
        basketball_url = "https://www.basketball-reference.com/boxscores/"
        url = basketball_url + date_1 + home_1 + ".html"
        html = urlopen(url)
        soup = BeautifulSoup(html)
        table_home_abbr = "box-{0}-game-basic".format(home_1)
        table_visitor_abbr = "box-{0}-game-basic".format(visitor_1)
        table_home = soup.find('table', {"id":table_home_abbr})
        df_home = pd.read_html(str(table_home))
        df_home = df_home[0]
        new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
        np_array = np.arange(len(df_home.columns))
        list_ = np_array.tolist()
        df_home.columns = df_home.columns.droplevel(0)
#renaming columns
        for j in range(len(df_home.columns)):
            old = df_home.columns[j]
            new = new_columns[j]
            df_home = df_home.rename(columns = {old:new})
        table_visitor = soup.find('table', {"id":table_visitor_abbr})
        df_visitor = pd.read_html(str(table_visitor))
        df_visitor = df_visitor[0]
        new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
        np_array = np.arange(len(df_visitor.columns))
        list_ = np_array.tolist()
        df_visitor.columns = df_visitor.columns.droplevel(0)
#renaming columns
        for j in range(len(df_visitor.columns)):
            old = df_visitor.columns[j]
            new = new_columns[j]
            df_visitor = df_visitor.rename(columns = {old:new})
        empty_ = []
        empty_.append(schedule_df.loc[ind].iloc[9])
#ID
        empty_.append(schedule_df.loc[ind].iloc[0])
#DATE
        empty_.append(schedule_df.loc[ind].iloc[6])
#home abbbr
        empty_.append(schedule_df.loc[ind].iloc[7])
#visitor abbr
        empty_.append(schedule_df.loc[ind].iloc[4])
#home points
        empty_.append(schedule_df.loc[ind].iloc[2])
#away points
        empty_.append(schedule_df.loc[ind].iloc[5])
#margin
        empty_.append(schedule_df.loc[ind].iloc[8])
#HOME_TEAM_WINS
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS
        length_of_df = len(box_score_df_main_2)
        box_score_df_main_2.loc[length_of_df] = empty_
        sleep(0.1)

In [84]:
box_score_df.tail(1)

,ID,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
17,359,2021-02-09,UTA,BOS,122.0,108.0,14,1,.476,.889,.375,28,41,.442,.826,.448,18,35

In [85]:
box_score_df_main_2.tail(20)

,ID,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
339,340,2021-02-07,CHO,WAS,119.0,97.0,22,1,0.424,0.769,0.417,21,59,0.378,0.714,0.225,22,48
340,341,2021-02-07,IND,UTA,95.0,103.0,-8,0,0.398,0.722,0.276,23,45,0.413,0.667,0.31,22,60
341,342,2021-02-07,NYK,MIA,103.0,109.0,-6,0,0.447,0.733,0.381,23,44,0.482,0.8,0.371,25,44
342,343,2021-02-07,PHO,BOS,100.0,91.0,9,1,0.488,1,0.276,25,50,0.355,0.667,0.386,19,41
343,344,2021-02-07,LAC,SAC,110.0,113.0,-3,0,0.414,0.87,0.286,19,53,0.489,0.733,0.345,25,52
344,345,2021-02-08,CHO,HOU,119.0,94.0,25,1,0.489,0.923,0.463,28,51,0.407,0.688,0.277,20,39
345,346,2021-02-08,CHI,WAS,101.0,105.0,-4,0,0.424,0.833,0.3,23,50,0.419,0.75,0.231,23,47
346,347,2021-02-08,MEM,TOR,113.0,128.0,-15,0,0.425,0.897,0.333,27,42,0.545,0.923,0.541,28,37
347,348,2021-02-08,DAL,MIN,127.0,122.0,5,1,0.517,0.833,0.353,30,48,0.462,0.714,0.429,27,41
348,349,2021-02-08,SAS,GSW,105.0,100.0,5,1,0.406,0.842,0.355,24,46,0.442,0.733,0.351,29,49
349,350,2021-02-08,PHO,CLE,119.0,113.0,6,1,0.522,0.737,0.458,29,41,0.512,0.68,0.333,23,39
350,351,2021-02-08,DEN,MIL,112.0,125.0,-13,0,0.436,0.938,0.417,22,38,0.506,0.864,0.4,24,50
351,352,2021-02-08,LAL,OKC,119.0,112.0,7,1,0.463,0.759,0.237,28,59,0.391,0.737,0.316,23,55
352,353,2021-02-09,DET,BRK,122.0,111.0,11,1,.560,.714,.448,28,37,.500,.875,.355,30,34
353,354,2021-02-09,MIA,NYK,98.0,96.0,2,1,.371,.821,.424,21,38,.425,.750,.357,22,46
354,355,2021-02-09,NOP,HOU,130.0,101.0,29,1,.511,.857,.387,31,55,.418,.571,.302,24,37
355,356,2021-02-09,SAS,GSW,91.0,114.0,-23,0,.372,.905,.333,20,45,.462,.684,.425,26,50
356,357,2021-02-09,POR,ORL,106.0,97.0,9,1,.389,.947,.391,18,54,.420,.545,.314,22,53
357,358,2021-02-09,SAC,PHI,111.0,119.0,-8,0,.434,.579,.333,24,39,.482,.800,.450,24,59
358,359,2021-02-09,UTA,BOS,122.0,108.0,14,1,.476,.889,.375,28,41,.442,.826,.448,18,35

In [86]:
#import dependencies
import sqlalchemy
# Import dependencies
import pandas as pd
from sqlalchemy import create_engine

# N.B. external config.py file should be formatted like:
# login = 'postgres:password' where password is set to whatever your database password is. Default username is 
# postgres, but change this if you use a different username.
import psycopg2
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'
                .format(username='postgres',
                        password='postgres',
                        ipaddress='localhost',
                        port=5432,
                        dbname='flask_deploy'))
# Create the connection
engine = create_engine(postgres_str)
cnx = engine.connect()

In [88]:
box_score_df_main_2.to_sql('box_score_2021', engine, if_exists='append', index=False)

In [89]:
box_score_df_main_2.to_csv('box_score_2021_V5.csv', index=False)