In [2]:
import pandas as pd
from urllib.request import urlopen
from bs4 import BeautifulSoup
import numpy as np
from time import sleep

In [3]:
df_ = pd.read_csv('partial_schedule_2021.csv')

In [7]:
df_compare = pd.read_csv('data/schedule2021.csv')

In [8]:
schedule_df = df_.copy()

In [9]:
df_compare.head(1)

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,VISITOR_ABBR,HOME_ABBR
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,GSW,BRK

In [10]:
box_score_columns = ['DATE', 'HOME_ABBR', 'VISITOR_ABBR', 'PTS_home', 'PTS_away', 'margin', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away', 'REB_away']
box_score_df = pd.DataFrame(columns=box_score_columns)

In [11]:
schedule_df.head(1)

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR,ID
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,26,BRK,GSW,1

In [13]:
#date_1 = schedule_df.loc[ind]['DATE'].replace(r"-","") + "0"
print(schedule_df.iloc[0,0].replace(r"-","")+ "0")

202012220

In [ ]:
for ind in schedule_df.head(1).index:
    if schedule_df['VISITOR_PTS'][ind] > 0:
        date_1 = schedule_df.loc[ind]['DATE'].replace(r"-","") + "0"
        home_1 = schedule_df.loc[ind]['HOME_ABBR']
        visitor_1 = schedule_df.loc[ind]['VISITOR_ABBR']
        basketball_url = "https://www.basketball-reference.com/boxscores/"
        url = basketball_url + date_1 + home_1 + ".html"
        html = urlopen(url)
        soup = BeautifulSoup(html)
        table_home_abbr = "box-{0}-game-basic".format(home_1)
        table_visitor_abbr = "box-{0}-game-basic".format(visitor_1)
        table_home = soup.find('table', {"id":table_home_abbr})
        df_home = pd.read_html(str(table_home))
        df_home = df_home[0]
        new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
        np_array = np.arange(len(df_home.columns))
        list_ = np_array.tolist()
        df_home.columns = df_home.columns.droplevel(0)
#renaming columns
        for j in range(len(df_home.columns)):
            old = df_home.columns[j]
            new = new_columns[j]
            df_home = df_home.rename(columns = {old:new})
        table_visitor = soup.find('table', {"id":table_visitor_abbr})
        df_visitor = pd.read_html(str(table_visitor))
        df_visitor = df_visitor[0]
        new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
        np_array = np.arange(len(df_visitor.columns))
        list_ = np_array.tolist()
        df_visitor.columns = df_visitor.columns.droplevel(0)
#renaming columns
        for j in range(len(df_visitor.columns)):
            old = df_visitor.columns[j]
            new = new_columns[j]
            df_visitor = df_visitor.rename(columns = {old:new})
        empty_ = []
        empty_.append(schedule_df.loc[ind].iloc[0])
#DATE
        empty_.append(schedule_df.loc[ind].iloc[6])
#home abbbr
        empty_.append(schedule_df.loc[ind].iloc[5])
#visitor abbr
        empty_.append(schedule_df.loc[ind].iloc[4])
#home points
        empty_.append(schedule_df.loc[ind].iloc[2])
#away points
        empty_.append(schedule_df.loc[ind].iloc[7])
#margin
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS
        length_of_df = len(box_score_df)
        box_score_df.loc[length_of_df] = empty_
        sleep(0.1)

In [17]:
for ind in schedule_df.head(1).index:
    if schedule_df['VISITOR_PTS'][ind] > 0:
        date_1 = schedule_df.loc[ind]['DATE'].replace(r"-","") + "0"
        home_1 = schedule_df.loc[ind]['HOME_ABBR']
        visitor_1 = schedule_df.loc[ind]['VISITOR_ABBR']
        basketball_url = "https://www.basketball-reference.com/boxscores/"
        url = basketball_url + date_1 + home_1 + ".html"
        html = urlopen(url)
        soup = BeautifulSoup(html)
        table_home_abbr = "box-{0}-game-basic".format(home_1)
        table_visitor_abbr = "box-{0}-game-basic".format(visitor_1)
        table_home = soup.find('table', {"id":table_home_abbr})
        df_home = pd.read_html(str(table_home))
        df_home = df_home[0]
        new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
        np_array = np.arange(len(df_home.columns))
        list_ = np_array.tolist()
        df_home.columns = df_home.columns.droplevel(0)
#renaming columns
        for j in range(len(df_home.columns)):
            old = df_home.columns[j]
            new = new_columns[j]
            df_home = df_home.rename(columns = {old:new})
        table_visitor = soup.find('table', {"id":table_visitor_abbr})
        df_visitor = pd.read_html(str(table_visitor))
        df_visitor = df_visitor[0]
        new_columns = ['STARTERS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-']
        np_array = np.arange(len(df_visitor.columns))
        list_ = np_array.tolist()
        df_visitor.columns = df_visitor.columns.droplevel(0)
#renaming columns
        for j in range(len(df_visitor.columns)):
            old = df_visitor.columns[j]
            new = new_columns[j]
            df_visitor = df_visitor.rename(columns = {old:new})
        empty_ = []
        empty_.append(schedule_df.loc[ind].iloc[0])
#DATE
        empty_.append(schedule_df.loc[ind].iloc[6])
#home abbbr
        empty_.append(schedule_df.loc[ind].iloc[5])
#visitor abbr
        empty_.append(schedule_df.loc[ind].iloc[4])
#home points
        empty_.append(schedule_df.loc[ind].iloc[2])
#away points
        empty_.append(schedule_df.loc[ind].iloc[7])
#margin
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
        empty_.append(df_home.loc[df_home['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,4])
#FG_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,10])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,7])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,14])
#FT_PCT
        empty_.append(df_visitor.loc[df_visitor['STARTERS'] == 'Team Totals'].iloc[0,13])
#REBOUNDS
        length_of_df = len(box_score_df)
        box_score_df.loc[length_of_df] = empty_
        sleep(0.1)

In [18]:
box_score_df

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,margin,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,2020-12-22,BRK,26,125.0,99.0,GSW,.457,.813,.429,24,57,.374,.652,.303,26,47
1,2020-12-22,BRK,26,125.0,99.0,GSW,.457,.813,.429,24,57,.374,.652,.303,26,47