In [1]:
import pandas as pd

In [17]:
df = pd.read_csv('games.csv')

In [18]:
#pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

In [19]:
df

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2020-12-19,12000047,Final,1610612753,1610612766,2020,1610612753,120.0,0.433,0.792,...,23.0,50.0,1610612766,117.0,0.444,0.864,0.439,21.0,52.0,1
1,2020-12-19,12000048,Final,1610612764,1610612765,2020,1610612764,99.0,0.427,0.625,...,24.0,45.0,1610612765,96.0,0.402,0.647,0.326,18.0,51.0,1
2,2020-12-19,12000049,Final,1610612763,1610612737,2020,1610612763,116.0,0.400,0.744,...,21.0,43.0,1610612737,117.0,0.422,0.837,0.297,24.0,47.0,0
3,2020-12-18,12000039,Final,1610612754,1610612755,2020,1610612754,107.0,0.371,0.692,...,19.0,45.0,1610612755,113.0,0.533,0.629,0.355,23.0,48.0,0
4,2020-12-18,12000040,Final,1610612761,1610612748,2020,1610612761,105.0,0.380,0.737,...,27.0,37.0,1610612748,117.0,0.534,0.741,0.514,30.0,51.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23515,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,...,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
23516,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,...,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
23517,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,...,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
23518,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,...,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
23519,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [20]:
mask = (df['GAME_DATE_EST'] > '2020-08-16') & (df['GAME_DATE_EST'] <= '2020-08-19')

In [21]:
df = df.loc[mask]

In [23]:
df

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
120,2020-08-19,41900112,Final,1610612761,1610612751,2019,1610612761,104.0,0.437,0.679,...,22.0,44.0,1610612751,99.0,0.388,0.704,0.341,25.0,46.0,1
121,2020-08-19,41900162,Final,1610612743,1610612762,2019,1610612743,105.0,0.457,0.783,...,22.0,41.0,1610612762,124.0,0.517,0.824,0.455,32.0,36.0,0
122,2020-08-19,41900122,Final,1610612738,1610612755,2019,1610612738,128.0,0.512,0.724,...,20.0,43.0,1610612755,101.0,0.418,0.811,0.238,21.0,38.0,1
123,2020-08-19,41900152,Final,1610612746,1610612742,2019,1610612746,114.0,0.440,0.769,...,16.0,47.0,1610612742,127.0,0.500,0.703,0.448,25.0,49.0,0
124,2020-08-18,41900101,Final,1610612749,1610612753,2019,1610612749,110.0,0.433,0.643,...,28.0,47.0,1610612753,122.0,0.494,0.947,0.390,29.0,48.0,0
125,2020-08-18,41900131,Final,1610612754,1610612748,2019,1610612754,101.0,0.474,0.864,...,22.0,37.0,1610612748,113.0,0.494,0.800,0.371,22.0,35.0,0
126,2020-08-18,41900171,Final,1610612745,1610612760,2019,1610612745,123.0,0.483,0.895,...,25.0,36.0,1610612760,108.0,0.440,0.840,0.371,22.0,46.0,1
127,2020-08-18,41900141,Final,1610612747,1610612757,2019,1610612747,93.0,0.351,0.645,...,22.0,55.0,1610612757,100.0,0.392,0.758,0.382,18.0,50.0,0
128,2020-08-17,41900161,Final,1610612743,1610612762,2019,1610612743,135.0,0.516,0.833,...,23.0,41.0,1610612762,125.0,0.474,0.739,0.340,18.0,52.0,1
129,2020-08-17,41900111,Final,1610612761,1610612751,2019,1610612761,134.0,0.471,0.970,...,26.0,47.0,1610612751,110.0,0.467,0.688,0.310,33.0,45.0,1
130,2020-08-17,41900121,Final,1610612738,1610612755,2019,1610612738,109.0,0.422,0.885,...,22.0,43.0,1610612755,101.0,0.463,0.783,0.333,23.0,50.0,1
131,2020-08-17,41900151,Final,1610612746,1610612742,2019,1610612746,118.0,0.474,0.750,...,18.0,45.0,1610612742,110.0,0.457,0.875,0.349,18.0,41.0,1

In [25]:
df = df.drop_duplicates(subset=['HOME_TEAM_ID'])

In [26]:
df

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
120,2020-08-19,41900112,Final,1610612761,1610612751,2019,1610612761,104.0,0.437,0.679,...,22.0,44.0,1610612751,99.0,0.388,0.704,0.341,25.0,46.0,1
121,2020-08-19,41900162,Final,1610612743,1610612762,2019,1610612743,105.0,0.457,0.783,...,22.0,41.0,1610612762,124.0,0.517,0.824,0.455,32.0,36.0,0
122,2020-08-19,41900122,Final,1610612738,1610612755,2019,1610612738,128.0,0.512,0.724,...,20.0,43.0,1610612755,101.0,0.418,0.811,0.238,21.0,38.0,1
123,2020-08-19,41900152,Final,1610612746,1610612742,2019,1610612746,114.0,0.440,0.769,...,16.0,47.0,1610612742,127.0,0.500,0.703,0.448,25.0,49.0,0
124,2020-08-18,41900101,Final,1610612749,1610612753,2019,1610612749,110.0,0.433,0.643,...,28.0,47.0,1610612753,122.0,0.494,0.947,0.390,29.0,48.0,0
125,2020-08-18,41900131,Final,1610612754,1610612748,2019,1610612754,101.0,0.474,0.864,...,22.0,37.0,1610612748,113.0,0.494,0.800,0.371,22.0,35.0,0
126,2020-08-18,41900171,Final,1610612745,1610612760,2019,1610612745,123.0,0.483,0.895,...,25.0,36.0,1610612760,108.0,0.440,0.840,0.371,22.0,46.0,1
127,2020-08-18,41900141,Final,1610612747,1610612757,2019,1610612747,93.0,0.351,0.645,...,22.0,55.0,1610612757,100.0,0.392,0.758,0.382,18.0,50.0,0

In [27]:
df.to_csv('playoffs.csv', index=False)

In [6]:
df_m = df.head(800)

In [7]:
len(df_m)

800

In [8]:
df_m

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
120,2020-08-19,41900112,Final,1610612761,1610612751,2019,1610612761,104.0,0.437,0.679,...,22.0,44.0,1610612751,99.0,0.388,0.704,0.341,25.0,46.0,1
121,2020-08-19,41900162,Final,1610612743,1610612762,2019,1610612743,105.0,0.457,0.783,...,22.0,41.0,1610612762,124.0,0.517,0.824,0.455,32.0,36.0,0
122,2020-08-19,41900122,Final,1610612738,1610612755,2019,1610612738,128.0,0.512,0.724,...,20.0,43.0,1610612755,101.0,0.418,0.811,0.238,21.0,38.0,1
123,2020-08-19,41900152,Final,1610612746,1610612742,2019,1610612746,114.0,0.440,0.769,...,16.0,47.0,1610612742,127.0,0.500,0.703,0.448,25.0,49.0,0
124,2020-08-18,41900101,Final,1610612749,1610612753,2019,1610612749,110.0,0.433,0.643,...,28.0,47.0,1610612753,122.0,0.494,0.947,0.390,29.0,48.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,2019-12-04,21900311,Final,1610612741,1610612763,2019,1610612741,106.0,0.429,0.730,...,22.0,50.0,1610612763,99.0,0.385,0.857,0.233,24.0,46.0,1
916,2019-12-04,21900312,Final,1610612760,1610612754,2019,1610612760,100.0,0.488,0.900,...,25.0,37.0,1610612754,107.0,0.483,0.824,0.375,19.0,39.0,0
917,2019-12-04,21900313,Final,1610612742,1610612750,2019,1610612742,121.0,0.500,0.783,...,24.0,45.0,1610612750,114.0,0.416,0.885,0.447,23.0,44.0,1
918,2019-12-04,21900314,Final,1610612762,1610612747,2019,1610612762,96.0,0.410,0.737,...,20.0,40.0,1610612747,121.0,0.511,0.600,0.483,27.0,46.0,0
919,2019-12-04,21900315,Final,1610612757,1610612758,2019,1610612757,127.0,0.560,0.810,...,28.0,43.0,1610612758,116.0,0.463,0.739,0.324,26.0,44.0,1

In [49]:
df_m.to_csv('example800.csv', index=False)

In [8]:
df2 = df_m.loc[df_m['HOME_TEAM_ID'] == 1610612738]

In [9]:
df2 = df2.head(10)

In [10]:
df2

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
57,2020-09-25,41900305,Final,1610612738,1610612748,2019,1610612738,121.0,0.452,0.862,...,29.0,50.0,1610612748,108.0,0.453,0.793,0.194,27.0,38.0,1
64,2020-09-17,41900302,Final,1610612738,1610612748,2019,1610612738,101.0,0.500,0.792,...,19.0,41.0,1610612748,106.0,0.444,0.857,0.326,27.0,38.0,0
65,2020-09-15,41900301,Final,1610612738,1610612748,2019,1610612738,114.0,0.443,0.913,...,24.0,37.0,1610612748,117.0,0.471,0.750,0.444,32.0,41.0,0
72,2020-09-09,41900216,Final,1610612738,1610612761,2019,1610612738,122.0,0.440,0.833,...,32.0,58.0,1610612761,125.0,0.436,0.720,0.404,22.0,46.0,0
80,2020-09-05,41900214,Final,1610612738,1610612761,2019,1610612738,93.0,0.440,0.741,...,18.0,45.0,1610612761,100.0,0.395,0.789,0.386,23.0,41.0,0
84,2020-09-03,41900213,Final,1610612738,1610612761,2019,1610612738,103.0,0.470,0.762,...,21.0,44.0,1610612761,104.0,0.466,0.563,0.325,23.0,39.0,0
122,2020-08-19,41900122,Final,1610612738,1610612755,2019,1610612738,128.0,0.512,0.724,...,20.0,43.0,1610612755,101.0,0.418,0.811,0.238,21.0,38.0,1
130,2020-08-17,41900121,Final,1610612738,1610612755,2019,1610612738,109.0,0.422,0.885,...,22.0,43.0,1610612755,101.0,0.463,0.783,0.333,23.0,50.0,1
137,2020-08-13,21901308,Final,1610612738,1610612764,2019,1610612738,90.0,0.398,0.857,...,22.0,51.0,1610612764,96.0,0.386,0.750,0.385,22.0,56.0,0
163,2020-08-09,21901288,Final,1610612738,1610612753,2019,1610612738,122.0,0.441,0.833,...,32.0,54.0,1610612753,119.0,0.402,0.846,0.319,24.0,52.0,1

In [11]:
df2 = df2.reset_index(drop=True)

In [12]:
len(df2)

10

In [13]:
df3 = df_m.loc[df_m['VISITOR_TEAM_ID'] == 1610612748]

In [14]:
df3.head(10)

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
50,2020-10-09,41900405,Final,1610612747,1610612748,2019,1610612747,108.0,0.463,0.857,...,21.0,41.0,1610612748,111.0,0.458,0.955,0.424,26.0,35.0,0
53,2020-10-02,41900402,Final,1610612747,1610612748,2019,1610612747,124.0,0.505,0.588,...,32.0,44.0,1610612748,114.0,0.507,0.912,0.407,29.0,37.0,1
54,2020-09-30,41900401,Final,1610612747,1610612748,2019,1610612747,116.0,0.452,0.926,...,26.0,54.0,1610612748,98.0,0.427,0.786,0.314,23.0,36.0,1
57,2020-09-25,41900305,Final,1610612738,1610612748,2019,1610612738,121.0,0.452,0.862,...,29.0,50.0,1610612748,108.0,0.453,0.793,0.194,27.0,38.0,1
64,2020-09-17,41900302,Final,1610612738,1610612748,2019,1610612738,101.0,0.500,0.792,...,19.0,41.0,1610612748,106.0,0.444,0.857,0.326,27.0,38.0,0
65,2020-09-15,41900301,Final,1610612738,1610612748,2019,1610612738,114.0,0.443,0.913,...,24.0,37.0,1610612748,117.0,0.471,0.750,0.444,32.0,41.0,0
74,2020-09-08,41900205,Final,1610612749,1610612748,2019,1610612749,94.0,0.363,0.731,...,20.0,41.0,1610612748,103.0,0.479,0.917,0.355,21.0,48.0,0
86,2020-09-02,41900202,Final,1610612749,1610612748,2019,1610612749,114.0,0.435,0.846,...,16.0,50.0,1610612748,116.0,0.457,0.781,0.378,22.0,38.0,0
90,2020-08-31,41900201,Final,1610612749,1610612748,2019,1610612749,104.0,0.493,0.538,...,22.0,34.0,1610612748,115.0,0.464,0.926,0.387,21.0,46.0,0
116,2020-08-20,41900132,Final,1610612754,1610612748,2019,1610612754,100.0,0.444,0.800,...,25.0,38.0,1610612748,109.0,0.474,0.679,0.514,27.0,41.0,0

Export list to explore which numbers to go with

In [15]:
df3 = df3.reset_index(drop=True)

In [16]:
average_home = df2.groupby(['HOME_TEAM_ID'])
home_df = average_home.mean()

In [17]:
average_away = df3.groupby(['VISITOR_TEAM_ID'])
away_df = average_away.mean()

In [18]:
away_df

,GAME_ID,HOME_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
VISITOR_TEAM_ID,,,,,,,,,,,,,,,,,,
1610612748,2.773393e+07,1.610613e+09,2019.0,1.610613e+09,111.027778,0.454833,0.786111,0.366611,25.055556,43.277778,1.610613e+09,109.472222,0.457194,0.807389,0.362861,25.138889,42.611111,0.555556

In [19]:
#away_df.to_csv('example2.csv')

In [20]:
home_df

,GAME_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
HOME_TEAM_ID,,,,,,,,,,,,,,,,,,
1610612738,37900439.0,1.610613e+09,2019.0,1.610613e+09,110.3,0.4518,0.8202,0.3247,23.9,46.6,1.610613e+09,107.7,0.4334,0.7662,0.3354,24.4,43.9,0.4

In [62]:
away_df.iloc[0,1]

109.47222222222223

In [11]:
df2.columns

Index(['GAME_DATE_EST', 'GAME_ID', 'GAME_STATUS_TEXT', 'HOME_TEAM_ID',
       'VISITOR_TEAM_ID', 'SEASON', 'TEAM_ID_home', 'PTS_home', 'FG_PCT_home',
       'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'TEAM_ID_away',
       'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away',
       'REB_away', 'HOME_TEAM_WINS'],
      dtype='object')

In [12]:
df2.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2020-12-19,12000047,Final,1610612753,1610612766,2020,1610612753,120.0,0.433,0.792,0.425,23.0,50.0,1610612766,117.0,0.444,0.864,0.439,21.0,52.0,1
1,2020-12-19,12000048,Final,1610612764,1610612765,2020,1610612764,99.0,0.427,0.625,0.295,24.0,45.0,1610612765,96.0,0.402,0.647,0.326,18.0,51.0,1
2,2020-12-19,12000049,Final,1610612763,1610612737,2020,1610612763,116.0,0.400,0.744,0.396,21.0,43.0,1610612737,117.0,0.422,0.837,0.297,24.0,47.0,0
3,2020-12-18,12000039,Final,1610612754,1610612755,2020,1610612754,107.0,0.371,0.692,0.262,19.0,45.0,1610612755,113.0,0.533,0.629,0.355,23.0,48.0,0
4,2020-12-18,12000040,Final,1610612761,1610612748,2020,1610612761,105.0,0.380,0.737,0.356,27.0,37.0,1610612748,117.0,0.534,0.741,0.514,30.0,51.0,0

In [27]:
away_df = away_df[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]

In [28]:
away_df

,PTS_home,PTS_away,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
VISITOR_TEAM_ID,,,,,,,,,,,,
1610612748,111.027778,109.472222,0.454833,0.786111,0.366611,25.055556,43.277778,0.457194,0.807389,0.362861,25.138889,42.611111

In [29]:
home_df = home_df[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]

In [30]:
home_df

,PTS_home,PTS_away,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
HOME_TEAM_ID,,,,,,,,,,,,
1610612738,110.3,107.7,0.4518,0.8202,0.3247,23.9,46.6,0.4334,0.7662,0.3354,24.4,43.9

In [34]:
empty_ = []
empty_.append(home_df.iloc[0,0])
empty_.append(away_df.iloc[0,1])
empty_.append(home_df.iloc[0,2])
empty_.append(home_df.iloc[0,3])
empty_.append(home_df.iloc[0,4])
empty_.append(home_df.iloc[0,5])
empty_.append(home_df.iloc[0,6])
empty_.append(away_df.iloc[0,7])
empty_.append(away_df.iloc[0,8])
empty_.append(away_df.iloc[0,9])
empty_.append(away_df.iloc[0,10])
empty_.append(away_df.iloc[0,11])

In [35]:
empty_

[110.3,
 109.47222222222223,
 0.4518,
 0.8201999999999998,
 0.3247,
 23.9,
 46.6,
 0.45719444444444446,
 0.8073888888888889,
 0.36286111111111113,
 25.13888888888889,
 42.611111111111114]

In [36]:
away_df.columns

Index(['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home',
       'AST_home', 'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away'],
      dtype='object')

In [37]:
home_away_df= pd.DataFrame(columns=away_df.columns)

In [41]:
home_away_df.loc[0] = empty_

In [42]:
home_away_df

,PTS_home,PTS_away,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,110.3,109.472222,0.4518,0.8202,0.3247,23.9,46.6,0.457194,0.807389,0.362861,25.138889,42.611111