In [1]:
import pandas as pd

In [2]:
teams_df = pd.read_csv('teams.csv')

In [5]:
teams_df = teams_df[['TEAM_ID', 'ABBREVIATION']]

In [7]:
teams_df = teams_df.set_index(['TEAM_ID'])

In [14]:
teams_df.columns.droplevel()

ValueError: Cannot remove 1 levels from an index with 1 levels: at least one level must be left.

In [29]:
team_to_abbreviation = teams_df.to_dict()

In [30]:
team_to_abbreviation = team_to_abbreviation['ABBREVIATION']

In [31]:
team_to_abbreviation[1610612737]

'ATL'

In [32]:
teams_to_abbreviation

{1610612737: 'ATL',
 1610612738: 'BOS',
 1610612740: 'NOP',
 1610612741: 'CHI',
 1610612742: 'DAL',
 1610612743: 'DEN',
 1610612745: 'HOU',
 1610612746: 'LAC',
 1610612747: 'LAL',
 1610612748: 'MIA',
 1610612749: 'MIL',
 1610612750: 'MIN',
 1610612751: 'BKN',
 1610612752: 'NYK',
 1610612753: 'ORL',
 1610612754: 'IND',
 1610612755: 'PHI',
 1610612756: 'PHX',
 1610612757: 'POR',
 1610612758: 'SAC',
 1610612759: 'SAS',
 1610612760: 'OKC',
 1610612761: 'TOR',
 1610612762: 'UTA',
 1610612763: 'MEM',
 1610612764: 'WAS',
 1610612765: 'DET',
 1610612766: 'CHA',
 1610612739: 'CLE',
 1610612744: 'GSW'}

In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('games.csv')

In [23]:
#pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

In [ ]:
VISITOR_ABBR	HOME_ABBR

In [ ]:
df[VISITOR_ABBR	HOME_ABBR]

In [41]:
df['VISITOR_ABBR'] = 0
df['HOME_ABBR'] = 0

TUTORIAL

```python
#already rean so read this
#run this to include abbreviations
for ind in sample_df.index:
    visitor = sample_df['VISITOR_TEAM_ID'][ind]
    home = sample_df['HOME_TEAM_ID'][ind]
    sample_df['VISITOR_ABBR'][ind] = team_to_abbreviation[visitor]
    sample_df['HOME_ABBR'][ind] = team_to_abbreviation[home]
```

In [37]:
sample_df['HOME_ABBR'] = 0

/Users/stanleytan/anaconda3/envs/MachineLearning/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [43]:
for ind in df.index:
    visitor = df['VISITOR_TEAM_ID'][ind]
    home = df['HOME_TEAM_ID'][ind]
    df['VISITOR_ABBR'][ind] = team_to_abbreviation[visitor]
    df['HOME_ABBR'][ind] = team_to_abbreviation[home]

/Users/stanleytan/anaconda3/envs/MachineLearning/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/stanleytan/anaconda3/envs/MachineLearning/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [45]:
df.to_csv('abbr_games.csv', index=False)

In [119]:
df

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2020-12-19,12000047,Final,1610612753,1610612766,2020,1610612753,120.0,0.433,0.792,...,23.0,50.0,1610612766,117.0,0.444,0.864,0.439,21.0,52.0,1
1,2020-12-19,12000048,Final,1610612764,1610612765,2020,1610612764,99.0,0.427,0.625,...,24.0,45.0,1610612765,96.0,0.402,0.647,0.326,18.0,51.0,1
2,2020-12-19,12000049,Final,1610612763,1610612737,2020,1610612763,116.0,0.400,0.744,...,21.0,43.0,1610612737,117.0,0.422,0.837,0.297,24.0,47.0,0
3,2020-12-18,12000039,Final,1610612754,1610612755,2020,1610612754,107.0,0.371,0.692,...,19.0,45.0,1610612755,113.0,0.533,0.629,0.355,23.0,48.0,0
4,2020-12-18,12000040,Final,1610612761,1610612748,2020,1610612761,105.0,0.380,0.737,...,27.0,37.0,1610612748,117.0,0.534,0.741,0.514,30.0,51.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23515,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,...,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
23516,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,...,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
23517,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,...,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
23518,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,...,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
23519,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [47]:
#need to run
df = df.loc[df['GAME_DATE_EST'] < '2020-08-16']

In [50]:
# need to run
df_m = df.head(800)

In [49]:
len(df_m)

800

In [123]:
#df_m.to_csv('example800.csv', index=False)

Compile the code here:
```python
df2 = df_m.loc[df_m['HOME_TEAM_ID'] == number]
df2 = df2.head(10)
df2 = df2.reset_index(drop=True)
average_home = df2.groupby(['HOME_TEAM_ID'])
home_df = average_home.mean()
home_df = home_df[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]

df3 = df_m.loc[df_m['VISITOR_TEAM_ID'] == number]
df3 = df3.head(10)
df3 = df3.reset_index(drop=True)
average_away = df3.groupby(['VISITOR_TEAM_ID'])
away_df = average_away.mean()
away_df = away_df[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]

empty_ = []
empty_.append(home_df.iloc[0,0])
empty_.append(away_df.iloc[0,1])
empty_.append(home_df.iloc[0,2])
empty_.append(home_df.iloc[0,3])
empty_.append(home_df.iloc[0,4])
empty_.append(home_df.iloc[0,5])
empty_.append(home_df.iloc[0,6])
empty_.append(away_df.iloc[0,7])
empty_.append(away_df.iloc[0,8])
empty_.append(away_df.iloc[0,9])
empty_.append(away_df.iloc[0,10])
empty_.append(away_df.iloc[0,11])

length_of_df = len(home_away_df)
home_away_df.loc[length_of_df] = empty_

```

Rinse and repeat

Export list to explore which numbers to go with

In [54]:
import pandas as pd
playoffs_df = pd.read_csv('playoffs.csv')

In [55]:
playoffs_df['VISITOR_ABBR'] = 0
playoffs_df['HOME_ABBR'] = 0

In [58]:
for ind in playoffs_df.index:
    visitor = playoffs_df['VISITOR_TEAM_ID'][ind]
    home = playoffs_df['HOME_TEAM_ID'][ind]
    playoffs_df['VISITOR_ABBR'][ind] = team_to_abbreviation[visitor]
    playoffs_df['HOME_ABBR'][ind] = team_to_abbreviation[home]

/Users/stanleytan/anaconda3/envs/MachineLearning/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/stanleytan/anaconda3/envs/MachineLearning/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [59]:
playoffs_df

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,VISITOR_ABBR,HOME_ABBR
0,2020-08-19,41900112,Final,1610612761,1610612751,2019,1610612761,104.0,0.437,0.679,...,1610612751,99.0,0.388,0.704,0.341,25.0,46.0,1,BKN,TOR
1,2020-08-19,41900162,Final,1610612743,1610612762,2019,1610612743,105.0,0.457,0.783,...,1610612762,124.0,0.517,0.824,0.455,32.0,36.0,0,UTA,DEN
2,2020-08-19,41900122,Final,1610612738,1610612755,2019,1610612738,128.0,0.512,0.724,...,1610612755,101.0,0.418,0.811,0.238,21.0,38.0,1,PHI,BOS
3,2020-08-19,41900152,Final,1610612746,1610612742,2019,1610612746,114.0,0.440,0.769,...,1610612742,127.0,0.500,0.703,0.448,25.0,49.0,0,DAL,LAC
4,2020-08-18,41900101,Final,1610612749,1610612753,2019,1610612749,110.0,0.433,0.643,...,1610612753,122.0,0.494,0.947,0.390,29.0,48.0,0,ORL,MIL
5,2020-08-18,41900131,Final,1610612754,1610612748,2019,1610612754,101.0,0.474,0.864,...,1610612748,113.0,0.494,0.800,0.371,22.0,35.0,0,MIA,IND
6,2020-08-18,41900171,Final,1610612745,1610612760,2019,1610612745,123.0,0.483,0.895,...,1610612760,108.0,0.440,0.840,0.371,22.0,46.0,1,OKC,HOU
7,2020-08-18,41900141,Final,1610612747,1610612757,2019,1610612747,93.0,0.351,0.645,...,1610612757,100.0,0.392,0.758,0.382,18.0,50.0,0,POR,LAL

In [126]:
win_loss_df = playoffs_df[['HOME_TEAM_WINS']]
win_loss_df

   HOME_TEAM_WINS
0               1
1               0
2               1
3               0
4               0
5               0
6               1
7               0

In [127]:
#playoffs_df = playoffs_df.head(2)

In [128]:
playoffs_df

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2020-08-19,41900112,Final,1610612761,1610612751,2019,1610612761,104.0,0.437,0.679,...,22.0,44.0,1610612751,99.0,0.388,0.704,0.341,25.0,46.0,1
1,2020-08-19,41900162,Final,1610612743,1610612762,2019,1610612743,105.0,0.457,0.783,...,22.0,41.0,1610612762,124.0,0.517,0.824,0.455,32.0,36.0,0
2,2020-08-19,41900122,Final,1610612738,1610612755,2019,1610612738,128.0,0.512,0.724,...,20.0,43.0,1610612755,101.0,0.418,0.811,0.238,21.0,38.0,1
3,2020-08-19,41900152,Final,1610612746,1610612742,2019,1610612746,114.0,0.440,0.769,...,16.0,47.0,1610612742,127.0,0.500,0.703,0.448,25.0,49.0,0
4,2020-08-18,41900101,Final,1610612749,1610612753,2019,1610612749,110.0,0.433,0.643,...,28.0,47.0,1610612753,122.0,0.494,0.947,0.390,29.0,48.0,0
5,2020-08-18,41900131,Final,1610612754,1610612748,2019,1610612754,101.0,0.474,0.864,...,22.0,37.0,1610612748,113.0,0.494,0.800,0.371,22.0,35.0,0
6,2020-08-18,41900171,Final,1610612745,1610612760,2019,1610612745,123.0,0.483,0.895,...,25.0,36.0,1610612760,108.0,0.440,0.840,0.371,22.0,46.0,1
7,2020-08-18,41900141,Final,1610612747,1610612757,2019,1610612747,93.0,0.351,0.645,...,22.0,55.0,1610612757,100.0,0.392,0.758,0.382,18.0,50.0,0

Tutorial
```python
for ind in df2.index: 
    df2['margin'][ind] = df2['PTS_home'][ind] - df2['PTS_away'][ind]
```

In [60]:
playoffs_df.to_csv('playoffs.csv')

In [52]:
#hoping that playoffs has the abbreviations done.

In [129]:
home_away_df= pd.DataFrame(columns=away_df.columns)
#create empty dataframe

In [122]:
#trying to gather something more
home_df2= df_m.loc[df_m['HOME_ABBR'] == 'ORL']
home_as_visitor_df2 = df_m.loc[df_m['VISITOR_ABBR'] == 'ORL']
home_df2_length = len(home_df2)
home_as_visitor_df2_length = len(home_as_visitor_df2)
#might consider later in the weighted average
home_df2 = home_df2.groupby(['HOME_ABBR']).mean()
home_df2 = home_df2[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]
home_as_visitor_df2 = home_as_visitor_df2.groupby(['VISITOR_ABBR']).mean()
home_as_visitor_df2 = home_as_visitor_df2[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]
home_pts = 0.75 * home_df2.iloc[0,0] + 0.25 * home_as_visitor_df2.iloc[0,1]
#home_pts
home_fg3_pct = 0.75 * home_df2.iloc[0,4] + 0.25 * home_as_visitor_df2.iloc[0,9]
home_ast = 0.75 * home_df2.iloc[0,5] + 0.25 * home_as_visitor_df2.iloc[0,10]
home_reb = 0.75 * home_df2.iloc[0,6] + 0.25 * home_as_visitor_df2.iloc[0,11]
home_fg_pct = 0.75 * home_df2.iloc[0,2] + 0.25 * home_as_visitor_df2.iloc[0,7]

In [123]:
print(f'home points = {home_pts}')
print(f'home fg3 points = {home_fg3_pct}')
print(f'home assist = {home_ast}')
print(f'home rebounds = {home_reb}')
print(f'home fg pct = {home_fg_pct}')

home points = 108.69562499999999
home fg3 points = 0.34303937500000004
home assist = 24.738125
home rebounds = 44.467187499999994
home fg pct = 0.44587499999999997

In [130]:
visitor_df2= df_m.loc[df_m['VISITOR_ABBR'] == 'ORL']
visitor_as_home_df2 = df_m.loc[df_m['HOME_ABBR'] == 'ORL']
visitor_df2_length = len(visitor_df2)
visitor_as_home_df2_length = len(visitor_as_home_df2)
visitor_df2 = visitor_df2.groupby(['VISITOR_ABBR']).mean()

In [132]:
visitor_df2 = visitor_df2[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]

In [136]:
#trying to gather something more
visitor_df2= df_m.loc[df_m['VISITOR_ABBR'] == 'ORL']
visitor_as_home_df2 = df_m.loc[df_m['HOME_ABBR'] == 'ORL']
visitor_df2_length = len(visitor_df2)
visitor_as_home_df2_length = len(visitor_as_home_df2)
#might consider later in the weighted average
visitor_df2 = visitor_df2.groupby(['VISITOR_ABBR']).mean()
visitor_df2 = visitor_df2[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]
visitor_as_home_df2 = visitor_as_home_df2.groupby(['HOME_ABBR']).mean()
visitor_as_home_df2 = visitor_as_home_df2[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]

In [139]:
visitor_as_home_df2 = df_m.loc[df_m['HOME_ABBR'] == 'ORL']

In [141]:
visitor_as_home_df2 = visitor_as_home_df2.groupby(['HOME_ABBR']).mean()
visitor_as_home_df2 = visitor_as_home_df2[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]

In [137]:
visitor_df2

,PTS_home,PTS_away,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
VISITOR_ABBR,,,,,,,,,,,,
ORL,110.71875,110.0625,0.477063,0.755125,0.374344,26.09375,44.53125,0.4545,0.767031,0.363437,24.3125,43.46875

In [143]:
visitor_as_home_df2

,PTS_home,PTS_away,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
HOME_ABBR,,,,,,,,,,,,
ORL,108.24,110.12,0.443,0.7628,0.33624,24.88,44.8,0.47252,0.78484,0.37664,24.4,44.88

In [145]:
visitor_pts = 0.75* visitor_df2.iloc[0,1] + 0.25*visitor_as_home_df2.iloc[0,0]
visitor_fg3_pct = 0.75 * visitor_df2.iloc[0,9] + 0.25*visitor_as_home_df2.iloc[0,4]
visitor_ast = 0.75 * visitor_df2.iloc[0,10] + 0.25*visitor_as_home_df2.iloc[0,5]
visitor_reb = 0.75 * visitor_df2.iloc[0,11] + 0.25*visitor_as_home_df2.iloc[0,6]
visitor_fg_pct = 0.75 * visitor_df2.iloc[0,7] + 0.25*visitor_as_home_df2.iloc[0,2]

In [114]:

visitor_pts = 0.75 * visitor_df2.iloc[0,0] + 0.25 * visitor_as_visitor_df2.iloc[0,1]
#visitor_pts
visitor_fg3_pct = 0.75 * visitor_df2.iloc[0,4] + 0.25 * visitor_as_visitor_df2.iloc[0,9]
visitor_ast = 0.75 * visitor_df2.iloc[0,5] + 0.25 * visitor_as_visitor_df2.iloc[0,10]
visitor_reb = 0.75 * visitor_df2.iloc[0,6] + 0.25 * visitor_as_visitor_df2.iloc[0,11]
visitor_fg_pct = 0.75 * visitor_df2.iloc[0,2] + 0.25 * visitor_as_visitor_df2.iloc[0,7]

0.33224999999999993

In [146]:
print(f'visitor points = {visitor_pts}')
print(f'visitor fg3 points = {visitor_fg3_pct}')
print(f'visitor assist = {visitor_ast}')
print(f'visitor rebounds = {visitor_reb}')
print(f'visitor fg pct = {visitor_fg_pct}')

visitor points = 109.606875
visitor fg3 points = 0.35663812500000003
visitor assist = 24.454375
visitor rebounds = 43.8015625
visitor fg pct = 0.45162500000000005

In [147]:
print(f'home points = {home_pts}')
print(f'home fg3 points = {home_fg3_pct}')
print(f'home assist = {home_ast}')
print(f'home rebounds = {home_reb}')
print(f'home fg pct = {home_fg_pct}')

home points = 108.69562499999999
home fg3 points = 0.34303937500000004
home assist = 24.738125
home rebounds = 44.467187499999994
home fg pct = 0.44587499999999997

In [ ]:
home_df2 = home_df2.groupby()

In [150]:
playoffs_df

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS,VISITOR_ABBR,HOME_ABBR
0,2020-08-19,41900112,Final,1610612761,1610612751,2019,1610612761,104.0,0.437,0.679,...,1610612751,99.0,0.388,0.704,0.341,25.0,46.0,1,BKN,TOR
1,2020-08-19,41900162,Final,1610612743,1610612762,2019,1610612743,105.0,0.457,0.783,...,1610612762,124.0,0.517,0.824,0.455,32.0,36.0,0,UTA,DEN
2,2020-08-19,41900122,Final,1610612738,1610612755,2019,1610612738,128.0,0.512,0.724,...,1610612755,101.0,0.418,0.811,0.238,21.0,38.0,1,PHI,BOS
3,2020-08-19,41900152,Final,1610612746,1610612742,2019,1610612746,114.0,0.440,0.769,...,1610612742,127.0,0.500,0.703,0.448,25.0,49.0,0,DAL,LAC
4,2020-08-18,41900101,Final,1610612749,1610612753,2019,1610612749,110.0,0.433,0.643,...,1610612753,122.0,0.494,0.947,0.390,29.0,48.0,0,ORL,MIL
5,2020-08-18,41900131,Final,1610612754,1610612748,2019,1610612754,101.0,0.474,0.864,...,1610612748,113.0,0.494,0.800,0.371,22.0,35.0,0,MIA,IND
6,2020-08-18,41900171,Final,1610612745,1610612760,2019,1610612745,123.0,0.483,0.895,...,1610612760,108.0,0.440,0.840,0.371,22.0,46.0,1,OKC,HOU
7,2020-08-18,41900141,Final,1610612747,1610612757,2019,1610612747,93.0,0.351,0.645,...,1610612757,100.0,0.392,0.758,0.382,18.0,50.0,0,POR,LAL

In [151]:
average_playoffs_df_columns = ['DATE', 'HOME_ABBR', 'VISITOR_ABBR', 'MARGIN', 'PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away' ]

In [156]:
average_playoffs_df = pd.DataFrame(columns=average_playoffs_df_columns)
#initialize empty dataframe

In [159]:
for ind in playoffs_df.index:
    home_team_abbr = playoffs_df['HOME_ABBR'][ind]
    visitor_team_abbr = playoffs_df['VISITOR_ABBR'][ind]
    #trying to gather something more
    home_df2= df_m.loc[df_m['HOME_ABBR'] == home_team_abbr]
    home_as_visitor_df2 = df_m.loc[df_m['VISITOR_ABBR'] == home_team_abbr]
    home_df2_length = len(home_df2)
    home_as_visitor_df2_length = len(home_as_visitor_df2)
#might consider later in the weighted average
    home_df2 = home_df2.groupby(['HOME_ABBR']).mean()
    home_df2 = home_df2[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]
    home_as_visitor_df2 = home_as_visitor_df2.groupby(['VISITOR_ABBR']).mean()
    home_as_visitor_df2 = home_as_visitor_df2[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]
    home_pts = 0.75 * home_df2.iloc[0,0] + 0.25 * home_as_visitor_df2.iloc[0,1]
    #home_pts
    home_fg3_pct = 0.75 * home_df2.iloc[0,4] + 0.25 * home_as_visitor_df2.iloc[0,9]
    home_ast = 0.75 * home_df2.iloc[0,5] + 0.25 * home_as_visitor_df2.iloc[0,10]
    home_reb = 0.75 * home_df2.iloc[0,6] + 0.25 * home_as_visitor_df2.iloc[0,11]
    home_fg_pct = 0.75 * home_df2.iloc[0,2] + 0.25 * home_as_visitor_df2.iloc[0,7]
 #trying to gather something more
    visitor_df2= df_m.loc[df_m['VISITOR_ABBR'] == visitor_team_abbr]
    visitor_as_home_df2 = df_m.loc[df_m['HOME_ABBR'] == visitor_team_abbr]
    visitor_df2_length = len(visitor_df2)
    visitor_as_home_df2_length = len(visitor_as_home_df2)
#might consider later in the weighted average
    visitor_df2 = visitor_df2.groupby(['VISITOR_ABBR']).mean()
    visitor_df2 = visitor_df2[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]
    visitor_as_home_df2 = visitor_as_home_df2.groupby(['HOME_ABBR']).mean()
    visitor_as_home_df2 = visitor_as_home_df2[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]
    visitor_pts = 0.75 * visitor_df2.iloc[0,0] + 0.25 * visitor_as_home_df2.iloc[0,1]
#visitor_pts
    visitor_fg3_pct = 0.75 * visitor_df2.iloc[0,4] + 0.25 * visitor_as_home_df2.iloc[0,9]
    visitor_ast = 0.75 * visitor_df2.iloc[0,5] + 0.25 * visitor_as_home_df2.iloc[0,10]
    visitor_reb = 0.75 * visitor_df2.iloc[0,6] + 0.25 * visitor_as_home_df2.iloc[0,11]
    visitor_fg_pct = 0.75 * visitor_df2.iloc[0,2] + 0.25 * visitor_as_home_df2.iloc[0,7]

NameError: name 'visitor_as_visitor_df2' is not defined

In [130]:
for ind in playoffs_df.index:
    home_team_id = playoffs_df['HOME_TEAM_ID'][ind]
    away_team_id = playoffs_df['VISITOR_TEAM_ID'][ind]
    df2 = df_m.loc[df_m['HOME_TEAM_ID'] == home_team_id]
    df2 = df2.head(30)
    df2 = df2.reset_index(drop=True)
    average_home = df2.groupby(['HOME_TEAM_ID'])
    home_df = average_home.mean()
    home_df = home_df[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]
    df3 = df_m.loc[df_m['VISITOR_TEAM_ID'] == away_team_id]
    df3 = df3.head(30)
    df3 = df3.reset_index(drop=True)
    average_away = df3.groupby(['VISITOR_TEAM_ID'])
    away_df = average_away.mean()
    away_df = away_df[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]
    empty_ = []
    empty_.append(home_df.iloc[0,0])
    empty_.append(away_df.iloc[0,1])
    empty_.append(home_df.iloc[0,2])
    empty_.append(home_df.iloc[0,3])
    empty_.append(home_df.iloc[0,4])
    empty_.append(home_df.iloc[0,5])
    empty_.append(home_df.iloc[0,6])
    empty_.append(away_df.iloc[0,7])
    empty_.append(away_df.iloc[0,8])
    empty_.append(away_df.iloc[0,9])
    empty_.append(away_df.iloc[0,10])
    empty_.append(away_df.iloc[0,11])
    length_of_df = len(home_away_df)
    home_away_df.loc[length_of_df] = empty_

In [131]:
home_away_df['HOME_TEAM_WINS'] = playoffs_df['HOME_TEAM_WINS']

In [132]:
home_away_df

,PTS_home,PTS_away,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,112.413793,111.407407,0.456103,0.802655,0.371241,24.965517,46.413793,0.432630,0.762444,0.332222,24.444444,48.407407,1
1,112.344828,114.923077,0.487586,0.767862,0.353414,27.517241,43.620690,0.484000,0.781808,0.385192,22.769231,44.461538,0
2,115.466667,107.678571,0.474967,0.785333,0.375533,24.266667,44.633333,0.447214,0.743786,0.351464,24.428571,44.821429,1
3,116.760000,114.933333,0.467840,0.785920,0.390000,24.720000,47.640000,0.459367,0.780133,0.363867,24.100000,47.800000,0
4,119.407407,110.066667,0.479630,0.742630,0.370185,26.925926,51.592593,0.454767,0.764467,0.360000,24.433333,43.333333,0
5,110.629630,107.500000,0.482074,0.773444,0.363222,26.851852,42.740741,0.454367,0.788000,0.360900,24.100000,43.466667,0
6,116.814815,109.428571,0.448852,0.776296,0.335481,22.074074,44.407407,0.462464,0.779714,0.353179,21.142857,43.178571,1
7,115.346154,111.851852,0.482231,0.729885,0.351500,25.576923,46.500000,0.458000,0.786852,0.345259,20.259259,42.814815,0

In [133]:
home_away_df.to_csv('imported_predicted_df.csv', index=False)

Compile the code here:
```python
df2 = df_m.loc[df_m['HOME_TEAM_ID'] == number]
df2 = df2.head(10)
df2 = df2.reset_index(drop=True)
average_home = df2.groupby(['HOME_TEAM_ID'])
home_df = average_home.mean()
home_df = home_df[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]

df3 = df_m.loc[df_m['VISITOR_TEAM_ID'] == number]
df3 = df3.head(10)
df3 = df3.reset_index(drop=True)
average_away = df3.groupby(['VISITOR_TEAM_ID'])
away_df = average_away.mean()
away_df = away_df[['PTS_home', 'PTS_away', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home',
       'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away']]

empty_ = []
empty_.append(home_df.iloc[0,0])
empty_.append(away_df.iloc[0,1])
empty_.append(home_df.iloc[0,2])
empty_.append(home_df.iloc[0,3])
empty_.append(home_df.iloc[0,4])
empty_.append(home_df.iloc[0,5])
empty_.append(home_df.iloc[0,6])
empty_.append(away_df.iloc[0,7])
empty_.append(away_df.iloc[0,8])
empty_.append(away_df.iloc[0,9])
empty_.append(away_df.iloc[0,10])
empty_.append(away_df.iloc[0,11])

length_of_df = len(home_away_df)
home_away_df.loc[length_of_df] = empty_

```

Rinse and repeat

You want to select on a date.