In [3]:
pwd

'/Users/stanleytan/Documents/ucb/ucb_/33-prev_projects/stack/4-Project/inclass/3rd_project_tied_4th/first_step/machine_learning_nba/1-webscraper'

In [4]:
import pandas as pd
box_score_prev = pd.read_csv('scraped_box_scores/03_01_box_score.csv')

In [5]:
box_score_prev

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,2021-10-19,MIL,BRK,127,104,23,1,0.457,0.778,0.378,25,54,0.440,0.565,0.531,19,44
1,2021-10-19,LAL,GSW,114,121,-7,0,0.474,0.474,0.357,21,45,0.441,0.833,0.359,30,50
2,2021-10-20,CHO,IND,123,122,1,1,0.430,0.667,0.419,29,46,0.467,0.875,0.362,29,51
3,2021-10-20,DET,CHI,88,94,-6,0,0.400,0.769,0.214,17,47,0.430,0.867,0.304,18,48
4,2021-10-20,NYK,BOS,138,134,4,1,0.486,0.704,0.378,27,55,0.410,0.739,0.368,34,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,2022-03-01,BOS,ATL,107,98,9,1,0.470,0.947,0.314,27,47,0.434,0.792,0.226,15,37
916,2022-03-01,TOR,BRK,109,108,1,1,0.456,0.870,0.304,27,48,0.500,0.737,0.400,21,37
917,2022-03-01,HOU,LAC,100,113,-13,0,0.396,0.647,0.333,21,45,0.438,0.941,0.419,24,55
918,2022-03-01,MIN,GSW,129,114,15,1,0.528,0.826,0.400,27,42,0.456,0.864,0.289,26,40
919,2022-03-01,LAL,DAL,104,109,-5,0,0.451,0.800,0.412,22,37,0.500,0.630,0.286,24,45

In [6]:
user_input = input("Using the previous box_scores to get the next set of boxscores: \
see NBA schedule in the binder")

Using the previous box_scores to get the next set of boxscores: see NBA schedule in the binder

In [23]:
# # adding winning_percentage which is unnecessary

# team_to_abbreviation = {
#     "ATLANTA HAWKS" : "ATL",
#     "ST. LOUIS HAWKS" : "SLH",
#     "MILWAUKEE HAWKS" : "MIL",
#     "TRI-CITIES BLACKHAWKS" : "TCB",
#     "BOSTON CELTICS" : "BOS",
#     "BROOKLYN NETS" : "BRK",
#     "NEW JERSEY NETS" : "NJN",
#     "CHICAGO BULLS" : "CHI",
#     "CHARLOTTE HORNETS": "CHO",
#     "CHARLOTTE BOBCATS" : "CHA",
#     "CLEVELAND CAVALIERS": "CLE",
#     "DALLAS MAVERICKS" : "DAL",
#     "DENVER NUGGETS" : "DEN",
#     "DETROIT PISTONS" : "DET",
#     "FORT WAYNE PISTONS" : "FWP",
#     "GOLDEN STATE WARRIORS" : "GSW",
#     "SAN FRANCISCO WARRIORS" : "SFW",
#     "PHILADELPHIA WARRIORS" : "PHI",
#     "HOUSTON ROCKETS" : "HOU",
#     "INDIANA PACERS" : "IND",
#     "LOS ANGELES CLIPPERS" : "LAC",
#     "SAN DIEGO CLIPPERS" : "SDC",
#     "BUFFALO BRAVES" : "BUF",
#     "LOS ANGELES LAKERS" : "LAL",
#     "MINNEAPOLIS LAKERS" : "MIN",
#     "MEMPHIS GRIZZLIES" : "MEM",
#     "VANCOUVER GRIZZLIES" : 'VAN',
#     "MIAMI HEAT" : "MIA",
#     "MILWAUKEE BUCKS" : "MIL",
#     "MINNESOTA TIMBERWOLVES" : "MIN",
#     "NEW ORLEANS PELICANS" : "NOP",
#     "NEW ORLEANS/OKLAHOMA CITY HORNETS" : "NOK",
#     "NEW ORLEANS HORNETS" : "NOH",
#     "NEW YORK KNICKS" : "NYK",
#     "OKLAHOMA CITY THUNDER" : "OKC",
#     "SEATTLE SUPERSONICS" : "SEA",
#     "ORLANDO MAGIC" : "ORL",
#     "PHILADELPHIA 76ERS" : "PHI",
#     "SYRACUSE NATIONALS" : "SYR",
#     "PHOENIX SUNS" : "PHO",
#     "PORTLAND TRAIL BLAZERS" : "POR",
#     "SACRAMENTO KINGS" : "SAC",
#     "KANSAS CITY KINGS" : "KCK",
#     "KANSAS CITY-OMAHA KINGS" : "KCK",
#     "CINCINNATI ROYALS" : "CIN",
#     "ROCHESTER ROYALS" : "ROR",
#     "SAN ANTONIO SPURS" : "SAS",
#     "TORONTO RAPTORS" : "TOR",
#     "UTAH JAZZ" : "UTA",
#     "NEW ORLEANS JAZZ" : "NOJ",
#     "WASHINGTON WIZARDS" : "WAS",
#     "WASHINGTON BULLETS" : "WAS",
#     "CAPITAL BULLETS" : "CAP",
#     "BALTIMORE BULLETS" : "BAL",
#     "CHICAGO ZEPHYRS" : "CHI",
#     "CHICAGO PACKERS" : "CHI",
#     "ANDERSON PACKERS" : "AND",
#     "CHICAGO STAGS" : "CHI",
#     "INDIANAPOLIS OLYMPIANS" : "IND",
#     "SHEBOYGAN RED SKINS" : "SRS",
#     "ST. LOUIS BOMBERS" : "SLB",
#     "WASHINGTON CAPITOLS" : "WAS",
#     "WATERLOO HAWKS" : "WAT"
# }
# test_ = pd.DataFrame.from_dict(team_to_abbreviation.items())
# list_ = test_[1].tolist()
# wins_ = dict.fromkeys(list_, 0)
# lost_ = dict.fromkeys(list_, 0)

# # adding winning percentage for another
# # df = pd.read_csv('old_data/abbr_games.csv')

# box_score_prev["DATE"]= pd.to_datetime(box_score_prev["DATE"])
# box_score_prev['PTS_home'] = pd.to_numeric(box_score_prev['PTS_home'])
# box_score_prev['PTS_away'] = pd.to_numeric(box_score_prev['PTS_away'])
# box_score_prev['MARGIN'] = pd.to_numeric(box_score_prev['MARGIN'])
# box_score_prev['HOME_TEAM_WINS'] = pd.to_numeric(box_score_prev['HOME_TEAM_WINS'])
# box_score_prev['FG_PCT_home'] = pd.to_numeric(box_score_prev['FG_PCT_home'])
# box_score_prev['FT_PCT_home'] = pd.to_numeric(box_score_prev['FT_PCT_home'])
# box_score_prev['FG3_PCT_home'] = pd.to_numeric(box_score_prev['FG3_PCT_home'])
# box_score_prev['AST_home'] = pd.to_numeric(box_score_prev['AST_home'])
# box_score_prev['REB_home'] = pd.to_numeric(box_score_prev['REB_home'])
# box_score_prev['FG_PCT_away'] = pd.to_numeric(box_score_prev['FG_PCT_away'])
# box_score_prev['FT_PCT_away'] = pd.to_numeric(box_score_prev['FT_PCT_away'])
# box_score_prev['FG3_PCT_away'] = pd.to_numeric(box_score_prev['FG3_PCT_away'])
# box_score_prev['AST_away'] = pd.to_numeric(box_score_prev['AST_away'])
# box_score_prev['REB_away'] = pd.to_numeric(box_score_prev['REB_away'])

# box_score_prev = box_score_prev.reset_index(drop=True)

# home_winning_percentage_list = []
# visitor_winning_percentage_list = []
# for ind in box_score_prev.index:
#     home_abbr = box_score_prev.loc[ind]['HOME_ABBR']
#     visitor_abbr = box_score_prev.loc[ind]['VISITOR_ABBR']
#     home_team_wins = box_score_prev.loc[ind]['HOME_TEAM_WINS']
#     if home_team_wins > 0:
#         wins_[home_abbr] += 1
#         lost_[visitor_abbr] += 1
#     else:
#         lost_[home_abbr] += 1
#         wins_[visitor_abbr] += 1
#     total_games_home_abbr = wins_[home_abbr] + lost_[home_abbr]
#     total_games_visitor_abbr = wins_[visitor_abbr] + lost_[visitor_abbr]
#     home_winning_percentage = wins_[home_abbr] / total_games_home_abbr
#     visitor_winning_percentage = wins_[visitor_abbr] / total_games_visitor_abbr
#     home_winning_percentage_list.append(home_winning_percentage)
#     visitor_winning_percentage_list.append(visitor_winning_percentage)
# box_score_prev['home_winning_percentage'] = home_winning_percentage_list
# box_score_prev['visitor_winning_percentage'] = visitor_winning_percentage_list

In [43]:
box_score_prev

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,2021-10-19,MIL,BRK,127,104,23,1,0.457,0.778,0.378,25,54,0.440,0.565,0.531,19,44
1,2021-10-19,LAL,GSW,114,121,-7,0,0.474,0.474,0.357,21,45,0.441,0.833,0.359,30,50
2,2021-10-20,CHO,IND,123,122,1,1,0.430,0.667,0.419,29,46,0.467,0.875,0.362,29,51
3,2021-10-20,DET,CHI,88,94,-6,0,0.400,0.769,0.214,17,47,0.430,0.867,0.304,18,48
4,2021-10-20,NYK,BOS,138,134,4,1,0.486,0.704,0.378,27,55,0.410,0.739,0.368,34,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,2022-02-24,CHI,ATL,112,108,4,1,0.488,0.815,0.296,16,43,0.423,0.667,0.286,20,45
886,2022-02-24,MIN,MEM,119,114,5,1,0.462,0.680,0.381,26,42,0.388,0.725,0.290,25,59
887,2022-02-24,OKC,PHO,104,124,-20,0,0.473,0.909,0.194,22,42,0.535,0.905,0.382,32,43
888,2022-02-24,POR,GSW,95,132,-37,0,0.397,0.828,0.257,16,31,0.511,0.844,0.366,36,46
889,2022-02-24,SAC,DEN,110,128,-18,0,0.500,0.833,0.310,25,34,0.558,0.850,0.429,30,39

In [7]:
box_score_prev["DATE"]= pd.to_datetime(box_score_prev["DATE"])
box_score_prev['PTS_home'] = pd.to_numeric(box_score_prev['PTS_home'])
box_score_prev['PTS_away'] = pd.to_numeric(box_score_prev['PTS_away'])
box_score_prev['MARGIN'] = pd.to_numeric(box_score_prev['MARGIN'])
box_score_prev['HOME_TEAM_WINS'] = pd.to_numeric(box_score_prev['HOME_TEAM_WINS'])
box_score_prev['FG_PCT_home'] = pd.to_numeric(box_score_prev['FG_PCT_home'])
box_score_prev['FT_PCT_home'] = pd.to_numeric(box_score_prev['FT_PCT_home'])
box_score_prev['FG3_PCT_home'] = pd.to_numeric(box_score_prev['FG3_PCT_home'])
box_score_prev['AST_home'] = pd.to_numeric(box_score_prev['AST_home'])
box_score_prev['REB_home'] = pd.to_numeric(box_score_prev['REB_home'])
box_score_prev['FG_PCT_away'] = pd.to_numeric(box_score_prev['FG_PCT_away'])
box_score_prev['FT_PCT_away'] = pd.to_numeric(box_score_prev['FT_PCT_away'])
box_score_prev['FG3_PCT_away'] = pd.to_numeric(box_score_prev['FG3_PCT_away'])
box_score_prev['AST_away'] = pd.to_numeric(box_score_prev['AST_away'])
box_score_prev['REB_away'] = pd.to_numeric(box_score_prev['REB_away'])

In [5]:
box_score_prev

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,2021-10-19,MIL,BRK,127,104,23,1,0.457,0.778,0.378,25,54,0.440,0.565,0.531,19,44
1,2021-10-19,LAL,GSW,114,121,-7,0,0.474,0.474,0.357,21,45,0.441,0.833,0.359,30,50
2,2021-10-20,CHO,IND,123,122,1,1,0.430,0.667,0.419,29,46,0.467,0.875,0.362,29,51
3,2021-10-20,DET,CHI,88,94,-6,0,0.400,0.769,0.214,17,47,0.430,0.867,0.304,18,48
4,2021-10-20,NYK,BOS,138,134,4,1,0.486,0.704,0.378,27,55,0.410,0.739,0.368,34,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902,2022-02-27,CHO,DET,126,127,-1,0,0.506,0.676,0.419,25,46,0.455,0.722,0.350,30,54
903,2022-02-27,HOU,LAC,98,99,-1,0,0.380,0.611,0.405,26,37,0.442,0.714,0.324,18,59
904,2022-02-27,GSW,DAL,101,107,-6,0,0.429,0.600,0.282,27,44,0.500,0.800,0.382,16,45
905,2022-02-27,POR,DEN,92,124,-32,0,0.374,0.692,0.167,22,42,0.512,0.774,0.324,28,55
906,2022-02-27,LAL,NOP,95,123,-28,0,0.417,0.900,0.206,15,38,0.511,0.640,0.433,29,51

In [8]:
schedule_df = pd.read_csv('schedule_2022.csv')

In [18]:
schedule_df

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS
0,2021-10-19,Brooklyn Nets,104.0,Milwaukee Bucks,127.0
1,2021-10-19,Golden State Warriors,121.0,Los Angeles Lakers,114.0
2,2021-10-20,Indiana Pacers,122.0,Charlotte Hornets,123.0
3,2021-10-20,Chicago Bulls,94.0,Detroit Pistons,88.0
4,2021-10-20,Boston Celtics,134.0,New York Knicks,138.0
...,...,...,...,...,...
1225,2022-04-10,Los Angeles Lakers,0.0,Denver Nuggets,0.0
1226,2022-04-10,San Antonio Spurs,0.0,Dallas Mavericks,0.0
1227,2022-04-10,Milwaukee Bucks,0.0,Cleveland Cavaliers,0.0
1228,2022-04-10,Washington Wizards,0.0,Charlotte Hornets,0.0
1229,2022-04-10,Indiana Pacers,0.0,Brooklyn Nets,0.0

In [19]:
user_input = input('required to get the dates to add to the box_scores')

required to get the dates to add to the box_scores

In [9]:
schedule_df = schedule_df.loc[schedule_df['DATE'] == '2022-03-02']

In [10]:
team_to_abbreviation = {
    "ATLANTA HAWKS" : "ATL",
    "ST. LOUIS HAWKS" : "SLH",
    "MILWAUKEE HAWKS" : "MIL",
    "TRI-CITIES BLACKHAWKS" : "TCB",
    "BOSTON CELTICS" : "BOS",
    "BROOKLYN NETS" : "BRK",
    "NEW JERSEY NETS" : "NJN",
    "CHICAGO BULLS" : "CHI",
    "CHARLOTTE HORNETS": "CHO",
    "CHARLOTTE BOBCATS" : "CHA",
    "CLEVELAND CAVALIERS": "CLE",
    "DALLAS MAVERICKS" : "DAL",
    "DENVER NUGGETS" : "DEN",
    "DETROIT PISTONS" : "DET",
    "FORT WAYNE PISTONS" : "FWP",
    "GOLDEN STATE WARRIORS" : "GSW",
    "SAN FRANCISCO WARRIORS" : "SFW",
    "PHILADELPHIA WARRIORS" : "PHI",
    "HOUSTON ROCKETS" : "HOU",
    "INDIANA PACERS" : "IND",
    "LOS ANGELES CLIPPERS" : "LAC",
    "SAN DIEGO CLIPPERS" : "SDC",
    "BUFFALO BRAVES" : "BUF",
    "LOS ANGELES LAKERS" : "LAL",
    "MINNEAPOLIS LAKERS" : "MIN",
    "MEMPHIS GRIZZLIES" : "MEM",
    "VANCOUVER GRIZZLIES" : 'VAN',
    "MIAMI HEAT" : "MIA",
    "MILWAUKEE BUCKS" : "MIL",
    "MINNESOTA TIMBERWOLVES" : "MIN",
    "NEW ORLEANS PELICANS" : "NOP",
    "NEW ORLEANS/OKLAHOMA CITY HORNETS" : "NOK",
    "NEW ORLEANS HORNETS" : "NOH",
    "NEW YORK KNICKS" : "NYK",
    "OKLAHOMA CITY THUNDER" : "OKC",
    "SEATTLE SUPERSONICS" : "SEA",
    "ORLANDO MAGIC" : "ORL",
    "PHILADELPHIA 76ERS" : "PHI",
    "SYRACUSE NATIONALS" : "SYR",
    "PHOENIX SUNS" : "PHO",
    "PORTLAND TRAIL BLAZERS" : "POR",
    "SACRAMENTO KINGS" : "SAC",
    "KANSAS CITY KINGS" : "KCK",
    "KANSAS CITY-OMAHA KINGS" : "KCK",
    "CINCINNATI ROYALS" : "CIN",
    "ROCHESTER ROYALS" : "ROR",
    "SAN ANTONIO SPURS" : "SAS",
    "TORONTO RAPTORS" : "TOR",
    "UTAH JAZZ" : "UTA",
    "NEW ORLEANS JAZZ" : "NOJ",
    "WASHINGTON WIZARDS" : "WAS",
    "WASHINGTON BULLETS" : "WAS",
    "CAPITAL BULLETS" : "CAP",
    "BALTIMORE BULLETS" : "BAL",
    "CHICAGO ZEPHYRS" : "CHI",
    "CHICAGO PACKERS" : "CHI",
    "ANDERSON PACKERS" : "AND",
    "CHICAGO STAGS" : "CHI",
    "INDIANAPOLIS OLYMPIANS" : "IND",
    "SHEBOYGAN RED SKINS" : "SRS",
    "ST. LOUIS BOMBERS" : "SLB",
    "WASHINGTON CAPITOLS" : "WAS",
    "WATERLOO HAWKS" : "WAT"
}

schedule_df['HOME_ABBR'] = 0
schedule_df['VISITOR_ABBR'] = 0

for ind in schedule_df.index: 
    schedule_df['VISITOR'][ind] = schedule_df['VISITOR'][ind].upper()
    schedule_df['HOME'][ind] =schedule_df['HOME'][ind].upper()
    schedule_df['HOME_ABBR'][ind] = team_to_abbreviation[schedule_df['HOME'][ind]]
    schedule_df['VISITOR_ABBR'][ind] = team_to_abbreviation[schedule_df['VISITOR'][ind]]

<ipython-input-10-378933caafdb>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule_df['VISITOR'][ind] = schedule_df['VISITOR'][ind].upper()
<ipython-input-10-378933caafdb>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule_df['HOME'][ind] =schedule_df['HOME'][ind].upper()
<ipython-input-10-378933caafdb>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule_df['HOME_ABBR'][ind] = team_to_abbreviation[schedule_df['HOME'][ind]]
/Users/stanleytan/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
<ipython-input-10-378933caafdb>:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule_df['VISITOR_ABBR'][ind] = team_to_abbreviation[schedule_df['VISITOR'][ind]]

In [22]:
schedule_df

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,HOME_ABBR,VISITOR_ABBR
921,2022-03-01,DETROIT PISTONS,0.0,WASHINGTON WIZARDS,0.0,WAS,DET
922,2022-03-01,ATLANTA HAWKS,0.0,BOSTON CELTICS,0.0,BOS,ATL
923,2022-03-01,BROOKLYN NETS,0.0,TORONTO RAPTORS,0.0,TOR,BRK
924,2022-03-01,LOS ANGELES CLIPPERS,0.0,HOUSTON ROCKETS,0.0,HOU,LAC
925,2022-03-01,GOLDEN STATE WARRIORS,0.0,MINNESOTA TIMBERWOLVES,0.0,MIN,GSW
926,2022-03-01,DALLAS MAVERICKS,0.0,LOS ANGELES LAKERS,0.0,LAL,DAL

In [11]:
box_score_columns = box_score_columns = [ 'DATE', 'HOME_ABBR', 'VISITOR_ABBR', 'PTS_home', 'PTS_away', 'MARGIN', 'HOME_TEAM_WINS', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away', 'REB_away']
box_score_df = pd.DataFrame(columns=box_score_columns)


from basketball_reference_scraper.box_scores import get_box_scores

import time
for ind in schedule_df.index:
    date_1 = schedule_df.loc[ind]['DATE']
    home_1 = schedule_df.loc[ind]['HOME_ABBR']
    visitor_1 = schedule_df.loc[ind]['VISITOR_ABBR']
    dict_ = get_box_scores(date_1, visitor_1, home_1, period='GAME', stat_type='BASIC')
    home_df = dict_[home_1]
    visitor_df = dict_[visitor_1]
    #id_ = schedule_df.loc[ind]['ID']
    #unsure why the ID is required
    home_pts = home_df.loc[home_df['PLAYER'] == 'Team Totals']['PTS'].iloc[0]
    visitor_pts = visitor_df.loc[visitor_df['PLAYER'] == 'Team Totals']['PTS'].iloc[0]
    margin_ = int(home_pts) - int(visitor_pts)
    if margin_ > 0:
        home_team_wins = 1
    else:
        home_team_wins = 0
    home_fg_pct = home_df.loc[home_df['PLAYER'] == 'Team Totals']['FG%'].iloc[0]
    home_ft_pct = home_df.loc[home_df['PLAYER'] == 'Team Totals']['FT%'].iloc[0]
    home_fg3_pct = home_df.loc[home_df['PLAYER'] == 'Team Totals']['3P%'].iloc[0]
    home_ast = home_df.loc[home_df['PLAYER'] == 'Team Totals']['AST'].iloc[0]
    home_reb = home_df.loc[home_df['PLAYER'] == 'Team Totals']['TRB'].iloc[0]
    visitor_fg_pct = visitor_df.loc[visitor_df['PLAYER'] == 'Team Totals']['FG%'].iloc[0]
    visitor_ft_pct = visitor_df.loc[visitor_df['PLAYER'] == 'Team Totals']['FT%'].iloc[0]
    visitor_fg3_pct = visitor_df.loc[visitor_df['PLAYER'] == 'Team Totals']['3P%'].iloc[0]
    visitor_ast = visitor_df.loc[visitor_df['PLAYER'] == 'Team Totals']['AST'].iloc[0]
    visitor_reb = visitor_df.loc[visitor_df['PLAYER'] == 'Team Totals']['TRB'].iloc[0]
    empty_ = []
    #empty_.append(id_)
#ID unsure why that is required
    empty_.append(date_1)
#DATE
    empty_.append(home_1)
#home abbr
    empty_.append(visitor_1)
#visito abbr
    empty_.append(home_pts)
#home pints
    empty_.append(visitor_pts)
#away points
    empty_.append(margin_)
#margin
    empty_.append(home_team_wins)
#HOME_TEAM_WINS
    empty_.append(home_fg_pct)
#FG_PCT
    empty_.append(home_ft_pct)
#FT_PCT
    empty_.append(home_fg3_pct)
#FG3_PCT
    empty_.append(home_ast)
#AST
    empty_.append(home_reb)
#REBOUNDS
    empty_.append(visitor_fg_pct)
#FG_PCT
    empty_.append(visitor_ft_pct)
#FT_PCT
    empty_.append(visitor_fg3_pct)
#FG3
    empty_.append(visitor_ast)
#AST
    empty_.append(visitor_reb)
#REBOUNDS
    length_of_df = len(box_score_df)
    box_score_df.loc[length_of_df] = empty_
    print(empty_)

['2022-03-02', 'CLE', 'CHO', '98', '119', -21, 0, '.468', '.667', '.323', '21', '37', '.506', '.727', '.447', '32', '45']
['2022-03-02', 'ORL', 'IND', '114', '122', -8, 0, '.454', '.800', '.313', '22', '52', '.436', '.800', '.324', '23', '54']
['2022-03-02', 'PHI', 'NYK', '123', '108', 15, 1, '.520', '.848', '.472', '24', '43', '.429', '.688', '.286', '20', '40']
['2022-03-02', 'HOU', 'UTA', '127', '132', -5, 0, '.500', '.667', '.412', '27', '35', '.543', '.708', '.357', '32', '49']
['2022-03-02', 'MIL', 'MIA', '120', '119', 1, 1, '.451', '.889', '.389', '22', '52', '.454', '.833', '.477', '28', '48']
['2022-03-02', 'NOP', 'SAC', '125', '95', 30, 1, '.591', '.833', '.379', '30', '50', '.393', '.680', '.229', '20', '38']
['2022-03-02', 'DEN', 'OKC', '107', '119', -12, 0, '.444', '.882', '.261', '25', '47', '.506', '.714', '.552', '24', '50']
['2022-03-02', 'PHO', 'POR', '120', '90', 30, 1, '.500', '.839', '.389', '32', '46', '.385', '.760', '.355', '22', '35']

In [12]:
box_score_combined = pd.concat([box_score_prev, box_score_df])

In [13]:
box_score_combined["DATE"]= pd.to_datetime(box_score_combined["DATE"])

In [14]:
box_score_combined.to_csv('scraped_box_scores/03_02_box_score.csv', index=False)

In [15]:
box_score_combined

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,2021-10-19,MIL,BRK,127,104,23,1,0.457,0.778,0.378,25,54,0.44,0.565,0.531,19,44
1,2021-10-19,LAL,GSW,114,121,-7,0,0.474,0.474,0.357,21,45,0.441,0.833,0.359,30,50
2,2021-10-20,CHO,IND,123,122,1,1,0.43,0.667,0.419,29,46,0.467,0.875,0.362,29,51
3,2021-10-20,DET,CHI,88,94,-6,0,0.4,0.769,0.214,17,47,0.43,0.867,0.304,18,48
4,2021-10-20,NYK,BOS,138,134,4,1,0.486,0.704,0.378,27,55,0.41,0.739,0.368,34,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,2022-03-02,HOU,UTA,127,132,-5,0,.500,.667,.412,27,35,.543,.708,.357,32,49
4,2022-03-02,MIL,MIA,120,119,1,1,.451,.889,.389,22,52,.454,.833,.477,28,48
5,2022-03-02,NOP,SAC,125,95,30,1,.591,.833,.379,30,50,.393,.680,.229,20,38
6,2022-03-02,DEN,OKC,107,119,-12,0,.444,.882,.261,25,47,.506,.714,.552,24,50
7,2022-03-02,PHO,POR,120,90,30,1,.500,.839,.389,32,46,.385,.760,.355,22,35

In [1]:
pwd

'/Users/stanleytan/Documents/ucb/ucb_/33-prev_projects/stack/4-Project/inclass/3rd_project_tied_4th/first_step/machine_learning_nba/1-webscraper'

In [28]:
box_score_combined

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
0,2021-10-19,MIL,BRK,127,104,23,1,0.457,0.778,0.378,25,54,0.44,0.565,0.531,19,44
1,2021-10-19,LAL,GSW,114,121,-7,0,0.474,0.474,0.357,21,45,0.441,0.833,0.359,30,50
2,2021-10-20,CHO,IND,123,122,1,1,0.43,0.667,0.419,29,46,0.467,0.875,0.362,29,51
3,2021-10-20,DET,CHI,88,94,-6,0,0.4,0.769,0.214,17,47,0.43,0.867,0.304,18,48
4,2021-10-20,NYK,BOS,138,134,4,1,0.486,0.704,0.378,27,55,0.41,0.739,0.368,34,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,2022-03-01,BOS,ATL,107,98,9,1,.470,.947,.314,27,47,.434,.792,.226,15,37
2,2022-03-01,TOR,BRK,109,108,1,1,.456,.870,.304,27,48,.500,.737,.400,21,37
3,2022-03-01,HOU,LAC,100,113,-13,0,.396,.647,.333,21,45,.438,.941,.419,24,55
4,2022-03-01,MIN,GSW,129,114,15,1,.528,.826,.400,27,42,.456,.864,.289,26,40
5,2022-03-01,LAL,DAL,104,109,-5,0,.451,.800,.412,22,37,.500,.630,.286,24,45

In [17]:
box_score_combined.loc[box_score_combined['HOME_ABBR'] == 'DET'].tail(10)

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
623,2022-01-14,DET,TOR,103,87,16,1,0.469,0.826,0.296,22,43,0.322,0.769,0.289,18,46
641,2022-01-16,DET,PHO,108,135,-27,0,0.463,0.676,0.36,25,32,0.586,0.733,0.407,30,51
704,2022-01-25,DET,DEN,105,110,-5,0,0.423,0.786,0.333,25,36,0.429,0.871,0.344,25,56
745,2022-01-30,DET,CLE,115,105,10,1,0.462,0.84,0.385,26,48,0.463,0.64,0.382,25,41
758,2022-02-01,DET,NOP,101,111,-10,0,0.488,0.786,0.25,21,35,0.438,0.893,0.286,24,46
774,2022-02-03,DET,MIN,117,128,-11,0,0.44,0.786,0.326,27,45,0.506,0.893,0.441,29,42
781,2022-02-04,DET,BOS,93,102,-9,0,0.327,0.75,0.385,18,56,0.451,0.76,0.321,23,55
824,2022-02-10,DET,MEM,107,132,-25,0,0.436,0.857,0.2,27,40,0.478,0.69,0.5,32,60
831,2022-02-11,DET,CHO,119,141,-22,0,0.471,0.611,0.343,32,45,0.557,0.652,0.429,36,51
883,2022-02-24,DET,CLE,106,103,3,1,0.407,0.893,0.324,23,49,0.442,0.676,0.343,20,42

In [19]:
 box_score_combined.columns

Index(['DATE', 'HOME_ABBR', 'VISITOR_ABBR', 'PTS_home', 'PTS_away', 'MARGIN',
       'HOME_TEAM_WINS', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home',
       'AST_home', 'REB_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away',
       'AST_away', 'REB_away'],
      dtype='object')

In [18]:
# winning percentage

In [20]:
team_to_abbreviation = {
    "ATLANTA HAWKS" : "ATL",
    "ST. LOUIS HAWKS" : "SLH",
    "MILWAUKEE HAWKS" : "MIL",
    "TRI-CITIES BLACKHAWKS" : "TCB",
    "BOSTON CELTICS" : "BOS",
    "BROOKLYN NETS" : "BRK",
    "NEW JERSEY NETS" : "NJN",
    "CHICAGO BULLS" : "CHI",
    "CHARLOTTE HORNETS": "CHO",
    "CHARLOTTE BOBCATS" : "CHA",
    "CLEVELAND CAVALIERS": "CLE",
    "DALLAS MAVERICKS" : "DAL",
    "DENVER NUGGETS" : "DEN",
    "DETROIT PISTONS" : "DET",
    "FORT WAYNE PISTONS" : "FWP",
    "GOLDEN STATE WARRIORS" : "GSW",
    "SAN FRANCISCO WARRIORS" : "SFW",
    "PHILADELPHIA WARRIORS" : "PHI",
    "HOUSTON ROCKETS" : "HOU",
    "INDIANA PACERS" : "IND",
    "LOS ANGELES CLIPPERS" : "LAC",
    "SAN DIEGO CLIPPERS" : "SDC",
    "BUFFALO BRAVES" : "BUF",
    "LOS ANGELES LAKERS" : "LAL",
    "MINNEAPOLIS LAKERS" : "MIN",
    "MEMPHIS GRIZZLIES" : "MEM",
    "VANCOUVER GRIZZLIES" : 'VAN',
    "MIAMI HEAT" : "MIA",
    "MILWAUKEE BUCKS" : "MIL",
    "MINNESOTA TIMBERWOLVES" : "MIN",
    "NEW ORLEANS PELICANS" : "NOP",
    "NEW ORLEANS/OKLAHOMA CITY HORNETS" : "NOK",
    "NEW ORLEANS HORNETS" : "NOH",
    "NEW YORK KNICKS" : "NYK",
    "OKLAHOMA CITY THUNDER" : "OKC",
    "SEATTLE SUPERSONICS" : "SEA",
    "ORLANDO MAGIC" : "ORL",
    "PHILADELPHIA 76ERS" : "PHI",
    "SYRACUSE NATIONALS" : "SYR",
    "PHOENIX SUNS" : "PHO",
    "PORTLAND TRAIL BLAZERS" : "POR",
    "SACRAMENTO KINGS" : "SAC",
    "KANSAS CITY KINGS" : "KCK",
    "KANSAS CITY-OMAHA KINGS" : "KCK",
    "CINCINNATI ROYALS" : "CIN",
    "ROCHESTER ROYALS" : "ROR",
    "SAN ANTONIO SPURS" : "SAS",
    "TORONTO RAPTORS" : "TOR",
    "UTAH JAZZ" : "UTA",
    "NEW ORLEANS JAZZ" : "NOJ",
    "WASHINGTON WIZARDS" : "WAS",
    "WASHINGTON BULLETS" : "WAS",
    "CAPITAL BULLETS" : "CAP",
    "BALTIMORE BULLETS" : "BAL",
    "CHICAGO ZEPHYRS" : "CHI",
    "CHICAGO PACKERS" : "CHI",
    "ANDERSON PACKERS" : "AND",
    "CHICAGO STAGS" : "CHI",
    "INDIANAPOLIS OLYMPIANS" : "IND",
    "SHEBOYGAN RED SKINS" : "SRS",
    "ST. LOUIS BOMBERS" : "SLB",
    "WASHINGTON CAPITOLS" : "WAS",
    "WATERLOO HAWKS" : "WAT"
}
test_ = pd.DataFrame.from_dict(team_to_abbreviation.items())
list_ = test_[1].tolist()
wins_ = dict.fromkeys(list_, 0)
lost_ = dict.fromkeys(list_, 0)

# adding winning percentage for another
# df = pd.read_csv('old_data/abbr_games.csv')

box_score_combined["DATE"]= pd.to_datetime(box_score_combined["DATE"])
box_score_combined['PTS_home'] = pd.to_numeric(box_score_combined['PTS_home'])
box_score_combined['PTS_away'] = pd.to_numeric(box_score_combined['PTS_away'])
box_score_combined['MARGIN'] = pd.to_numeric(box_score_combined['MARGIN'])
box_score_combined['HOME_TEAM_WINS'] = pd.to_numeric(box_score_combined['HOME_TEAM_WINS'])
box_score_combined['FG_PCT_home'] = pd.to_numeric(box_score_combined['FG_PCT_home'])
box_score_combined['FT_PCT_home'] = pd.to_numeric(box_score_combined['FT_PCT_home'])
box_score_combined['FG3_PCT_home'] = pd.to_numeric(box_score_combined['FG3_PCT_home'])
box_score_combined['AST_home'] = pd.to_numeric(box_score_combined['AST_home'])
box_score_combined['REB_home'] = pd.to_numeric(box_score_combined['REB_home'])
box_score_combined['FG_PCT_away'] = pd.to_numeric(box_score_combined['FG_PCT_away'])
box_score_combined['FT_PCT_away'] = pd.to_numeric(box_score_combined['FT_PCT_away'])
box_score_combined['FG3_PCT_away'] = pd.to_numeric(box_score_combined['FG3_PCT_away'])
box_score_combined['AST_away'] = pd.to_numeric(box_score_combined['AST_away'])
box_score_combined['REB_away'] = pd.to_numeric(box_score_combined['REB_away'])

box_score_combined = box_score_combined.reset_index(drop=True)

home_winning_percentage_list = []
visitor_winning_percentage_list = []
for ind in box_score_combined.index:
    home_abbr = box_score_combined.loc[ind]['HOME_ABBR']
    visitor_abbr = box_score_combined.loc[ind]['VISITOR_ABBR']
    home_team_wins = box_score_combined.loc[ind]['HOME_TEAM_WINS']
    if home_team_wins > 0:
        wins_[home_abbr] += 1
        lost_[visitor_abbr] += 1
    else:
        lost_[home_abbr] += 1
        wins_[visitor_abbr] += 1
    total_games_home_abbr = wins_[home_abbr] + lost_[home_abbr]
    total_games_visitor_abbr = wins_[visitor_abbr] + lost_[visitor_abbr]
    home_winning_percentage = wins_[home_abbr] / total_games_home_abbr
    visitor_winning_percentage = wins_[visitor_abbr] / total_games_visitor_abbr
    home_winning_percentage_list.append(home_winning_percentage)
    visitor_winning_percentage_list.append(visitor_winning_percentage)
box_score_combined['home_winning_percentage'] = home_winning_percentage_list
box_score_combined['visitor_winning_percentage'] = visitor_winning_percentage_list

# adding the winning_percentages to the boxscore

In [21]:
box_score_combined

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,HOME_TEAM_WINS,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,home_winning_percentage,visitor_winning_percentage
0,2021-10-19,MIL,BRK,127,104,23,1,0.457,0.778,0.378,25,54,0.440,0.565,0.531,19,44,1.000000,0.000000
1,2021-10-19,LAL,GSW,114,121,-7,0,0.474,0.474,0.357,21,45,0.441,0.833,0.359,30,50,0.000000,1.000000
2,2021-10-20,CHO,IND,123,122,1,1,0.430,0.667,0.419,29,46,0.467,0.875,0.362,29,51,1.000000,0.000000
3,2021-10-20,DET,CHI,88,94,-6,0,0.400,0.769,0.214,17,47,0.430,0.867,0.304,18,48,0.000000,1.000000
4,2021-10-20,NYK,BOS,138,134,4,1,0.486,0.704,0.378,27,55,0.410,0.739,0.368,34,56,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,2022-03-02,HOU,UTA,127,132,-5,0,0.500,0.667,0.412,27,35,0.543,0.708,0.357,32,49,0.241935,0.639344
924,2022-03-02,MIL,MIA,120,119,1,1,0.451,0.889,0.389,22,52,0.454,0.833,0.477,28,48,0.612903,0.645161
925,2022-03-02,NOP,SAC,125,95,30,1,0.591,0.833,0.379,30,50,0.393,0.680,0.229,20,38,0.419355,0.365079
926,2022-03-02,DEN,OKC,107,119,-12,0,0.444,0.882,0.261,25,47,0.506,0.714,0.552,24,50,0.573770,0.322581
927,2022-03-02,PHO,POR,120,90,30,1,0.500,0.839,0.389,32,46,0.385,0.760,0.355,22,35,0.806452,0.403226

In [22]:
box_score_combined.to_csv('../3-further_analysis/03_03box_score_combined.csv', index=False)