In [2]:
import pandas as pd
diff_df = pd.read_csv('diff_df_feb_24.csv')

In [3]:
grouped_df = pd.read_csv('grouped_feb_24.csv')

In [4]:
diff_df

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,FG_PCT_home,FT_PCT_home,FG3_PCT_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away
0,2022-02-24,DET,CLE,0.975000,-4.262500,5.237500,0.008250,0.043875,0.033300,-0.027850,-0.096113,-0.004075
1,2022-02-24,BRK,BOS,-8.500000,8.300000,-16.800000,-0.026275,-0.006500,-0.090800,0.025300,0.010000,0.060100
2,2022-02-24,CHI,ATL,1.757143,-2.941429,4.698571,0.022857,-0.026150,0.022029,-0.000027,-0.008916,-0.004469
3,2022-02-24,MIN,MEM,1.421429,-3.242857,4.664286,-0.001386,-0.005729,0.014157,-0.025000,0.004500,-0.000679
4,2022-02-24,OKC,PHO,-9.700000,3.800000,-13.500000,-0.038400,-0.031300,-0.015400,-0.008500,-0.028600,-0.001600
5,2022-02-24,POR,GSW,-5.760000,-10.500000,4.740000,-0.023180,-0.057680,-0.021340,-0.004700,-0.043400,-0.077500
6,2022-02-24,SAC,DEN,-4.933333,1.403333,-6.336667,-0.016717,0.013433,-0.041750,-0.000007,0.014913,-0.010133

In [5]:
grouped_df

,DATE,HOME_ABBR,VISITOR_ABBR,PTS_home,PTS_away,MARGIN,FG_PCT_home,FT_PCT_home,FG3_PCT_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away,home_winning_percentage,visitor_winning_percentage,diff_%
0,2022-02-24,DET,CLE,109.4,107.6,1.8,0.4495,0.7835,0.3392,0.4880,0.7338,0.3570,0.215686,0.606061,-0.4
1,2022-02-24,BRK,BOS,108.0,111.7,-3.7,0.4563,0.7949,0.3126,0.4802,0.8170,0.3739,0.500000,0.579439,-0.1
2,2022-02-24,CHI,ATL,120.1,111.4,8.7,0.5225,0.8399,0.3714,0.4548,0.8400,0.3415,0.638095,0.495050,0.1
3,2022-02-24,MIN,MEM,114.0,119.7,-5.7,0.4553,0.7331,0.3466,0.4689,0.6748,0.3206,0.547170,0.710280,-0.2
4,2022-02-24,OKC,PHO,100.8,113.2,-12.4,0.4170,0.7777,0.3204,0.4895,0.7841,0.3181,0.298077,0.836538,-0.5
5,2022-02-24,POR,GSW,105.2,108.5,-3.3,0.4371,0.7272,0.3505,0.4451,0.8052,0.3639,0.411765,0.695238,-0.3
6,2022-02-24,SAC,DEN,117.5,111.9,5.6,0.4846,0.7827,0.3820,0.4732,0.8259,0.3509,0.365385,0.549020,-0.2

In [6]:
date1 = grouped_df['DATE']
home_abbr1 = grouped_df['HOME_ABBR']
visitor_abbr1 = grouped_df['VISITOR_ABBR']
home_winning_percentage = grouped_df['home_winning_percentage']
visitor_winning_percentage = grouped_df['visitor_winning_percentage']
diff = grouped_df['diff_%']

In [8]:
grouped_df = grouped_df.drop('visitor_winning_percentage', 1)

In [11]:
grouped_df

,PTS_home,PTS_away,MARGIN,FG_PCT_home,FT_PCT_home,FG3_PCT_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away
0,109.4,107.6,1.8,0.4495,0.7835,0.3392,0.4880,0.7338,0.3570
1,108.0,111.7,-3.7,0.4563,0.7949,0.3126,0.4802,0.8170,0.3739
2,120.1,111.4,8.7,0.5225,0.8399,0.3714,0.4548,0.8400,0.3415
3,114.0,119.7,-5.7,0.4553,0.7331,0.3466,0.4689,0.6748,0.3206
4,100.8,113.2,-12.4,0.4170,0.7777,0.3204,0.4895,0.7841,0.3181
5,105.2,108.5,-3.3,0.4371,0.7272,0.3505,0.4451,0.8052,0.3639
6,117.5,111.9,5.6,0.4846,0.7827,0.3820,0.4732,0.8259,0.3509

In [10]:
grouped_df = grouped_df.drop('diff_%', 1)

In [7]:
grouped_df = grouped_df.drop('DATE', 1)
grouped_df = grouped_df.drop('HOME_ABBR', 1)
grouped_df = grouped_df.drop('VISITOR_ABBR', 1)
grouped_df = grouped_df.drop('home_winning_percentage', 1)
grouped_df = grouped_df.drop('visitor_winning_percentage', 1)
grouped_df = grouped_df.drop('diff_%', 1)

KeyError: "['visitor_percentage'] not found in axis"

In [13]:
diff_df = diff_df.drop('DATE', 1)
diff_df = diff_df.drop('HOME_ABBR', 1)
diff_df = diff_df.drop('VISITOR_ABBR', 1)

In [14]:
diff_df

,PTS_home,PTS_away,MARGIN,FG_PCT_home,FT_PCT_home,FG3_PCT_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away
0,0.975000,-4.262500,5.237500,0.008250,0.043875,0.033300,-0.027850,-0.096113,-0.004075
1,-8.500000,8.300000,-16.800000,-0.026275,-0.006500,-0.090800,0.025300,0.010000,0.060100
2,1.757143,-2.941429,4.698571,0.022857,-0.026150,0.022029,-0.000027,-0.008916,-0.004469
3,1.421429,-3.242857,4.664286,-0.001386,-0.005729,0.014157,-0.025000,0.004500,-0.000679
4,-9.700000,3.800000,-13.500000,-0.038400,-0.031300,-0.015400,-0.008500,-0.028600,-0.001600
5,-5.760000,-10.500000,4.740000,-0.023180,-0.057680,-0.021340,-0.004700,-0.043400,-0.077500
6,-4.933333,1.403333,-6.336667,-0.016717,0.013433,-0.041750,-0.000007,0.014913,-0.010133

In [15]:
combined_df = diff_df + grouped_df

In [16]:
combined_df

,PTS_home,PTS_away,MARGIN,FG_PCT_home,FT_PCT_home,FG3_PCT_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away
0,110.375000,103.337500,7.037500,0.457750,0.827375,0.372500,0.460150,0.637687,0.352925
1,99.500000,120.000000,-20.500000,0.430025,0.788400,0.221800,0.505500,0.827000,0.434000
2,121.857143,108.458571,13.398571,0.545357,0.813750,0.393429,0.454773,0.831084,0.337031
3,115.421429,116.457143,-1.035714,0.453914,0.727371,0.360757,0.443900,0.679300,0.319921
4,91.100000,117.000000,-25.900000,0.378600,0.746400,0.305000,0.481000,0.755500,0.316500
5,99.440000,98.000000,1.440000,0.413920,0.669520,0.329160,0.440400,0.761800,0.286400
6,112.566667,113.303333,-0.736667,0.467883,0.796133,0.340250,0.473193,0.840813,0.340767

In [17]:
combined_df['DATE'] = date1
combined_df['HOME_ABBR'] = home_abbr1
combined_df['VISITOR_ABBR'] = visitor_abbr1
combined_df['home_winning_percentage'] = home_winning_percentage
combined_df['visitor_winning_percentage'] = visitor_winning_percentage
combined_df['diff_%'] = diff

In [19]:
combined_df.columns

Index(['PTS_home', 'PTS_away', 'MARGIN', 'FG_PCT_home', 'FT_PCT_home',
       'FG3_PCT_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'DATE',
       'HOME_ABBR', 'VISITOR_ABBR', 'home_winning_percentage',
       'visitor_winning_percentage', 'diff_%'],
      dtype='object')

In [22]:
combined_df = combined_df[['DATE','HOME_ABBR', 'VISITOR_ABBR', 'PTS_home', 'PTS_away', 'MARGIN', 'FG_PCT_home', 'FT_PCT_home',
       'FG3_PCT_home', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away','home_winning_percentage',
       'visitor_winning_percentage', 'diff_%']]

In [25]:
diff_df

,PTS_home,PTS_away,MARGIN,FG_PCT_home,FT_PCT_home,FG3_PCT_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away
0,0.975000,-4.262500,5.237500,0.008250,0.043875,0.033300,-0.027850,-0.096113,-0.004075
1,-8.500000,8.300000,-16.800000,-0.026275,-0.006500,-0.090800,0.025300,0.010000,0.060100
2,1.757143,-2.941429,4.698571,0.022857,-0.026150,0.022029,-0.000027,-0.008916,-0.004469
3,1.421429,-3.242857,4.664286,-0.001386,-0.005729,0.014157,-0.025000,0.004500,-0.000679
4,-9.700000,3.800000,-13.500000,-0.038400,-0.031300,-0.015400,-0.008500,-0.028600,-0.001600
5,-5.760000,-10.500000,4.740000,-0.023180,-0.057680,-0.021340,-0.004700,-0.043400,-0.077500
6,-4.933333,1.403333,-6.336667,-0.016717,0.013433,-0.041750,-0.000007,0.014913,-0.010133

In [24]:
grouped_df

,PTS_home,PTS_away,MARGIN,FG_PCT_home,FT_PCT_home,FG3_PCT_home,FG_PCT_away,FT_PCT_away,FG3_PCT_away
0,109.4,107.6,1.8,0.4495,0.7835,0.3392,0.4880,0.7338,0.3570
1,108.0,111.7,-3.7,0.4563,0.7949,0.3126,0.4802,0.8170,0.3739
2,120.1,111.4,8.7,0.5225,0.8399,0.3714,0.4548,0.8400,0.3415
3,114.0,119.7,-5.7,0.4553,0.7331,0.3466,0.4689,0.6748,0.3206
4,100.8,113.2,-12.4,0.4170,0.7777,0.3204,0.4895,0.7841,0.3181
5,105.2,108.5,-3.3,0.4371,0.7272,0.3505,0.4451,0.8052,0.3639
6,117.5,111.9,5.6,0.4846,0.7827,0.3820,0.4732,0.8259,0.3509

In [26]:
combined_df.to_csv('for_ml_feb_24.csv', index=False)

In [ ]:
date1 = grouped_df['DATE']
home_abbr1 = grouped_df['HOME_ABBR']
visitor_abbr1 = grouped_df['VISITOR_ABBR']
home_winning_percentage = grouped_df['home_winning_percentage']
visitor_winning_percentage = grouped_df['visitor_winning_percentage']
diff = grouped_df['diff_%']