In [2]:
pip install basketball-reference-scraper

Collecting basketball-reference-scraper
  Using cached basketball_reference_scraper-1.0.26-py3-none-any.whl (46 kB)
Collecting pandas==0.25.3
  Downloading pandas-0.25.3-cp38-cp38-macosx_10_9_x86_64.whl (10.3 MB)
     |████████████████████████████████| 10.3 MB 14.5 MB/s eta 0:00:01
Collecting lxml==4.4.2
  Downloading lxml-4.4.2.tar.gz (2.6 MB)
     |████████████████████████████████| 2.6 MB 40.6 MB/s eta 0:00:01
Collecting bs4==0.0.1
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
Collecting soupsieve==1.9.5
  Using cached soupsieve-1.9.5-py2.py3-none-any.whl (33 kB)
Collecting numpy==1.18.1
  Downloading numpy-1.18.1-cp38-cp38-macosx_10_9_x86_64.whl (15.2 MB)
     |████████████████████████████████| 15.2 MB 35.5 MB/s eta 0:00:01
Collecting pytz==2019.3
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting beautifulsoup4==4.8.2
  Using cached beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)
Requirement already satisfied: python-dateutil==2.8.1 in /Users/stanleytan/anaconda3/lib/python3.8/site-packages (from basketball-reference-scraper) (2.8.1)
Collecting six==1.13.0
  Using cached six-1.13.0-py2.py3-none-any.whl (10 kB)
Collecting requests==2.22.0
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/stanleytan/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/stanleytan/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (1.25.11)
Collecting idna<2.9,>=2.5
  Using cached idna-2.8-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: certifi>=2017.4.17 in /Users/stanleytan/anaconda3/lib/python3.8/site-packages (from requests==2.22.0->basketball-reference-scraper) (2020.6.20)
Building wheels for collected packages: lxml, bs4
  Building wheel for lxml (setup.py) ... done
  Created wheel for lxml: filename=lxml-4.4.2-cp38-cp38-macosx_10_9_x86_64.whl size=1787706 sha256=f37d00d5c1681cc6c554151f54eb613c40b7330f2107c9bc7348719f5408ec50
  Stored in directory: /Users/stanleytan/Library/Caches/pip/wheels/f0/48/b1/afbc9466bd44895c9ce63c8f43745399f5e8f6783c21f429de
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1273 sha256=2f91e586cb6a2865c6a2710daa9f7f94e0de96a0142cfd37f423f702221764f7
  Stored in directory: /Users/stanleytan/Library/Caches/pip/wheels/75/78/21/68b124549c9bdc94f822c02fb9aa3578a669843f9767776bca
Successfully built lxml bs4
Installing collected packages: numpy, pytz, pandas, lxml, soupsieve, beautifulsoup4, bs4, six, idna, requests, basketball-reference-scraper
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2
  Attempting uninstall: pytz
    Found existing installation: pytz 2020.1
    Uninstalling pytz-2020.1:
      Successfully uninstalled pytz-2020.1
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.3
    Uninstalling pandas-1.1.3:
      Successfully uninstalled pandas-1.1.3
  Attempting uninstall: lxml
    Found existing installation: lxml 4.6.1
    Uninstalling lxml-4.6.1:
      Successfully uninstalled lxml-4.6.1
  Attempting uninstall: soupsieve
    Found existing installation: soupsieve 2.0.1
    Uninstalling soupsieve-2.0.1:
      Successfully uninstalled soupsieve-2.0.1
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.9.3
    Uninstalling beautifulsoup4-4.9.3:
      Successfully uninstalled beautifulsoup4-4.9.3
  Attempting uninstall: six
    Found existing installation: six 1.15.0
    Uninstalling six-1.15.0:
      Successfully uninstalled six-1.15.0
  Attempting uninstall: idna
    Found existing installation: idna 2.10
    Uninstalling idna-2.10:
      Successfully uninstalled idna-2.10
  Attempting uninstall: requests
    Found existing installation: requests 2.24.0
    Uninstalling requests-2.24.0:
      Successfully uninstalled requests-2.24.0
Successfully installed basketball-reference-scraper-1.0.26 beautifulsoup4-4.8.2 bs4-0.0.1 idna-2.8 lxml-4.4.2 numpy-1.18.1 pandas-0.25.3 pytz-2019.3 requests-2.22.0 six-1.13.0 soupsieve-1.9.5
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install Unidecode

Collecting Unidecode
  Using cached Unidecode-1.1.2-py2.py3-none-any.whl (239 kB)
Installing collected packages: Unidecode
Successfully installed Unidecode-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
from basketball_reference_scraper.seasons import get_schedule, get_standings

df = get_schedule(2021, playoffs=False)

In [2]:
df

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS
0,2020-12-22,Golden State Warriors,99.0,Brooklyn Nets,125.0
1,2020-12-22,Los Angeles Clippers,116.0,Los Angeles Lakers,109.0
2,2020-12-23,Charlotte Hornets,114.0,Cleveland Cavaliers,121.0
3,2020-12-23,New York Knicks,107.0,Indiana Pacers,121.0
4,2020-12-23,Miami Heat,107.0,Orlando Magic,113.0
...,...,...,...,...,...
535,2021-03-04,Milwaukee Bucks,NaN,Memphis Grizzlies,NaN
536,2021-03-04,Oklahoma City Thunder,NaN,San Antonio Spurs,NaN
537,2021-03-04,Miami Heat,NaN,New Orleans Pelicans,NaN
538,2021-03-04,Golden State Warriors,NaN,Phoenix Suns,NaN
539,2021-03-04,Sacramento Kings,NaN,Portland Trail Blazers,NaN

In [21]:
team_to_abbreviation = {
    "ATLANTA HAWKS" : "ATL",
    "ST. LOUIS HAWKS" : "SLH",
    "MILWAUKEE HAWKS" : "MIL",
    "TRI-CITIES BLACKHAWKS" : "TCB",
    "BOSTON CELTICS" : "BOS",
    "BROOKLYN NETS" : "BRK",
    "NEW JERSEY NETS" : "NJN",
    "CHICAGO BULLS" : "CHI",
    "CHARLOTTE HORNETS": "CHO",
    "CHARLOTTE BOBCATS" : "CHA",
    "CLEVELAND CAVALIERS": "CLE",
    "DALLAS MAVERICKS" : "DAL",
    "DENVER NUGGETS" : "DEN",
    "DETROIT PISTONS" : "DET",
    "FORT WAYNE PISTONS" : "FWP",
    "GOLDEN STATE WARRIORS" : "GSW",
    "SAN FRANCISCO WARRIORS" : "SFW",
    "PHILADELPHIA WARRIORS" : "PHI",
    "HOUSTON ROCKETS" : "HOU",
    "INDIANA PACERS" : "IND",
    "LOS ANGELES CLIPPERS" : "LAC",
    "SAN DIEGO CLIPPERS" : "SDC",
    "BUFFALO BRAVES" : "BUF",
    "LOS ANGELES LAKERS" : "LAL",
    "MINNEAPOLIS LAKERS" : "MIN",
    "MEMPHIS GRIZZLIES" : "MEM",
    "VANCOUVER GRIZZLIES" : 'VAN',
    "MIAMI HEAT" : "MIA",
    "MILWAUKEE BUCKS" : "MIL",
    "MINNESOTA TIMBERWOLVES" : "MIN",
    "NEW ORLEANS PELICANS" : "NOP",
    "NEW ORLEANS/OKLAHOMA CITY HORNETS" : "NOK",
    "NEW ORLEANS HORNETS" : "NOH",
    "NEW YORK KNICKS" : "NYK",
    "OKLAHOMA CITY THUNDER" : "OKC",
    "SEATTLE SUPERSONICS" : "SEA",
    "ORLANDO MAGIC" : "ORL",
    "PHILADELPHIA 76ERS" : "PHI",
    "SYRACUSE NATIONALS" : "SYR",
    "PHOENIX SUNS" : "PHO",
    "PORTLAND TRAIL BLAZERS" : "POR",
    "SACRAMENTO KINGS" : "SAC",
    "KANSAS CITY KINGS" : "KCK",
    "KANSAS CITY-OMAHA KINGS" : "KCK",
    "CINCINNATI ROYALS" : "CIN",
    "ROCHESTER ROYALS" : "ROR",
    "SAN ANTONIO SPURS" : "SAS",
    "TORONTO RAPTORS" : "TOR",
    "UTAH JAZZ" : "UTA",
    "NEW ORLEANS JAZZ" : "NOJ",
    "WASHINGTON WIZARDS" : "WAS",
    "WASHINGTON BULLETS" : "WAS",
    "CAPITAL BULLETS" : "CAP",
    "BALTIMORE BULLETS" : "BAL",
    "CHICAGO ZEPHYRS" : "CHI",
    "CHICAGO PACKERS" : "CHI",
    "ANDERSON PACKERS" : "AND",
    "CHICAGO STAGS" : "CHI",
    "INDIANAPOLIS OLYMPIANS" : "IND",
    "SHEBOYGAN RED SKINS" : "SRS",
    "ST. LOUIS BOMBERS" : "SLB",
    "WASHINGTON CAPITOLS" : "WAS",
    "WATERLOO HAWKS" : "WAT"
}

In [5]:
schedule_df = df.copy()

In [9]:
schedule_df['MARGIN'] = 0
schedule_df['HOME_ABBR'] = 0
schedule_df['VISITOR_ABBR'] = 0
schedule_df = schedule_df.fillna(0)

In [22]:
team_to_abbreviation['ATLANTA HAWKS']

'ATL'

In [25]:
for ind in schedule_df.index: 
    schedule_df['MARGIN'][ind] = schedule_df['HOME_PTS'][ind] - schedule_df['VISITOR_PTS'][ind]
    schedule_df['VISITOR'][ind] = schedule_df['VISITOR'][ind].upper()
    schedule_df['HOME'][ind] = schedule_df['HOME'][ind].upper()
    schedule_df['HOME_ABBR'][ind] = team_to_abbreviation[schedule_df['HOME'][ind]]
    schedule_df['VISITOR_ABBR'][ind] = team_to_abbreviation[schedule_df['VISITOR'][ind]]

<ipython-input-25-05614a8d751e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule_df['MARGIN'][ind] = schedule_df['HOME_PTS'][ind] - schedule_df['VISITOR_PTS'][ind]
<ipython-input-25-05614a8d751e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule_df['VISITOR'][ind] = schedule_df['VISITOR'][ind].upper()
<ipython-input-25-05614a8d751e>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule_df['HOME'][ind] = schedule_df['HOME'][ind].upper()
<ipython-input-25-05614a8d751e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule_df['HOME_ABBR'][ind] = team_to_abbreviation[schedule_df['HOME'][ind]]
<ipython-input-25-05614a8d751e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schedule_df['VISITOR_ABBR'][ind] = team_to_abbreviation[schedule_df['VISITOR'][ind]]

In [26]:
schedule_df

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,26,BRK,GSW
1,2020-12-22,LOS ANGELES CLIPPERS,116.0,LOS ANGELES LAKERS,109.0,-7,LAL,LAC
2,2020-12-23,CHARLOTTE HORNETS,114.0,CLEVELAND CAVALIERS,121.0,7,CLE,CHO
3,2020-12-23,NEW YORK KNICKS,107.0,INDIANA PACERS,121.0,14,IND,NYK
4,2020-12-23,MIAMI HEAT,107.0,ORLANDO MAGIC,113.0,6,ORL,MIA
...,...,...,...,...,...,...,...,...
535,2021-03-04,MILWAUKEE BUCKS,0.0,MEMPHIS GRIZZLIES,0.0,0,MEM,MIL
536,2021-03-04,OKLAHOMA CITY THUNDER,0.0,SAN ANTONIO SPURS,0.0,0,SAS,OKC
537,2021-03-04,MIAMI HEAT,0.0,NEW ORLEANS PELICANS,0.0,0,NOP,MIA
538,2021-03-04,GOLDEN STATE WARRIORS,0.0,PHOENIX SUNS,0.0,0,PHO,GSW
539,2021-03-04,SACRAMENTO KINGS,0.0,PORTLAND TRAIL BLAZERS,0.0,0,POR,SAC

In [16]:
schedule_df

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,26,0,0
1,2020-12-22,LOS ANGELES CLIPPERS,116.0,LOS ANGELES LAKERS,109.0,-7,0,0
2,2020-12-23,CHARLOTTE HORNETS,114.0,CLEVELAND CAVALIERS,121.0,7,0,0
3,2020-12-23,NEW YORK KNICKS,107.0,INDIANA PACERS,121.0,14,0,0
4,2020-12-23,MIAMI HEAT,107.0,ORLANDO MAGIC,113.0,6,0,0
...,...,...,...,...,...,...,...,...
535,2021-03-04,MILWAUKEE BUCKS,0.0,MEMPHIS GRIZZLIES,0.0,0,0,0
536,2021-03-04,OKLAHOMA CITY THUNDER,0.0,SAN ANTONIO SPURS,0.0,0,0,0
537,2021-03-04,MIAMI HEAT,0.0,NEW ORLEANS PELICANS,0.0,0,0,0
538,2021-03-04,GOLDEN STATE WARRIORS,0.0,PHOENIX SUNS,0.0,0,0,0
539,2021-03-04,SACRAMENTO KINGS,0.0,PORTLAND TRAIL BLAZERS,0.0,0,0,0

In [51]:
partial_schedule = schedule_df.loc[schedule_df['VISITOR_PTS'] != 0]

In [52]:
end_a = len(partial_schedule) + 1
a_ = list(range(1, end_a))
partial_schedule['ID'] = a_

<ipython-input-52-3fb2d3cbc4ef>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  partial_schedule['ID'] = a_

In [54]:
partial_schedule.head(1)

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR,ID
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,26,BRK,GSW,1

In [56]:
end_a = len(schedule_df) + 1
a_ = list(range(1, end_a))
schedule_df['ID'] = a_

In [57]:
schedule_df

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR,ID
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,26,BRK,GSW,1
1,2020-12-22,LOS ANGELES CLIPPERS,116.0,LOS ANGELES LAKERS,109.0,-7,LAL,LAC,2
2,2020-12-23,CHARLOTTE HORNETS,114.0,CLEVELAND CAVALIERS,121.0,7,CLE,CHO,3
3,2020-12-23,NEW YORK KNICKS,107.0,INDIANA PACERS,121.0,14,IND,NYK,4
4,2020-12-23,MIAMI HEAT,107.0,ORLANDO MAGIC,113.0,6,ORL,MIA,5
...,...,...,...,...,...,...,...,...,...
535,2021-03-04,MILWAUKEE BUCKS,0.0,MEMPHIS GRIZZLIES,0.0,0,MEM,MIL,536
536,2021-03-04,OKLAHOMA CITY THUNDER,0.0,SAN ANTONIO SPURS,0.0,0,SAS,OKC,537
537,2021-03-04,MIAMI HEAT,0.0,NEW ORLEANS PELICANS,0.0,0,NOP,MIA,538
538,2021-03-04,GOLDEN STATE WARRIORS,0.0,PHOENIX SUNS,0.0,0,PHO,GSW,539
539,2021-03-04,SACRAMENTO KINGS,0.0,PORTLAND TRAIL BLAZERS,0.0,0,POR,SAC,540

In [32]:
#import dependencies
import sqlalchemy
# Import dependencies
import pandas as pd
from sqlalchemy import create_engine

# N.B. external config.py file should be formatted like:
# login = 'postgres:password' where password is set to whatever your database password is. Default username is 
# postgres, but change this if you use a different username.
import psycopg2
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'
                .format(username='postgres',
                        password='postgres',
                        ipaddress='localhost',
                        port=5432,
                        dbname='flask_deploy'))
# Create the connection
engine = create_engine(postgres_str)
cnx = engine.connect()

In [58]:
partial_schedule.head(1)

,DATE,VISITOR,VISITOR_PTS,HOME,HOME_PTS,MARGIN,HOME_ABBR,VISITOR_ABBR,ID
0,2020-12-22,GOLDEN STATE WARRIORS,99.0,BROOKLYN NETS,125.0,26,BRK,GSW,1

In [59]:
partial_schedule.to_sql('partial_schedule', engine, if_exists='append', index=False)

In [61]:
partial_schedule.to_csv('partial_schedule_2021.csv', index=False)

In [60]:
schedule_df.to_sql('full_schedule', engine, if_exists='append', index=False)

In [ ]:
CREATE TABLE partial_schedule (
     "ID" INT PRIMARY KEY, 
     "DATE" DATE,
     "VISITOR" VARCHAR, 
     "VISITOR_PTS" INT, 
     "HOME" VARCHAR,
     "HOME_PTS" INT,
     "MARGIN" INT,
     "HOME_ABBR" VARCHAR,
     "VISITOR_ABBR" VARCHAR
)

CREATE TABLE full_schedule (
     "ID" INT PRIMARY KEY, 
     "DATE" DATE,
     "VISITOR" VARCHAR, 
     "VISITOR_PTS" INT, 
     "HOME" VARCHAR,
     "HOME_PTS" INT,
     "MARGIN" INT,
     "HOME_ABBR" VARCHAR,
     "VISITOR_ABBR" VARCHAR
)

```sql

CREATE TABLE boxscore_2021 (
    "ID" INT PRIMARY KEY, 
    "DATE" DATE,
    "HOME_ABBR" VARCHAR,
	"MARGIN" INT,
    "VISITOR_ABBR" VARCHAR,
    "PTS_home" INT,
    "PTS_away" INT,
    "FG_PCT_home" DOUBLE PRECISION,
    "FT_PCT_home" DOUBLE PRECISION,
    "FG3_PCT_home" DOUBLE PRECISION,
    "AST_home" INT,
    "REB_home" INT,
    "FG_PCT_away" DOUBLE PRECISION,
    "FT_PCT_away" DOUBLE PRECISION,
    "FG3_PCT_away" DOUBLE PRECISION,
    "AST_away" INT,
    "REB_away" INT
);

```